const API='https://lahajlrombmoftevweaf.supabase.co', KEY='sb_publishable_ixLS7JIsBDtPF75R-rZwcA_2eAD0bKV';
const $=id=>document.getElementById(id), money=v=>v==null?'Sob consulta':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeImage=url=>{try{return new URL(url).protocol==='https:'?url:''}catch{return ''}};
async function api(path,options={},token){const r=await fetch(API+path,{...options,headers:{apikey:KEY,Authorization:'Bearer '+(token||KEY),'Content-Type':'application/json',...options.headers}});let d=await r.json().catch(()=>null);if(!r.ok)throw Error(d?.msg||d?.message||'Não foi possível concluir. Tente novamente.');return d;}
let products=[],phone='',selection=[];try{selection=JSON.parse(localStorage.getItem('videira-selection')||'[]');if(!Array.isArray(selection))selection=[]}catch{};
function persist(){localStorage.setItem('videira-selection',JSON.stringify(selection));if($('count'))$('count').textContent=selection.reduce((a,b)=>a+b.qty,0);}
function add(id){const p=products.find(p=>p.id===id);if(!p)return;const item=selection.find(p=>p.id===id);if(item)item.qty=Math.min(99,item.qty+1);else selection.push({id,qty:1});persist();renderCart();$('cart').showModal();}
function renderCart(){selection=selection.filter(i=>products.some(p=>p.id===i.id));persist();$('cartItems').innerHTML=selection.length?selection.map(i=>{const p=products.find(p=>p.id===i.id);return `<div class="cart-row"><div>${esc(p.name)}<p class="muted">${money(p.price)}</p></div><div class="qty"><button data-qty="${i.id}" data-change="-1" aria-label="Diminuir quantidade">−</button><span>${i.qty}</span><button data-qty="${i.id}" data-change="1" aria-label="Aumentar quantidade">+</button></div></div>`}).join(''):'<p class="muted">Sua seleção está vazia. Explore o catálogo e escolha seus rótulos.</p>';
const unknown=selection.some(i=>products.find(p=>p.id===i.id).price==null);$('total').textContent=selection.length?(unknown?'Valores a confirmar no atendimento':'Subtotal: '+money(selection.reduce((s,i)=>s+Number(products.find(p=>p.id===i.id).price)*i.qty,0))):'';
const msg='Olá! Gostaria de consultar esta seleção da Videira:\n'+selection.map(i=>i.qty+' × '+products.find(p=>p.id===i.id).name).join('\n')+'\nPode confirmar disponibilidade, valores e entrega?';$('checkout').hidden=!selection.length||!phone;if(phone)$('checkout').href='https://wa.me/'+phone+'?text='+encodeURIComponent(msg);}
function render(){const term=$('search').value.toLocaleLowerCase('pt-BR');let list=products.filter(p=>[p.name,p.country,p.grape,p.winery,p.description].join(' ').toLocaleLowerCase('pt-BR').includes(term)&&['country','grape','category','winery'].every(k=>!$(k).value||p[k]===$(k).value));if($('sort').value==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));if($('sort').value==='price')list.sort((a,b)=>(a.price==null?Infinity:Number(a.price))-(b.price==null?Infinity:Number(b.price)));$('resultCount').textContent=list.length+' rótulo'+(list.length===1?'':'s');$('products').innerHTML=list.length?list.map(p=>`<article class="product"><button class="product-view" data-detail="${p.id}" aria-label="Ver detalhes de ${esc(p.name)}">${safeImage(p.image_url)?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" loading="lazy">`:'<div class="placeholder" aria-hidden="true">V</div>'}<p class="eyebrow">${esc(p.country||p.category)}</p><h3>${esc(p.name)}</h3><p>${esc(p.winery)}<br>${esc(p.grape)}</p></button><div class="product-bottom"><strong>${money(p.price)}</strong><button class="add" data-add="${p.id}" aria-label="Adicionar ${esc(p.name)}">+</button></div></article>`).join(''):`<div class="empty"><h3>${products.length?'Nenhum rótulo encontrado':'Novas descobertas em breve.'}</h3><span>${products.length?'Experimente outra busca ou limpe os filtros.':'Estamos preparando nossa seleção de vinhos.<br>Fale com a equipe para conhecer os rótulos disponíveis.'}</span>${phone?`<a class="text-button" href="https://wa.me/${phone}" target="_blank" rel="noopener">Conversar com a Videira ↗</a>`:''}</div>`;}
async function initStore(){persist();if(sessionStorage.getItem('videira-adult')!=='yes')$('age').showModal();$('ageYes').onclick=()=>{sessionStorage.setItem('videira-adult','yes');$('age').close()};$('age').addEventListener('cancel',e=>e.preventDefault());$('ageNo').onclick=()=>{$('ageMessage').textContent='O acesso ao catálogo é permitido somente para maiores de 18 anos.';$('ageYes').hidden=true};
document.addEventListener('click',e=>{let b=e.target.closest('[data-add],[data-detail],[data-close],[data-qty]');if(!b)return;if(b.dataset.close)$(b.dataset.close).close();if(b.dataset.add)add(b.dataset.add);if(b.dataset.qty){const i=selection.find(i=>i.id===b.dataset.qty);i.qty=Math.min(99,i.qty+Number(b.dataset.change));selection=selection.filter(i=>i.qty>0);persist();renderCart()}if(b.dataset.detail){const p=products.find(p=>p.id===b.dataset.detail);$('detailContent').innerHTML=`<p class="eyebrow">${esc(p.country)} · ${esc(p.category)}</p><h2>${esc(p.name)}</h2>${safeImage(p.image_url)?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:''}<p>${esc(p.description||'Consulte nossa equipe para conhecer melhor este rótulo.')}</p><p class="muted">${esc(p.grape)} · ${esc(p.winery)}</p><p>${money(p.price)}</p><button class="pill" data-add="${p.id}">Adicionar à seleção</button>`;$('detail').showModal()}});
$('cartButton').onclick=()=>{renderCart();$('cart').showModal()};$('search').oninput=render;['country','grape','category','winery','sort'].forEach(k=>$(k).onchange=render);$('clear').onclick=()=>{$('search').value='';['country','grape','category','winery'].forEach(k=>$(k).value='');render()};
try{const [p,s]=await Promise.all([api('/rest/v1/products?select=*&active=eq.true&order=created_at.desc'),api('/rest/v1/store_settings?select=whatsapp')]);products=p;phone=s[0]?.whatsapp||'';if(phone){$('contact').href='https://wa.me/'+phone;$('contact').target='_blank';$('contact').rel='noopener'}else $('contact').hidden=true;['country','grape','category','winery'].forEach(k=>[...new Set(products.map(p=>p[k]).filter(Boolean))].sort().forEach(v=>$(k).add(new Option(v,v))));let countries=[...new Set(products.map(p=>p.country).filter(Boolean))];$('countries').innerHTML=(countries.length?countries.slice(0,4):['Brasil','Argentina','Chile','Portugal']).map(c=>`<button class="country-card" data-country="${esc(c)}"><small>EXPLORE A SELEÇÃO</small><span>${esc(c)}</span><small>Descobrir rótulos ↗</small></button>`).join('');$('countries').onclick=e=>{const b=e.target.closest('[data-country]');if(b){$('country').value=b.dataset.country;render();$('catalogo').scrollIntoView()}};render();renderCart();}catch(e){$('products').innerHTML='<div class="empty"><h3>Não foi possível carregar o catálogo.</h3><p>Atualize a página para tentar novamente.</p></div>'}}
let session=null;
async function adminLoad(){const p=await api('/rest/v1/products?select=*&order=created_at.desc',{},session.access_token);products=p;$('adminList').innerHTML=p.map(p=>`<div class="admin-item"><span>${esc(p.name)} · ${money(p.price)} · ${p.active?'Publicado':'Oculto'}</span><button class="text-button" data-edit="${p.id}">Editar</button></div>`).join('')||'<p>Nenhum produto cadastrado. Adicione o primeiro rótulo abaixo.</p>';const s=await api('/rest/v1/store_settings?select=whatsapp',{},session.access_token);$('whatsapp').value=s[0]?.whatsapp||'';}
async function initAdmin(){const status=$('status');$('login').onsubmit=async e=>{e.preventDefault();status.textContent='Entrando…';try{session=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});$('password').value='';if(session.user.app_metadata?.role!=='admin'){session=null;throw Error('Esta conta ainda não tem acesso de administrador.')}await adminLoad();$('login').hidden=true;$('panel').hidden=false;status.textContent='Conectado. Você pode cadastrar e editar os produtos.';}catch(e){status.textContent=e.message}};
$('logout').onclick=async()=>{try{await api('/auth/v1/logout',{method:'POST'},session.access_token)}catch{}session=null;$('panel').hidden=true;$('login').hidden=false;status.textContent='Sessão encerrada.'};$('adminList').onclick=e=>{const b=e.target.closest('[data-edit]');if(!b)return;const p=products.find(p=>p.id===b.dataset.edit);$('productId').value=p.id;['name','country','grape','winery','category','description','image_url','price'].forEach(k=>$(k).value=p[k]??'');$('active').checked=p.active;$('featured').checked=p.featured;$('productForm').scrollIntoView()};$('reset').onclick=()=>{$('productForm').reset();$('productId').value=''};
$('productForm').onsubmit=async e=>{e.preventDefault();const save=$('save');save.disabled=true;try{let p={};['name','country','grape','winery','category','description','image_url'].forEach(k=>p[k]=$(k).value.trim());if(p.image_url&&!safeImage(p.image_url))throw Error('Use uma URL de imagem HTTPS válida.');p.price=$('price').value===''?null:Number($('price').value);p.active=$('active').checked;p.featured=$('featured').checked;const id=$('productId').value;await api('/rest/v1/products'+(id?'?id=eq.'+encodeURIComponent(id):''),{method:id?'PATCH':'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(p)},session.access_token);$('productForm').reset();$('productId').value='';await adminLoad();status.textContent='Produto salvo com sucesso.'}catch(e){status.textContent=e.message}finally{save.disabled=false}};
$('settingsForm').onsubmit=async e=>{e.preventDefault();try{const whatsapp=$('whatsapp').value.replace(/\D/g,'');if(!/^\d{10,15}$/.test(whatsapp))throw Error('Informe o número com código do país e DDD.');await api('/rest/v1/store_settings?id=eq.true',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({whatsapp})},session.access_token);status.textContent='WhatsApp atualizado.'}catch(e){status.textContent=e.message}};}
if($('products'))initStore();if($('login'))initAdmin();