let catalogTerms=[],storeSettings={};
function promoActive(p,now=Date.now()){return (!p.promotion_start||Date.parse(p.promotion_start)<=now)&&(!p.promotion_end||Date.parse(p.promotion_end)>=now)}
function catalogPrice(p,method='geral',now=Date.now()){if(p.price==null)return null;const active=promoActive(p,now);const general=active&&p.sale_price!=null?Number(p.sale_price):Number(p.price);return active&&method==='pix'&&p.pix_price!=null?Number(p.pix_price):active&&method==='cartao'&&p.card_price!=null?Number(p.card_price):general}
function termDescendants(id){const ids=new Set([id]);for(let changed=true;changed;){changed=false;for(const t of catalogTerms)if(ids.has(t.parent_id)&&!ids.has(t.id)){ids.add(t.id);changed=true}}return ids}
function facetNames(p,kind){const ids=new Set(p.term_ids||[]);const names=catalogTerms.filter(t=>t.kind===kind&&ids.has(t.id)).map(t=>t.name);return names.length?names:[p[{tipo:'category',uva:'grape',pais:'country',bodega:'winery'}[kind]]].filter(Boolean)}
function matchesTerm(p,id){const allowed=termDescendants(id);return (p.term_ids||[]).some(t=>allowed.has(t))||catalogTerms.filter(t=>allowed.has(t.id)).some(t=>facetNames(p,t.kind).includes(t.name))}
function installmentText(p){const total=catalogPrice(p,'cartao');if(total==null)return '';const minimum=Number(storeSettings.card_min_installment)||0;const max=Number(storeSettings.card_installments)||1;const count=Math.max(1,Math.min(max,minimum?Math.floor(total/minimum):max));return count>1?`${count}x de ${money(total/count)}${storeSettings.card_interest_free?' sem juros':''}`:''}
function priceHtml(p){if(storeSettings.show_prices===false)return '<span class="catalog-payment">Consulte as condições no atendimento</span>';const current=catalogPrice(p);if(current==null)return '<strong>Sob consulta</strong>';const sale=promoActive(p)&&p.sale_price!=null;const pix=promoActive(p)&&p.pix_price!=null;const card=promoActive(p)&&p.card_price!=null;return `<span class="catalog-price">${sale?`<del>${money(p.price)}</del>`:''}<strong>${money(current)}</strong>${pix?`<small>${money(catalogPrice(p,'pix'))} no Pix</small>`:''}${card?`<small>${money(catalogPrice(p,'cartao'))} no cartão</small>`:''}${installmentText(p)?`<small>${esc(installmentText(p))}</small>`:''}</span>`}
async function catalogRows(path){const all=[];for(let offset=0;;offset+=500){const rows=await api(path+(path.includes('?')?'&':'?')+'limit=500&offset='+offset);all.push(...rows);if(rows.length<500)return all}}
async function loadCatalog(){const [p,s,t]=await Promise.all([catalogRows('/rest/v1/products?select=*&active=eq.true&order=created_at.desc'),api('/rest/v1/store_settings?select=*'),catalogRows('/rest/v1/catalog_terms?select=*&order=name.asc')]);products=p;storeSettings=s[0]||{};catalogTerms=t;phone=storeSettings.whatsapp||'';applyStoreSettings();return [p,s]}
function applyStoreSettings(){const s=storeSettings;if(s.store_name){document.title=s.store_name+' | '+(document.body.dataset.layout==='home'?s.tagline||'Vinhos':'Catálogo de vinhos');document.querySelectorAll('.header-logo').forEach(a=>a.setAttribute('aria-label',s.store_name));if(s.store_name!=='Videira Vinhoteca')document.querySelectorAll('.logo-word,.footer-brand').forEach(el=>el.textContent=s.store_name)}if(s.meta_description){let meta=document.querySelector('meta[name="description"]');if(meta)meta.content=s.meta_description}if(s.logo_url&&safeImage(s.logo_url))document.querySelectorAll('.header-logo img').forEach(img=>{img.src=s.logo_url;img.alt=s.store_name||'Logo da loja'});if(/^#[0-9a-f]{6}$/i.test(s.primary_color||''))document.documentElement.style.setProperty('--videira-color',s.primary_color);
 const hero=document.querySelector('.hero-slide');if(hero){if(s.hero_title)hero.querySelector('h1').textContent=s.hero_title;if(s.hero_text)hero.querySelector('.hero-copy p').textContent=s.hero_text;if(s.hero_image_url&&safeImage(s.hero_image_url))hero.style.setProperty('--hero-image',`url("${s.hero_image_url.replace(/["\\\n\r]/g,encodeURIComponent)}")`);const button=hero.querySelector('a');if(s.hero_link_label)button.textContent=s.hero_link_label;if(s.hero_link_url==='/loja'||safeImage(s.hero_link_url))button.href=s.hero_link_url}
 if(s.featured_title){const el=document.querySelector('#selecao h2');if(el)el.textContent=s.featured_title}let announcement=document.querySelector('.catalog-announcement');if(s.announcement){if(!announcement){announcement=document.createElement('div');announcement.className='catalog-announcement';document.querySelector('main').prepend(announcement)}announcement.textContent=s.announcement}
 let footer=document.querySelector('footer');if(!footer){footer=document.createElement('footer');footer.className='catalog-footer';document.querySelector('main').after(footer)}let info=footer.querySelector('.catalog-store-info');if(!info){info=document.createElement('div');info.className='catalog-store-info';footer.append(info)}info.replaceChildren();for(const value of [s.store_name,s.address,s.opening_hours,s.footer_text,s.payment_note].filter(Boolean)){const line=document.createElement('p');line.textContent=value;info.append(line)}if(s.contact_email){const a=document.createElement('a');a.href='mailto:'+s.contact_email;a.textContent=s.contact_email;info.append(a)}if(s.instagram_url&&safeImage(s.instagram_url)){const a=document.createElement('a');a.href=s.instagram_url;a.textContent='Instagram';a.target='_blank';a.rel='noopener';info.append(a)}if(phone)document.querySelectorAll('a[href^="https://wa.me/"]').forEach(a=>a.href='https://wa.me/'+phone);const existing=footer.querySelector(':scope > p');if(existing&&s.footer_text)existing.hidden=true;
 const cart=document.getElementById('cart');if(cart&&!document.getElementById('cartPayment')){const label=document.createElement('label');label.className='catalog-cart-payment';label.textContent='Forma de pagamento para consultar valores';const select=document.createElement('select');select.id='cartPayment';select.add(new Option('Preço geral','geral'));select.add(new Option('Pix','pix'));select.add(new Option('Cartão','cartao'));select.onchange=()=>renderCart();label.append(select);document.getElementById('cartItems').before(label)}
}
