'use strict';
const BASE='https://lahajlrombmoftevweaf.supabase.co',KEY='sb_publishable_ixLS7JIsBDtPF75R-rZwcA_2eAD0bKV';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let refreshing=null,session=null,expires=0,erp=null,revision=0,products=[],terms=[],settings={},system='erp',page='Resumo',saveAction=null,busy=false,dirty=false;
const localDate=v=>{const d=new Date(v);return Number.isNaN(d.valueOf())?'':new Date(d.valueOf()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const labels={name:'Nome',price:'Preço normal',sale_price:'Promoção',pix_price:'Pix',card_price:'Cartão',active:'Publicado',featured:'Destaque',kind:'Grupo',parent_id:'Categoria superior'};
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const editable=new Set(['Produtos','Clientes','Fornecedores','Despesas','Taxas','Empresa','Plano mensal']);
function message(text,error=false){$('#notice').textContent=text;$('#notice').classList.toggle('error',error)}
async function request(path,method='GET',body,refresh=true){
 if(refresh&&session&&Date.now()>expires){if(!refreshing)refreshing=request('/auth/v1/token?grant_type=refresh_token','POST',{refresh_token:session.refresh_token},false).then(next=>{session=next;expires=Date.now()+(next.expires_in-60)*1000}).finally(()=>refreshing=null);await refreshing}
 const headers={apikey:KEY,'Content-Type':'application/json',Authorization:'Bearer '+(session?.access_token||KEY),Prefer:'return=representation'};
 const r=await fetch(BASE+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});
 const text=await r.text();let data;try{data=text?JSON.parse(text):null}catch{throw Error('Resposta inesperada. Tente novamente.')}
 if(!r.ok)throw Error(data?.msg||data?.message||data?.error_description||'Não foi possível concluir a ação.');return data;
}
async function all(table){let rows=[],offset=0;for(;;){let part=await request('/rest/v1/'+table+'?select=*&limit=500&offset='+offset);rows.push(...part);if(part.length<500)return rows;offset+=500}}
async function load(){const [work,p,t,s]=await Promise.all([request('/rest/v1/erp_workspaces?select=payload,revision'),all('products'),all('catalog_terms'),request('/rest/v1/store_settings?select=*')]);erp=work[0]?.payload||null;revision=work[0]?.revision||0;products=p;terms=t;settings=s[0]||{};dirty=false}
async function guarded(action){if(busy)return;busy=true;try{await action()}catch(e){message(e.message,true)}finally{busy=false}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$('#loginError').textContent='Conectando…';try{session=await request('/auth/v1/token?grant_type=password','POST',{email:$('#email').value.trim(),password:$('#password').value},false);expires=Date.now()+(session.expires_in-60)*1000;$('#password').value='';await load();$('#account').textContent=session.user.email;$('#login').hidden=true;$('#login').style.display='none';$('#app').hidden=false;render();}catch(error){session=null;$('#loginError').textContent=error.message==='Invalid login credentials'?'E-mail ou senha incorretos.':error.message}finally{button.disabled=false}};
$('#logout').onclick=()=>guarded(async()=>{if(dirty&&!confirm('Descartar alterações não salvas e sair?'))return;try{await request('/auth/v1/logout','POST',{})}finally{session=null;erp=null;products=[];terms=[];settings={};location.reload()}});
$('#refresh').onclick=()=>guarded(async()=>{if(dirty&&!confirm('Descartar alterações do formulário e sincronizar?'))return;$('#editor').close();await load();render();message('Dados atualizados com o banco online.')});
$('#menu').onclick=()=>document.querySelector('aside').classList.toggle('open');
document.querySelectorAll('[data-system]').forEach(b=>b.onclick=()=>{system=b.dataset.system;page='Resumo';render()});
function rows(name){return erp?.tables[name]?.rows||[]}
function nextId(name){return Math.max(0,...rows(name).map(r=>Number(r.Id)||0))+1}
function defaultRow(name){return Object.fromEntries(erp.tables[name].columns.map(c=>[c.name,c.default_value??(c.type==='date'?new Date().toISOString():c.type==='text'?'':c.type==='bool'?false:0)]))}
async function commit(change){const copy=structuredClone(erp);change(copy);const result=await request('/rest/v1/rpc/save_erp_workspace','POST',{expected_revision:revision,new_payload:copy});erp=copy;revision=result.revision;dirty=false;return result}
function render(){document.querySelectorAll('[data-system]').forEach(b=>b.classList.toggle('active',b.dataset.system===system));const pages=system==='erp'?['Resumo',...Object.keys(erp?.tables||{})]:['Resumo','Produtos','Categorias','Configurações'];$('#nav').innerHTML=pages.map(p=>'<button data-page="'+esc(p)+'" class="'+(p===page?'active':'')+'">'+esc(p)+'</button>').join('');$('#nav').querySelectorAll('button').forEach(b=>b.onclick=()=>{page=b.dataset.page;document.querySelector('aside').classList.remove('open');render()});$('#notice').textContent='';if(page==='Resumo')summary();else if(system==='erp')erpTable();else if(page==='Produtos')siteProducts();else if(page==='Categorias')categories();else settingsPage()}
function summary(){if(system==='erp'&&!erp){$('#content').innerHTML='<h1>Gestão</h1><div class="card">Sua conta não possui uma base do Gestão vinculada.</div>';return}let stats=system==='erp'?[['Produtos',rows('Produtos').length],['Clientes',rows('Clientes').length],['Vendas',rows('Vendas').filter(r=>r.Situação==='Concluída').length],['Estoque',rows('Produtos').reduce((n,r)=>n+Number(r.Estoque||0),0)]]:[['Produtos',products.length],['Publicados',products.filter(p=>p.active).length],['Categorias',terms.length],['Destaques',products.filter(p=>p.featured).length]];$('#content').innerHTML='<h1>'+esc(system==='erp'?'Gestão • Visão geral':'Site • Visão geral')+'</h1><p>Seus dados disponíveis em qualquer dispositivo após o login.</p><div class="metrics">'+stats.map(([k,v])=>'<div class="card metric">'+esc(k)+'<strong>'+v+'</strong></div>').join('')+'</div><div class="panelGrid"><div class="card"><h2>Acesso online</h2><p>As alterações salvas aqui são gravadas no mesmo banco usado pelo aplicativo do computador. Use Sincronizar para carregar alterações de outro dispositivo.</p><span class="badge">Conectado ao Supabase</span></div><div class="card"><h2>'+ (system==='erp'?'Operação e cadastros':'Administração da loja')+'</h2><p>'+(system==='erp'?'Consulte todas as tabelas, edite produtos e cadastros, registre despesas e movimente o estoque. As vendas e conversões de orçamentos continuam disponíveis no aplicativo Windows, já conectado ao banco online.':'Edite produtos, preços promocionais, categorias e configurações. O catálogo público recebe as alterações salvas.')+'</p></div></div>'}
function tableView(columns,data,action,extra=''){let search='',index=0,size=30;$('#content').innerHTML='<h1>'+esc(page)+'</h1><div class="toolbar"><input id="search" type="search" placeholder="Pesquisar nesta lista…" aria-label="Pesquisar"><span class="grow"></span>'+extra+'</div><div class="tableWrap"><table><thead><tr>'+columns.map(c=>'<th>'+esc(labels[c]||c)+'</th>').join('')+(action?'<th>Ações</th>':'')+'</tr></thead><tbody></tbody></table><div class="pager"><span id="count"></span><button id="prev">Anterior</button><button id="next">Próxima</button></div></div>';function paint(){const filtered=data.filter(r=>Object.values(r).some(v=>String(v??'').toLocaleLowerCase('pt-BR').includes(search)));index=Math.min(index,Math.max(0,Math.ceil(filtered.length/size)-1));const slice=filtered.slice(index*size,(index+1)*size);$('tbody').innerHTML=slice.map((r,i)=>'<tr>'+columns.map(c=>'<td title="'+esc(r[c])+'">'+esc(typeof r[c]==='boolean'?(r[c]?'Sim':'Não'):String(r[c]??'').slice(0,120))+'</td>').join('')+(action?'<td><button data-row="'+i+'">Abrir</button></td>':'')+'</tr>').join('');$('tbody').querySelectorAll('button').forEach(b=>b.onclick=()=>action(slice[Number(b.dataset.row)]));$('#count').textContent=filtered.length+' registros • página '+(index+1);$('#prev').disabled=index===0;$('#next').disabled=(index+1)*size>=filtered.length}$('#search').oninput=e=>{search=e.target.value.toLocaleLowerCase('pt-BR');index=0;paint()};$('#prev').onclick=()=>{index--;paint()};$('#next').onclick=()=>{index++;paint()};paint()}
function erpTable(){const table=erp.tables[page],can=editable.has(page);let columns=table.columns.map(c=>c.name);tableView(columns,table.rows,can?r=>erpEdit(r):r=>readRow(r,table),can?'<button class="primary" id="add">Adicionar</button>':'');if(can)$('#add').onclick=()=>erpEdit(null)}
function field(name,label,type,value,opts={}){const f=document.createElement('label');f.textContent=label;const input=document.createElement(type==='textarea'?'textarea':type==='select'?'select':'input');input.name=name;if(type==='select'){for(const item of opts.options||[]){const option=document.createElement('option');option.value=typeof item==='string'?item:item.value;option.textContent=typeof item==='string'?item:item.label;input.append(option)}}else if(type!=='textarea')input.type=type;input.value=value??'';if(type==='checkbox'){input.checked=!!value;input.value='1'}if(type==='number')input.step='any';if(opts.required)input.required=true;if(opts.readonly)input.readOnly=true;if(opts.wide)f.className='wide';f.append(input);$('#editFields').append(f);return input}
function dialog(title,build,save){$('#editTitle').textContent=title;$('#editFields').replaceChildren();$('#editError').textContent='';saveAction=save;$('#saveEditor').hidden=!save;build();dirty=false;$('#editor').showModal()}
function closeEditor(){if(dirty&&!confirm('Descartar alterações não salvas?'))return;dirty=false;$('#editor').close()}
$('#closeEditor').onclick=$('#cancelEditor').onclick=closeEditor;$('#editor').addEventListener('cancel',e=>{e.preventDefault();closeEditor()});$('#editForm').oninput=()=>dirty=true;
$('#editForm').onsubmit=async e=>{e.preventDefault();$('#saveEditor').disabled=true;$('#editError').textContent='';try{await saveAction(new FormData(e.currentTarget));dirty=false;$('#editor').close();render();message('Alterações salvas online.')}catch(err){$('#editError').textContent=err.message}finally{$('#saveEditor').disabled=false}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
function erpEdit(original){const name=page,table=erp.tables[name],row=original?structuredClone(original):defaultRow(name);if(!original){row.Id=nextId(name);if(name==='Produtos'){row.Ativo='Sim';row.Confirmado=true}}dialog((original?'Editar':'Adicionar')+' • '+name,()=>{for(const c of table.columns){if(c.name==='Id')continue;let type=c.type==='date'?'datetime-local':c.type==='bool'?'checkbox':c.type==='number'||c.type==='int'?'number':'text';let value=row[c.name];if(type==='datetime-local')value=value&&!String(value).startsWith('/Date')?localDate(value):localDate(new Date());field(c.name,c.name,type,value,{readonly:name==='Produtos'&&c.name==='Estoque'})}if(name==='Produtos'&&original){const note=document.createElement('div');note.className='wide';note.innerHTML='<p>Estoque é alterado por movimentação, mantendo o histórico.</p><button type="button" id="stock">Movimentar estoque</button>';$('#editFields').append(note);$('#stock').onclick=()=>{if(dirty){$('#editError').textContent='Salve as alterações do produto antes de movimentar estoque.';return}$('#editor').close();stock(original)}}},async fd=>{for(const c of table.columns){if(c.name==='Id'||name==='Produtos'&&c.name==='Estoque')continue;const value=fd.get(c.name);row[c.name]=c.type==='bool'?value!==null:c.type==='date'?new Date(value).toISOString():c.type==='number'||c.type==='int'?Number(value):String(value??'');if((c.type==='number'||c.type==='int')&&(!Number.isFinite(row[c.name])||c.type==='int'&&!Number.isInteger(row[c.name])))throw Error('Valor inválido: '+c.name)}if(name==='Produtos'&&(!row.Nome.trim()||Number(row.Custo)<0||Number(row.Preço)<0))throw Error('Preencha o nome e valores não negativos.');await commit(copy=>{const list=copy.tables[name].rows;if(original)list[list.findIndex(r=>r.Id===original.Id)]=row;else list.push(row)})})}
function stock(product){dialog('Movimentar estoque • '+product.Nome,()=>{field('q','Quantidade (positiva para entrada; negativa para saída)','number',0,{required:true});field('note','Motivo','textarea','',{required:true,wide:true})},async fd=>{const q=Number(fd.get('q'));if(!Number.isInteger(q)||q===0||Number(product.Estoque)+q<0)throw Error('Informe quantidade inteira, diferente de zero, sem deixar estoque negativo.');await commit(copy=>{const p=copy.tables.Produtos.rows.find(r=>r.Id===product.Id);p.Estoque=Number(p.Estoque)+q;const m=defaultRow('Movimentos');Object.assign(m,{Id:nextId('Movimentos'),Data:new Date().toISOString(),Produto:p.Id,Código:p.Código,Nome:p.Nome,Quantidade:q,Tipo:q>0?'Entrada':'Saída',Observações:String(fd.get('note'))});copy.tables.Movimentos.rows.push(m)})})}
function siteProducts(){tableView(['name','price','sale_price','pix_price','card_price','active','featured'],products,siteEdit,'<button id="add" class="primary">Adicionar produto</button>');$('#add').onclick=()=>siteEdit(null)}
function siteEdit(original){let p=original||{active:false,featured:false,term_ids:[]};dialog(original?'Editar produto do site':'Adicionar produto do site',()=>{field('name','Nome','text',p.name,{required:true,wide:true});field('description','Descrição','textarea',p.description,{wide:true});field('image_url','URL da imagem','url',p.image_url,{wide:true});for(const [key,label] of [['price','Preço normal'],['sale_price','Promoção geral'],['pix_price','Preço no Pix'],['card_price','Preço no cartão']])field(key,label,'number',p[key]);for(const [key,label] of [['promotion_start','Início da promoção'],['promotion_end','Fim da promoção']])field(key,label,'datetime-local',p[key]?localDate(p[key]):'');field('active','Publicado','checkbox',p.active);field('featured','Destaque','checkbox',p.featured);for(const [kind,label] of [['tipo','Tipo de vinho'],['uva','Uva'],['pais','País'],['bodega','Bodega'],['colecao','Coleção']]){const fs=document.createElement('fieldset');fs.className='wide';fs.innerHTML='<legend>'+label+'</legend>'+terms.filter(t=>t.kind===kind).map(t=>'<label><input name="term" type="checkbox" value="'+esc(t.id)+'" '+((p.term_ids||[]).includes(t.id)?'checked':'')+'>'+esc(t.name)+(t.parent_id?' (subcategoria)':'')+'</label>').join('');$('#editFields').append(fs)}},async fd=>{const body={name:String(fd.get('name')).trim(),description:String(fd.get('description')),image_url:String(fd.get('image_url')),active:fd.has('active'),featured:fd.has('featured'),term_ids:fd.getAll('term')};for(const key of ['price','sale_price','pix_price','card_price']){body[key]=fd.get(key)===''?null:Number(fd.get(key));if(body[key]!==null&&(!Number.isFinite(body[key])||body[key]<0))throw Error('Preço inválido.')}for(const key of ['promotion_start','promotion_end'])body[key]=fd.get(key)?new Date(fd.get(key)).toISOString():null;if(body.promotion_start&&body.promotion_end&&body.promotion_start>body.promotion_end)throw Error('O fim da promoção deve ser após o início.');for(const key of ['sale_price','pix_price','card_price'])if(body[key]!==null&&(body.price===null||body[key]>body.price))throw Error('Preço promocional deve ser menor ou igual ao preço normal.');await request('/rest/v1/products'+(original?'?id=eq.'+original.id:''),original?'PATCH':'POST',body);products=await all('products')})}
function categories(){tableView(['name','kind','parent_id'],terms,termEdit,'<button id="add" class="primary">Adicionar categoria</button>');$('#add').onclick=()=>termEdit(null)}
function termEdit(term){dialog(term?'Editar categoria':'Adicionar categoria',()=>{field('name','Nome','text',term?.name,{required:true});const kind=field('kind','Grupo','select',term?.kind||'tipo',{options:[{value:'tipo',label:'Tipo de vinho'},{value:'uva',label:'Uva'},{value:'pais',label:'País'},{value:'bodega',label:'Bodega'},{value:'colecao',label:'Coleção'}]});const parent=field('parent_id','Categoria superior','select',term?.parent_id||'',{options:[]});function parents(){const value=parent.value;parent.replaceChildren();for(const item of [{id:'',name:'Nenhuma — categoria principal'},...terms.filter(t=>t.kind===kind.value&&t.id!==term?.id)]){const o=document.createElement('option');o.value=item.id;o.textContent=item.name;parent.append(o)}parent.value=value||term?.parent_id||''}kind.onchange=parents;parents()},async fd=>{await request('/rest/v1/catalog_terms'+(term?'?id=eq.'+term.id:''),term?'PATCH':'POST',{name:String(fd.get('name')).trim(),kind:fd.get('kind'),parent_id:fd.get('parent_id')||null});terms=await all('catalog_terms')})}
const settingLabels={store_name:'Nome da loja',whatsapp:'WhatsApp',tagline:'Slogan',contact_email:'E-mail de contato',instagram_url:'Instagram',address:'Endereço',opening_hours:'Horários',footer_text:'Texto do rodapé',logo_url:'URL da logo',primary_color:'Cor principal',hero_title:'Título da página inicial',hero_text:'Texto da página inicial',hero_image_url:'Imagem principal',hero_link_label:'Texto do botão principal',hero_link_url:'Link do botão principal',featured_title:'Título dos destaques',announcement:'Aviso da loja',meta_description:'Descrição para buscadores',show_prices:'Mostrar preços',card_installments:'Parcelas no cartão',card_min_installment:'Parcela mínima',card_interest_free:'Parcelamento sem juros',payment_note:'Observações de pagamento'};
function settingsPage(){$('#content').innerHTML='<h1>Configurações do site</h1><div class="card"><p>Identidade da loja, página inicial, contatos, pagamentos e informações públicas.</p><button id="settingsEdit" class="primary">Editar configurações</button></div>';$('#settingsEdit').onclick=()=>dialog('Configurações da loja',()=>{for(const [key,label] of Object.entries(settingLabels)){let type=typeof settings[key]==='boolean'?'checkbox':typeof settings[key]==='number'?'number':['hero_text','footer_text','meta_description','payment_note'].includes(key)?'textarea':'text';field(key,label,type,settings[key],{wide:type==='textarea'})}},async fd=>{const body={};for(const key of Object.keys(settingLabels)){const old=settings[key];body[key]=typeof old==='boolean'?fd.has(key):typeof old==='number'?Number(fd.get(key)):String(fd.get(key)??'')}if(body.primary_color&&!/^#[0-9a-f]{6}$/i.test(body.primary_color))throw Error('Cor inválida. Use formato #6a1d3c.');await request('/rest/v1/store_settings?id=eq.true','PATCH',body);settings=(await request('/rest/v1/store_settings?select=*'))[0]})}


function readRow(row,table){dialog('Detalhes • '+page,()=>{for(const c of table.columns){const value=c.type==='date'?new Date(row[c.name]).toLocaleString('pt-BR'):row[c.name];const input=field(c.name,c.name,'textarea',value,{readonly:true,wide:true});input.rows=2}},null)}

