using System;using System.Collections.Generic;using System.Drawing;using System.Globalization;using System.Linq;using System.Threading.Tasks;using System.Windows.Forms;
namespace Videira {public partial class VideiraSite {
 List<CatalogTerm> terms=new List<CatalogTerm>();Dictionary<string,object> storeSettings=new Dictionary<string,object>();TreeView termChecks;TextBox salePrice,pixPrice,cardPrice;DateTimePicker promoStart,promoEnd;
 string[] groupKeys={"tipo","uva","pais","bodega","colecao"};string[] groupLabels={"Tipos de vinho","Uvas","Países","Bodegas / produtores","Coleções"};
 async Task Reload(){products=await api.Products();var rows=(object[])await api.Request("/rest/v1/catalog_terms?select=*&order=name.asc");terms=rows.Cast<Dictionary<string,object>>().Select(r=>new CatalogTerm{Id=SiteApi.Read(r,"id"),Name=SiteApi.Read(r,"name"),Kind=SiteApi.Read(r,"kind"),Parent=SiteApi.Read(r,"parent_id")}).ToList();categories=terms.Where(t=>t.Kind=="tipo"||t.Kind=="colecao").Select(t=>t.Name).Distinct().OrderBy(x=>x).ToList();var settings=(object[])await api.Request("/rest/v1/store_settings?select=*");if(settings.Length>0)storeSettings=(Dictionary<string,object>)settings[0];}
 static string[] Ids(Dictionary<string,object> p){object raw;if(p==null||!p.TryGetValue("term_ids",out raw)||raw==null)return new string[0];var values=raw as System.Collections.IEnumerable;return values==null?new string[0]:values.Cast<object>().Select(Convert.ToString).ToArray();}
 bool CategoryMatch(Dictionary<string,object> p,string name){var targets=terms.Where(t=>t.Name==name).Select(t=>t.Id).ToList();for(int i=0;i<targets.Count;i++)foreach(var child in terms.Where(t=>t.Parent==targets[i]))if(!targets.Contains(child.Id))targets.Add(child.Id);return Ids(p).Any(targets.Contains)||SiteApi.Read(p,"category")==name;}
 TabPage Tab(TabControl tabs,string label){var page=new TabPage(label){BackColor=Color.White,Padding=new Padding(18),AutoScroll=true};tabs.TabPages.Add(page);return page;}
 TableLayoutPanel Fields(TabPage page,int rows){var panel=new TableLayoutPanel{Dock=DockStyle.Top,AutoSize=true,ColumnCount=1,RowCount=rows,Margin=Padding.Empty};panel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));for(int i=0;i<rows;i++)panel.RowStyles.Add(new RowStyle(SizeType.Absolute,82));page.Controls.Add(panel);return panel;}
 void BuildTermNodes(TreeNodeCollection nodes,string kind,string parent,HashSet<string> selected){foreach(var term in terms.Where(t=>t.Kind==kind&&t.Parent==parent).OrderBy(t=>t.Name)){var node=new TreeNode(term.Name){Tag=term,Checked=selected.Contains(term.Id)};nodes.Add(node);BuildTermNodes(node.Nodes,kind,term.Id,selected);}}
 TreeView TermsTree(bool checks,HashSet<string> selected){var tree=new TreeView{Dock=DockStyle.Fill,CheckBoxes=checks,HideSelection=false,BorderStyle=BorderStyle.FixedSingle,ItemHeight=30};for(int i=0;i<groupKeys.Length;i++){var node=new TreeNode(groupLabels[i]);tree.Nodes.Add(node);BuildTermNodes(node.Nodes,groupKeys[i],"",selected);node.ExpandAll();}tree.BeforeCheck+=(s,e)=>{if(e.Node.Tag==null)e.Cancel=true;};return tree;}
 IEnumerable<TreeNode> Nodes(TreeNodeCollection nodes){foreach(TreeNode n in nodes){yield return n;foreach(var child in Nodes(n.Nodes))yield return child;}}
 void Editor(Dictionary<string,object> product){editing=product==null?"":SiteApi.Read(product,"id");Func<string,string> v=k=>product==null?"":SiteApi.Read(product,k);var root=PageRoot(editing==""?"Adicionar produto":"Editar produto");var tools=Buttons();tools.Controls.Add(ActionButton("Voltar aos produtos",()=>{if(Discard()){dirty=false;ProductsPage();}return Task.FromResult(0);}));root.Controls.Add(tools);var layout=new TableLayoutPanel{Height=530,ColumnCount=2,Margin=Padding.Empty};layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,72));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,28));root.Controls.Add(layout);var tabs=new TabControl{Dock=DockStyle.Fill,Font=Font,Padding=new Point(16,9),Margin=new Padding(0,0,16,0)};layout.Controls.Add(tabs,0,0);
 var general=Fields(Tab(tabs,"Geral"),3);title=Field(general,"Nome do produto *",v("name"));general.RowStyles[1].Height=260;description=Field(general,"Descrição do vinho",v("description"),true);general.Controls.Add(Copy("Organização: marque tipos, uvas, países e bodegas na aba Categorias.\nUse a aba Preços para promoções, Pix e cartão.",75));
 var prices=Fields(Tab(tabs,"Preços"),7);price=Field(prices,"Preço normal (R$) — vazio: sob consulta",v("price")==""?"":Amount(product).ToString("0.00",CultureInfo.GetCultureInfo("pt-BR")));salePrice=Field(prices,"Preço promocional geral (R$)",LocalPrice(product,"sale_price"));pixPrice=Field(prices,"Preço no Pix (R$)",LocalPrice(product,"pix_price"));cardPrice=Field(prices,"Preço no cartão (R$)",LocalPrice(product,"card_price"));var dates=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,Margin=Padding.Empty};dates.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));dates.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));prices.Controls.Add(dates);promoStart=PromoDate(dates,"Início da promoção",v("promotion_start"));promoEnd=PromoDate(dates,"Fim da promoção",v("promotion_end"));prices.RowStyles[5].Height=120;prices.Controls.Add(Copy("Desmarque as datas para não limitar o período.\nA promoção geral deve ser menor que o preço normal.\nPix e cartão vazios usam o preço vigente.\nParcelamento: configure em Configurações → Pagamento.",110));
 var org=Tab(tabs,"Categorias");var selected=new HashSet<string>(Ids(product));if(selected.Count==0&&product!=null){foreach(var term in terms)if((term.Kind=="tipo"&&term.Name==v("category"))||(term.Kind=="uva"&&term.Name==v("grape"))||(term.Kind=="pais"&&term.Name==v("country"))||(term.Kind=="bodega"&&term.Name==v("winery")))selected.Add(term.Id);}termChecks=TermsTree(true,selected);org.Controls.Add(termChecks);termChecks.AfterCheck+=(s,e)=>dirty=true;var orgInfo=new Label{Text="Marque várias opções. Subcategorias também aparecem nos filtros da categoria principal.",Dock=DockStyle.Top,Height=50,ForeColor=Color.DimGray};org.Controls.Add(orgInfo);
 var photos=Fields(Tab(tabs,"Imagem"),3);photo=Field(photos,"URL HTTPS da imagem",v("image_url"));photo.MaxLength=2000;var imageActions=Buttons();imageActions.Dock=DockStyle.Fill;imageActions.Controls.Add(ActionButton("Selecionar e enviar foto",async()=>{using(var d=new OpenFileDialog{Filter="Imagens|*.jpg;*.jpeg;*.png;*.webp"}){if(d.ShowDialog(this)==DialogResult.OK){photo.Text=await api.UploadPhoto(d.FileName);Notify("Imagem enviada. Salve o produto para associar a foto.");}}}));imageActions.Controls.Add(ActionButton("Abrir foto",()=>{Uri u;if(!Uri.TryCreate(photo.Text,UriKind.Absolute,out u)||u.Scheme!="https")throw new Exception("Informe uma URL HTTPS válida.");System.Diagnostics.Process.Start(u.AbsoluteUri);return Task.FromResult(0);}));photos.Controls.Add(imageActions);photos.Controls.Add(Copy("JPG, PNG ou WebP até 6 MB. Após o envio, salve o produto."));
 var side=Section("Publicar");side.Margin=Padding.Empty;layout.Controls.Add(side,1,0);var pub=SectionBody(side);pub.RowCount=5;foreach(int height in new[]{55,75,130,55,70})pub.RowStyles.Add(new RowStyle(SizeType.Absolute,height));published=new CheckBox{Text="Publicado\nna loja",Checked=product!=null&&Flag(product,"active"),Dock=DockStyle.Fill};featured=new CheckBox{Text="Destaque na\npágina inicial",Checked=product!=null&&Flag(product,"featured"),Dock=DockStyle.Fill};pub.Controls.Add(published);pub.Controls.Add(featured);pub.Controls.Add(Copy("Rascunho: guardado no painel, sem aparecer na loja.\n\nSalvar atualiza o catálogo online.",125));pub.Controls.Add(ActionButton(editing==""?"Salvar produto":"Atualizar",Save,true));pub.Controls.Add(Copy("Revise as categorias e os preços antes de publicar.",65));published.CheckedChanged+=(s,e)=>dirty=true;featured.CheckedChanged+=(s,e)=>dirty=true;dirty=false;}
 string LocalPrice(Dictionary<string,object> p,string key){string value=p==null?"":SiteApi.Read(p,key);return value==""?"":Decimal.Parse(value,CultureInfo.InvariantCulture).ToString("0.00",CultureInfo.GetCultureInfo("pt-BR"));}
 DateTimePicker PromoDate(TableLayoutPanel panel,string label,string value){var wrapper=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=2,Margin=new Padding(0,0,12,16)};wrapper.RowStyles.Add(new RowStyle(SizeType.Absolute,25));wrapper.Controls.Add(new Label{Text=label,Dock=DockStyle.Fill});var date=new DateTimePicker{Format=DateTimePickerFormat.Custom,CustomFormat="dd/MM/yyyy HH:mm",ShowCheckBox=true,Checked=false,Dock=DockStyle.Top};DateTime parsed;if(DateTime.TryParse(value,null,DateTimeStyles.RoundtripKind,out parsed)){date.Value=parsed.ToLocalTime();date.Checked=true;}date.ValueChanged+=(s,e)=>dirty=true;wrapper.Controls.Add(date);panel.Controls.Add(wrapper);return date;}
 object ReadMoney(TextBox input){if(String.IsNullOrWhiteSpace(input.Text))return null;decimal value;if(!Decimal.TryParse(input.Text.Trim().Replace('.',','),NumberStyles.AllowDecimalPoint,CultureInfo.GetCultureInfo("pt-BR"),out value)||value<0||value>9999999999m)throw new Exception("Informe preços válidos, sem separador de milhar.");return Math.Round(value,2);}
 async Task Save(){if(title.Text.Trim()=="")throw new Exception("Informe o nome do produto.");var selected=Nodes(termChecks.Nodes).Where(n=>n.Checked&&n.Tag is CatalogTerm).Select(n=>(CatalogTerm)n.Tag).ToList();if(!selected.Any(t=>t.Kind=="tipo"))throw new Exception("Marque ao menos um tipo de vinho na aba Categorias.");object normal=ReadMoney(price),sale=ReadMoney(salePrice),pix=ReadMoney(pixPrice),card=ReadMoney(cardPrice);if(normal==null&&(sale!=null||pix!=null||card!=null))throw new Exception("Informe o preço normal antes dos preços especiais.");if(sale!=null&&Convert.ToDecimal(sale)>=Convert.ToDecimal(normal))throw new Exception("A promoção geral deve ser menor que o preço normal.");if(pix!=null&&Convert.ToDecimal(pix)>Convert.ToDecimal(normal))throw new Exception("O preço no Pix não pode superar o preço normal.");if(promoStart.Checked&&promoEnd.Checked&&promoEnd.Value<promoStart.Value)throw new Exception("O fim da promoção deve ser depois do início.");ValidateHttps(photo.Text,"foto");var data=new Dictionary<string,object>{{"name",title.Text.Trim()},{"description",description.Text.Trim()},{"image_url",photo.Text.Trim()},{"term_ids",selected.Select(t=>t.Id).ToArray()},{"price",normal},{"sale_price",sale},{"pix_price",pix},{"card_price",card},{"promotion_start",promoStart.Checked?(object)promoStart.Value.ToUniversalTime().ToString("o"):null},{"promotion_end",promoEnd.Checked?(object)promoEnd.Value.ToUniversalTime().ToString("o"):null},{"active",published.Checked},{"featured",featured.Checked}};await api.Save(data,editing);dirty=false;await Reload();ProductsPage();Notify("Produto e preços salvos no site.");}
 void ValidateHttps(string text,string label){Uri u;if(text.Trim()!=""&&(!Uri.TryCreate(text.Trim(),UriKind.Absolute,out u)||u.Scheme!="https"))throw new Exception("Informe uma URL HTTPS válida para "+label+".");}
 void CategoriesPage(){var root=PageRoot("Categorias e atributos");var actions=Buttons();actions.Controls.Add(ActionButton("Adicionar categoria",()=>{TermDialog(null);return Task.FromResult(0);},true));actions.Controls.Add(ActionButton("Atualizar",async()=>{await Reload();CategoriesPage();}));root.Controls.Add(actions);var tree=TermsTree(false,new HashSet<string>());tree.Height=460;tree.Dock=DockStyle.None;root.Controls.Add(tree);var edit=Buttons();edit.Controls.Add(ActionButton("Editar selecionada",()=>{if(tree.SelectedNode==null||!(tree.SelectedNode.Tag is CatalogTerm))throw new Exception("Selecione uma categoria ou atributo.");TermDialog((CatalogTerm)tree.SelectedNode.Tag);return Task.FromResult(0);}));root.Controls.Add(edit);root.Controls.Add(new Label{Text="Organize cada grupo em categorias e subcategorias. Um produto pode ter várias opções em cada grupo.",AutoSize=true,ForeColor=Color.DimGray});dirty=false;}
 void TermDialog(CatalogTerm term){using(var d=new Form{Text=term==null?"Adicionar categoria ou atributo":"Editar categoria ou atributo",Width=560,Height=370,StartPosition=FormStartPosition.CenterParent,Font=Font,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false}){var name=new TextBox{Text=term==null?"":term.Name,Location=new Point(20,50),Width=500,MaxLength=100};d.Controls.Add(new Label{Text="Nome",Location=new Point(20,24),AutoSize=true});d.Controls.Add(name);var kind=new AdminComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Location=new Point(20,115),Width=500,Enabled=term==null};kind.Items.AddRange(groupLabels.Cast<object>().ToArray());kind.SelectedIndex=term==null?0:Array.IndexOf(groupKeys,term.Kind);d.Controls.Add(new Label{Text="Grupo",Location=new Point(20,90),AutoSize=true});d.Controls.Add(kind);var parent=new AdminComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Location=new Point(20,185),Width=500};d.Controls.Add(new Label{Text="Categoria principal (opcional)",Location=new Point(20,158),AutoSize=true});d.Controls.Add(parent);Action parents=()=>{parent.Items.Clear();parent.Items.Add(new TermOption{Id="",Label="Nenhuma — categoria principal"});foreach(var t in terms.Where(t=>t.Kind==groupKeys[kind.SelectedIndex]&&(term==null||t.Id!=term.Id)))parent.Items.Add(new TermOption{Id=t.Id,Label=t.Name});parent.SelectedIndex=0;if(term!=null)for(int i=0;i<parent.Items.Count;i++)if(((TermOption)parent.Items[i]).Id==term.Parent)parent.SelectedIndex=i;};parents();kind.SelectedIndexChanged+=(s,e)=>parents();var message=new Label{Location=new Point(20,285),Size=new Size(500,50),ForeColor=Color.Firebrick};d.Controls.Add(message);var save=new Button{Text="Salvar",Location=new Point(20,235),Width=120,Height=34,BackColor=blue,ForeColor=Color.White};d.Controls.Add(save);save.Click+=async(s,e)=>{save.Enabled=false;try{if(name.Text.Trim()=="")throw new Exception("Informe o nome.");if(terms.Any(t=>t.Kind==groupKeys[kind.SelectedIndex]&&String.Equals(t.Name,name.Text.Trim(),StringComparison.OrdinalIgnoreCase)&&(term==null||t.Id!=term.Id)))throw new Exception("Já existe uma opção com esse nome no grupo.");string pid=((TermOption)parent.SelectedItem).Id;var data=new{name=name.Text.Trim(),kind=groupKeys[kind.SelectedIndex],parent_id=pid==""?null:pid};var rows=(object[])await api.Request("/rest/v1/catalog_terms"+(term==null?"":"?id=eq."+Uri.EscapeDataString(term.Id)),term==null?"POST":"PATCH",data);if(rows==null||rows.Length!=1)throw new Exception("O site não confirmou a categoria.");await Reload();CategoriesPage();Notify("Categoria e hierarquia salvas no site.");d.Close();}catch(Exception ex){message.Text=ex.Message;}finally{save.Enabled=true;}};d.ShowDialog(this);}}
}
public class CatalogTerm{public string Id,Kind,Name,Parent;}
public class TermOption{public string Id,Label;public override string ToString(){return Label;}}
}

