using System;using System.Net;using System.Net.Http;using System.Threading;using System.Threading.Tasks;using System.Collections.Generic;using System.IO;using Videira;
class CatalogServer:HttpMessageHandler{
 public bool Wrong;public int Patches;public string Path,Payload;
 protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage r,CancellationToken c){string value;if(r.RequestUri.AbsolutePath.EndsWith("/token"))value="{\"access_token\":\"fixture\",\"refresh_token\":\"fixture\",\"expires_in\":3600}";else if(r.RequestUri.AbsolutePath.EndsWith("/user"))value="{\"app_metadata\":{\"role\":\"admin\"}}";else{Patches++;Path=r.RequestUri.PathAndQuery;Payload=await r.Content.ReadAsStringAsync();value=Wrong?"[]":"[{\"id\":\"11111111-1111-1111-1111-111111111111\"},{\"id\":\"22222222-2222-2222-2222-222222222222\"}]";}return new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(value)};
 }
}
class CatalogCheck{
 static void Assert(bool ok,string message){if(!ok)throw new Exception(message);}
 static void Main(){var fake=new CatalogServer();using(var api=new SiteApi(fake)){api.Login("fixture@example.com","fixture").GetAwaiter().GetResult();string[] ids={"11111111-1111-1111-1111-111111111111","22222222-2222-2222-2222-222222222222"};api.UpdateProducts(ids,new Dictionary<string,object>{{"active",true}}).GetAwaiter().GetResult();Assert(fake.Patches==1&&fake.Path.Contains("id=in.")&&fake.Payload=="{\"active\":true}","Ação em lote inválida");fake.Wrong=true;bool blocked=false;try{api.UpdateProducts(ids,new Dictionary<string,object>{{"featured",true}}).GetAwaiter().GetResult();}catch(Exception ex){blocked=ex.Message.Contains("não confirmou todos");}Assert(blocked,"Resposta parcial não detectada");int calls=fake.Patches;try{api.UpdateProducts(new[]{"invalido"},new Dictionary<string,object>{{"active",true}}).GetAwaiter().GetResult();}catch{}Assert(calls==fake.Patches,"ID inválido transmitido");}
 var csv=VideiraSite.CatalogCsv(new List<Dictionary<string,object>>{new Dictionary<string,object>{{"name","=FORMULA;\"vinho\""},{"category","Tinto"},{"description","Linha 1\nLinha 2"},{"price",99.9m},{"active",false},{"featured",true}}});Assert(csv.Contains("\"'=FORMULA;\"\"vinho\"\"\"")&&csv.Contains("99,90")&&csv.Contains("Linha 1\nLinha 2"),"CSV não protege fórmula ou preserva valores");File.WriteAllText("work/site-app/catalog-check.txt","PASS: PATCH em lote usa somente IDs selecionados; retorno parcial e IDs inválidos são rejeitados; CSV preserva texto, moeda e bloqueia fórmulas. Nenhuma gravação real foi feita.");
 }
}
