using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace Videira {
public partial class VideiraSite {
 FlowLayoutPanel currentRoot;bool fitting;
 void FitPage(){if(fitting||currentRoot==null||currentRoot.IsDisposed)return;fitting=true;try{int w=Math.Max(650,body.ClientSize.Width-body.Padding.Horizontal-22);currentRoot.MinimumSize=new Size(w,0);currentRoot.MaximumSize=new Size(w,0);currentRoot.Width=w;foreach(Control c in currentRoot.Controls){if(c is Label){c.MaximumSize=new Size(w,0);}else c.Width=w;}currentRoot.PerformLayout();}finally{fitting=false;}}
 FlowLayoutPanel PageRoot(string heading){body.SuspendLayout();foreach(Control c in body.Controls.Cast<Control>().ToArray()){body.Controls.Remove(c);c.Dispose();}body.AutoScrollPosition=Point.Empty;currentRoot=new FlowLayoutPanel{AutoSize=true,AutoSizeMode=AutoSizeMode.GrowAndShrink,FlowDirection=FlowDirection.TopDown,WrapContents=false,Margin=Padding.Empty,Padding=Padding.Empty,Location=new Point(body.Padding.Left,body.Padding.Top)};body.Controls.Add(currentRoot);currentRoot.Controls.Add(new Label{Text=heading,Font=new Font("Segoe UI",24),ForeColor=Color.FromArgb(29,35,39),AutoSize=true,Margin=new Padding(0,0,0,8)});string subtitle=heading=="Painel"?"Seu catálogo em um só lugar. Organize os produtos e publique na loja.":heading=="Produtos"?"Pesquise, filtre e atualize seu catálogo. Selecione várias linhas para ações em lote.":heading.Contains("produto")?"Edite os dados e escolha quando o produto aparece na loja.":"Administração do catálogo Videira Vinhoteca";currentRoot.Controls.Add(new Label{Text=subtitle,AutoSize=true,ForeColor=Color.DimGray,Margin=new Padding(0,0,0,24)});currentRoot.ControlAdded+=(s,e)=>FitPage();FitPage();body.ResumeLayout();return currentRoot;}
 FlowLayoutPanel Buttons(){return new FlowLayoutPanel{AutoSize=true,AutoSizeMode=AutoSizeMode.GrowAndShrink,WrapContents=true,Margin=new Padding(0,0,0,16),Padding=Padding.Empty};}
 Label Copy(string text,int height=60){return new Label{Text=text,Dock=DockStyle.Fill,AutoSize=false,Height=height,ForeColor=Color.FromArgb(70,75,80),Margin=new Padding(0,6,0,12)};}
 Control FilterField(Control field,string label){var box=new Panel{Width=field.Width+6,Height=64,Margin=new Padding(0,0,10,8)};box.Controls.Add(new Label{Text=label,AutoSize=true,Location=new Point(0,0),ForeColor=Color.DimGray});field.Location=new Point(0,25);field.Margin=Padding.Empty;box.Controls.Add(field);return box;}
 Panel Section(string heading){var panel=new Panel{BackColor=Color.White,BorderStyle=BorderStyle.FixedSingle,Dock=DockStyle.Fill,Margin=new Padding(0,0,16,16),Padding=new Padding(20)};var caption=new Label{Text=heading,Font=new Font("Segoe UI",12,FontStyle.Bold),Dock=DockStyle.Top,Height=34};panel.Controls.Add(caption);return panel;}
 TableLayoutPanel SectionBody(Panel section){var t=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,AutoScroll=false,Padding=Padding.Empty};t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));section.Controls.Add(t);t.BringToFront();return t;}
 void Dashboard(){var root=PageRoot("Painel");var actions=Buttons();actions.Controls.Add(ActionButton("Adicionar produto",()=>{Editor(null);return Task.FromResult(0);},true));actions.Controls.Add(ActionButton("Gerenciar catálogo",()=>{ProductsPage();return Task.FromResult(0);}));actions.Controls.Add(ActionButton("Sincronizar",async()=>{await Reload();Dashboard();Notify("Catálogo sincronizado às "+DateTime.Now.ToString("HH:mm")+".");}));root.Controls.Add(actions);
 var metrics=new TableLayoutPanel{Height=115,ColumnCount=4,Margin=new Padding(0,0,0,20)};for(int i=0;i<4;i++)metrics.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,25));root.Controls.Add(metrics);int[] counts={products.Count,products.Count(p=>Flag(p,"active")),products.Count(p=>!Flag(p,"active")),categories.Count};string[] labels={"Produtos","Publicados","Rascunhos","Categorias"};for(int i=0;i<4;i++){var tile=new Panel{Dock=DockStyle.Fill,BackColor=Color.White,BorderStyle=BorderStyle.FixedSingle,Margin=new Padding(0,0,i==3?0:12,0),Padding=new Padding(16)};tile.Controls.Add(new Label{Text=labels[i],Dock=DockStyle.Bottom,Height=24,ForeColor=Color.DimGray});tile.Controls.Add(new Label{Text=counts[i].ToString(),Dock=DockStyle.Top,Height=45,Font=new Font("Segoe UI",25),ForeColor=blue});metrics.Controls.Add(tile,i,0);}
 var columns=new TableLayoutPanel{Height=350,ColumnCount=2,Margin=Padding.Empty};columns.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,60));columns.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,40));root.Controls.Add(columns);var recent=Section("Últimos produtos cadastrados");columns.Controls.Add(recent,0,0);var content=SectionBody(recent);content.RowStyles.Add(new RowStyle(SizeType.Percent,100));var grid=Grid();grid.Dock=DockStyle.Fill;grid.DataSource=products.Take(6).Select(p=>new RecentRow{Produto=SiteApi.Read(p,"name"),Situação=Flag(p,"active")?"Publicado":"Rascunho"}).ToList();content.Controls.Add(grid);grid.CellDoubleClick+=(s,e)=>{if(e.RowIndex>=0)Editor(products[e.RowIndex]);};if(products.Count==0){grid.Visible=false;content.Controls.Add(Copy("Seu catálogo ainda está vazio.\nUse Adicionar produto para cadastrar o primeiro vinho."));}
 var health=Section("Revisão do catálogo");health.Margin=new Padding(0,0,0,16);columns.Controls.Add(health,1,0);var checks=SectionBody(health);checks.RowStyles.Add(new RowStyle(SizeType.Percent,100));checks.Controls.Add(Copy(products.Count(p=>SiteApi.Read(p,"image_url")=="")+" produtos sem foto\n\n"+products.Count(p=>SiteApi.Read(p,"description")=="")+" produtos sem descrição\n\n"+products.Count(p=>Flag(p,"featured"))+" destaques na página inicial\n\n"+products.Count(p=>SiteApi.Read(p,"price")=="")+" preços sob consulta\n\nConfira esses dados antes de publicar."));
 var draft=Card("Rascunho rápido",210);root.Controls.Add(draft);var quick=Input(draft,"Nome do produto",20,55,360);quick.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;quick.Width=draft.Width-40;var save=ActionButton("Criar e continuar editando",()=>{if(quick.Text.Trim()=="")throw new Exception("Informe o nome do produto.");string value=quick.Text.Trim();Editor(null);title.Text=value;return Task.FromResult(0);},true);save.Location=new Point(20,130);draft.Controls.Add(save);dirty=false;}
 static bool Flag(Dictionary<string,object> p,string key){object v;return p.TryGetValue(key,out v)&&v!=null&&Convert.ToBoolean(v);}
 static decimal Amount(Dictionary<string,object> p){object v;return p.TryGetValue("price",out v)&&v!=null?Convert.ToDecimal(v):0m;}
 void ProductsPage(){page="Produtos";var root=PageRoot("Produtos");var tools=Buttons();tools.Controls.Add(ActionButton("Adicionar novo",()=>{Editor(null);return Task.FromResult(0);},true));tools.Controls.Add(ActionButton("Atualizar lista",async()=>{await Reload();ProductsPage();Notify("Catálogo atualizado do site.");}));root.Controls.Add(tools);
 var filters=Buttons();var search=new TextBox{Width=220,Margin=new Padding(0,4,12,10),AccessibleName="Pesquisar produto"};var status=new AdminComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=130,Margin=new Padding(0,4,12,10),AccessibleName="Situação"};status.Items.AddRange(new object[]{"Todos os status","Publicados","Rascunhos","Destaques","Sem foto"});status.SelectedIndex=0;var cat=new AdminComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=165,Margin=new Padding(0,4,12,10),AccessibleName="Categoria"};cat.Items.Add("Todas as categorias");cat.Items.AddRange(categories.Cast<object>().ToArray());cat.SelectedIndex=0;var order=new AdminComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=160,Margin=new Padding(0,4,12,10),AccessibleName="Ordenação"};order.Items.AddRange(new object[]{"Mais recentes","Nome A–Z","Menor preço","Maior preço"});order.SelectedIndex=0;filters.Controls.AddRange(new Control[]{FilterField(search,"Pesquisar produto"),FilterField(status,"Situação"),FilterField(cat,"Categoria"),FilterField(order,"Ordenar por")});root.Controls.Add(filters);
 var total=new Label{AutoSize=true,ForeColor=Color.DimGray,Margin=new Padding(0,0,0,10)};root.Controls.Add(total);var grid=Grid();grid.Height=360;root.Controls.Add(grid);List<Dictionary<string,object>> visible=new List<Dictionary<string,object>>();Action render=()=>{IEnumerable<Dictionary<string,object>> query=products.Where(p=>String.Join(" ",new[]{SiteApi.Read(p,"name"),SiteApi.Read(p,"category"),SiteApi.Read(p,"country"),SiteApi.Read(p,"grape"),SiteApi.Read(p,"winery")}).IndexOf(search.Text,StringComparison.CurrentCultureIgnoreCase)>=0).Where(p=>cat.SelectedIndex==0||SiteApi.Read(p,"category")==cat.Text).Where(p=>status.SelectedIndex==0||status.SelectedIndex==1&&Flag(p,"active")||status.SelectedIndex==2&&!Flag(p,"active")||status.SelectedIndex==3&&Flag(p,"featured")||status.SelectedIndex==4&&SiteApi.Read(p,"image_url")=="");if(order.SelectedIndex==1)query=query.OrderBy(p=>SiteApi.Read(p,"name"));if(order.SelectedIndex==2)query=query.OrderBy(Amount);if(order.SelectedIndex==3)query=query.OrderByDescending(Amount);visible=query.ToList();grid.DataSource=visible.Select(p=>new CatalogRow{Id=SiteApi.Read(p,"id"),Produto=SiteApi.Read(p,"name"),Categoria=SiteApi.Read(p,"category"),Preço=SiteApi.Read(p,"price")==""?"Sob consulta":"R$ "+Amount(p).ToString("N2"),Situação=Flag(p,"active")?"Publicado":"Rascunho",Destaque=Flag(p,"featured")?"Sim":"—"}).ToList();if(grid.Columns.Contains("Id")){grid.Columns["Id"].Visible=false;grid.Columns["Produto"].FillWeight=230;}total.Text=visible.Count+" de "+products.Count+" produtos • Ctrl ou Shift para selecionar várias linhas";};render();search.TextChanged+=(s,e)=>render();status.SelectedIndexChanged+=(s,e)=>render();cat.SelectedIndexChanged+=(s,e)=>render();order.SelectedIndexChanged+=(s,e)=>render();
 Func<Dictionary<string,object>> selected=()=>{if(grid.CurrentRow==null)throw new Exception("Selecione um produto.");string id=((CatalogRow)grid.CurrentRow.DataBoundItem).Id;return products.First(p=>SiteApi.Read(p,"id")==id);};grid.CellDoubleClick+=(s,e)=>{if(e.RowIndex>=0)Editor(selected());};var actions=Buttons();actions.Controls.Add(ActionButton("Editar",()=>{Editor(selected());return Task.FromResult(0);}));actions.Controls.Add(ActionButton("Duplicar",()=>{var copy=new Dictionary<string,object>(selected());copy["id"]="";copy["name"]=SiteApi.Read(copy,"name")+" (cópia)";copy["active"]=false;copy["featured"]=false;Editor(copy);dirty=true;Notify("Cópia preparada como rascunho. Salve para criar o novo produto.");return Task.FromResult(0);}));var operation=new AdminComboBox{Width=175,DropDownStyle=ComboBoxStyle.DropDownList,Margin=new Padding(8,3,8,8)};operation.Items.AddRange(new object[]{"Publicar selecionados","Mover para rascunho","Marcar destaque","Remover destaque"});operation.SelectedIndex=0;actions.Controls.Add(operation);actions.Controls.Add(ActionButton("Aplicar",async()=>{var ids=grid.SelectedRows.Cast<DataGridViewRow>().Select(r=>((CatalogRow)r.DataBoundItem).Id).ToArray();if(ids.Length==0)throw new Exception("Selecione ao menos um produto.");if(MessageBox.Show(this,"Aplicar ‘"+operation.Text+"’ a "+ids.Length+" produtos no site?","Ação em lote",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;var update=new Dictionary<string,object>();update[operation.SelectedIndex<2?"active":"featured"]=operation.SelectedIndex==0||operation.SelectedIndex==2;await api.UpdateProducts(ids,update);await Reload();ProductsPage();Notify(ids.Length+" produtos atualizados no site.");}));actions.Controls.Add(ActionButton("Exportar CSV",()=>{Export(visible);return Task.FromResult(0);}));root.Controls.Add(actions);dirty=false;}
 void Export(List<Dictionary<string,object>> rows){using(var dialog=new SaveFileDialog{Filter="Catálogo CSV|*.csv",FileName="Videira-Catalogo-"+DateTime.Now.ToString("yyyy-MM-dd")+".csv"}){if(dialog.ShowDialog(this)!=DialogResult.OK)return;File.WriteAllText(dialog.FileName,CatalogCsv(rows),new UTF8Encoding(true));Notify(rows.Count+" produtos exportados. A exportação usa os filtros da lista.");}}
 public static string CatalogCsv(List<Dictionary<string,object>> rows){var csv=new StringBuilder("Nome;Categoria;Preço;País;Uva;Produtor;Descrição;Imagem;Publicado;Destaque\r\n");foreach(var p in rows){var values=new[]{SiteApi.Read(p,"name"),SiteApi.Read(p,"category"),SiteApi.Read(p,"price")==""?"":Amount(p).ToString("0.00",CultureInfo.GetCultureInfo("pt-BR")),SiteApi.Read(p,"country"),SiteApi.Read(p,"grape"),SiteApi.Read(p,"winery"),SiteApi.Read(p,"description"),SiteApi.Read(p,"image_url"),Flag(p,"active")?"Sim":"Não",Flag(p,"featured")?"Sim":"Não"};csv.AppendLine(String.Join(";",values.Select(v=>"\""+((v.Length>0&&"=+-@".Contains(v.TrimStart().FirstOrDefault()))?"'":"")+v.Replace("\"","\"\"")+"\"")));}return csv.ToString();}
 TextBox Field(TableLayoutPanel parent,string label,string value="",bool multiline=false){var wrap=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2,Margin=new Padding(0,0,12,16)};wrap.RowStyles.Add(new RowStyle(SizeType.Absolute,25));wrap.RowStyles.Add(new RowStyle(SizeType.Percent,100));wrap.Controls.Add(new Label{Text=label,AutoSize=true,Dock=DockStyle.Fill},0,0);var input=new TextBox{Text=value,Dock=DockStyle.Fill,Multiline=multiline,MaxLength=multiline?5000:200,ScrollBars=multiline?ScrollBars.Vertical:ScrollBars.None};wrap.Controls.Add(input,0,1);input.TextChanged+=(s,e)=>dirty=true;parent.Controls.Add(wrap);return input;}
 void Editor(Dictionary<string,object> product){editing=product==null?"":SiteApi.Read(product,"id");Func<string,string> v=k=>product==null?"":SiteApi.Read(product,k);var root=PageRoot(editing==""?"Adicionar produto":"Editar produto");var tools=Buttons();tools.Controls.Add(ActionButton("Voltar aos produtos",()=>{if(Discard()){dirty=false;ProductsPage();}return Task.FromResult(0);}));root.Controls.Add(tools);var layout=new TableLayoutPanel{Height=690,ColumnCount=2,RowCount=1,Margin=Padding.Empty};layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,65));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,35));root.Controls.Add(layout);
 var main=Section("Dados do produto");layout.Controls.Add(main,0,0);var fields=SectionBody(main);fields.RowCount=7;fields.RowStyles.Add(new RowStyle(SizeType.Absolute,76));fields.RowStyles.Add(new RowStyle(SizeType.Absolute,76));fields.RowStyles.Add(new RowStyle(SizeType.Absolute,76));fields.RowStyles.Add(new RowStyle(SizeType.Absolute,76));fields.RowStyles.Add(new RowStyle(SizeType.Absolute,170));fields.RowStyles.Add(new RowStyle(SizeType.Absolute,50));title=Field(fields,"Nome do produto *",v("name"));var pair=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,Margin=Padding.Empty};pair.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));pair.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));fields.Controls.Add(pair);price=Field(pair,"Preço (R$)",v("price")==""?"":Amount(product).ToString("0.00",CultureInfo.GetCultureInfo("pt-BR")));var cwrap=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=2,Margin=new Padding(0,0,0,16)};cwrap.RowStyles.Add(new RowStyle(SizeType.Absolute,25));cwrap.Controls.Add(new Label{Text="Categoria *",Dock=DockStyle.Fill});category=new AdminComboBox{Dock=DockStyle.Top,DropDownStyle=ComboBoxStyle.DropDown};category.Items.AddRange(categories.Cast<object>().ToArray());category.Text=v("category");category.TextChanged+=(s,e)=>dirty=true;cwrap.Controls.Add(category);pair.Controls.Add(cwrap);
 var origin=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,Margin=Padding.Empty};origin.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));origin.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));fields.Controls.Add(origin);country=Field(origin,"País",v("country"));grape=Field(origin,"Uva",v("grape"));winery=Field(fields,"Bodega / produtor",v("winery"));description=Field(fields,"Descrição",v("description"),true);fields.Controls.Add(Copy("Preço vazio aparece como ‘Sob consulta’.\nVocê pode digitar uma categoria nova.",50));
 var right=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=2,ColumnCount=1,Margin=Padding.Empty};right.RowStyles.Add(new RowStyle(SizeType.Absolute,290));right.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.Controls.Add(right,1,0);var publication=Section("Publicação");publication.Margin=new Padding(0,0,0,16);right.Controls.Add(publication);var pub=SectionBody(publication);pub.RowCount=5;pub.RowStyles.Add(new RowStyle(SizeType.Absolute,35));pub.RowStyles.Add(new RowStyle(SizeType.Absolute,55));pub.RowStyles.Add(new RowStyle(SizeType.Absolute,65));pub.RowStyles.Add(new RowStyle(SizeType.Absolute,45));published=new CheckBox{Text="Publicado na loja",Dock=DockStyle.Fill,Checked=product!=null&&Flag(product,"active")};featured=new CheckBox{Text="Destaque na\npágina inicial",Dock=DockStyle.Fill,Checked=product!=null&&Flag(product,"featured")};pub.Controls.Add(published);pub.Controls.Add(featured);pub.Controls.Add(Copy("Rascunhos ficam guardados\ne não aparecem na vitrine.",65));var save=ActionButton(editing==""?"Salvar produto":"Atualizar produto",Save,true);save.Dock=DockStyle.Fill;pub.Controls.Add(save);published.CheckedChanged+=(s,e)=>dirty=true;featured.CheckedChanged+=(s,e)=>dirty=true;
 var media=Section("Imagem do produto");media.Margin=new Padding(0,0,0,16);right.Controls.Add(media);var photos=SectionBody(media);photos.RowCount=5;photos.RowStyles.Add(new RowStyle(SizeType.Absolute,85));photos.RowStyles.Add(new RowStyle(SizeType.Absolute,60));photos.RowStyles.Add(new RowStyle(SizeType.Absolute,100));photo=Field(photos,"URL HTTPS da foto",v("image_url"));photo.MaxLength=2000;var upload=ActionButton("Enviar imagem",async()=>{using(var d=new OpenFileDialog{Filter="Fotos|*.jpg;*.jpeg;*.png;*.webp"}){if(d.ShowDialog(this)!=DialogResult.OK)return;photo.Text=await api.UploadPhoto(d.FileName);Notify("Foto enviada. Salve o produto para associá-la ao catálogo.");}});upload.Dock=DockStyle.Fill;photos.Controls.Add(upload);photos.Controls.Add(Copy("JPG, PNG ou WebP até 6 MB.\n\nSalve o produto após enviar a foto.\nA URL atual pode ser aberta abaixo.",100));var open=ActionButton("Abrir foto",()=>{Uri uri;if(!Uri.TryCreate(photo.Text,UriKind.Absolute,out uri)||uri.Scheme!="https")throw new Exception("Informe uma URL HTTPS válida.");System.Diagnostics.Process.Start(uri.AbsoluteUri);return Task.FromResult(0);});open.Dock=DockStyle.Fill;photos.Controls.Add(open);dirty=false;}
}
public class RecentRow{public string Produto{get;set;}public string Situação{get;set;}}
public class CatalogRow{public string Id{get;set;}public string Produto{get;set;}public string Categoria{get;set;}public string Preço{get;set;}public string Situação{get;set;}public string Destaque{get;set;}}
}
