using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace Videira {
public partial class VideiraSite : Form {
 readonly SiteApi api=new SiteApi(); readonly Color dark=Color.FromArgb(35,40,45), blue=Color.FromArgb(0,115,170), line=Color.FromArgb(195,196,199); Panel body,sidebar;Label notice,account; Dictionary<string,Button> nav=new Dictionary<string,Button>();List<Dictionary<string,object>> products=new List<Dictionary<string,object>>();List<string> categories=new List<string>();bool busy,dirty;string page="Painel",editing="";TextBox title,price,photo,description;CheckBox published,featured;bool preview;
 public VideiraSite(bool demo=false){preview=demo;Text="Videira Site 3.0 — Administração";Size=new Size(1366,900);MinimumSize=new Size(1024,720);StartPosition=FormStartPosition.CenterScreen;Font=new Font("Segoe UI",9.5f);AutoScaleMode=AutoScaleMode.Dpi;DoubleBuffered=true;BackColor=Color.FromArgb(240,240,241);Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);Build();ShowPage("Painel");FormClosing+=(s,e)=>{if(busy||!Discard())e.Cancel=true;};FormClosed+=(s,e)=>api.Dispose();}
 Button ActionButton(string text,Func<Task> action,bool primary=false){var b=new Button{Text=text,AutoSize=true,Height=34,MinimumSize=new Size(90,34),FlatStyle=FlatStyle.Flat,BackColor=primary?blue:Color.White,ForeColor=primary?Color.White:blue,Padding=new Padding(10,3,10,3),Margin=new Padding(0,0,8,8)};b.FlatAppearance.BorderColor=primary?blue:line;b.Click+=async(s,e)=>await Run(action);return b;}
 async Task Run(Func<Task> action){if(busy)return;busy=true;UseWaitCursor=true;body.Enabled=false;sidebar.Enabled=false;try{await action();}catch(Exception ex){Notify(ex is HttpRequestException?"Não foi possível conectar. Confira a internet. O salvamento não foi confirmado.":ex.Message,true);}finally{body.Enabled=true;sidebar.Enabled=true;UseWaitCursor=false;busy=false;}}
 void Notify(string message,bool error=false){notice.Text=message;notice.ForeColor=error?Color.Firebrick:Color.FromArgb(44,51,56);notice.BackColor=error?Color.FromArgb(252,231,231):Color.White;}
 bool Discard(){return !dirty||MessageBox.Show(this,"Descartar as alterações que ainda não foram salvas?","Videira Site",MessageBoxButtons.YesNo,MessageBoxIcon.Question)==DialogResult.Yes;}
 void Build(){var shell=new TableLayoutPanel{Dock=DockStyle.Fill,Margin=Padding.Empty,Padding=Padding.Empty,ColumnCount=2,RowCount=2};shell.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,190));shell.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));shell.RowStyles.Add(new RowStyle(SizeType.Absolute,36));shell.RowStyles.Add(new RowStyle(SizeType.Percent,100));Controls.Add(shell);var top=new Panel{Dock=DockStyle.Fill,BackColor=dark,Margin=Padding.Empty};shell.Controls.Add(top,0,0);shell.SetColumnSpan(top,2);var brand=new Label{Text="◈  Videira Site   |   Administração",ForeColor=Color.White,Dock=DockStyle.Left,Width=330,TextAlign=ContentAlignment.MiddleLeft,Padding=new Padding(15,0,0,0)};top.Controls.Add(brand);account=new Label{Text="Conta do administrador",ForeColor=Color.White,Dock=DockStyle.Right,Width=340,TextAlign=ContentAlignment.MiddleRight,Padding=new Padding(0,0,18,0)};top.Controls.Add(account);
 sidebar=new Panel{Dock=DockStyle.Fill,BackColor=dark,Margin=Padding.Empty};shell.Controls.Add(sidebar,0,1);var menu=new FlowLayoutPanel{Dock=DockStyle.Top,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoSize=true,Padding=new Padding(0,12,0,0)};sidebar.Controls.Add(menu);foreach(var item in new[]{new[]{"Painel","▣"},new[]{"Produtos","▤"},new[]{"Adicionar produto","＋"},new[]{"Categorias","≡"},new[]{"Mídia","▧"},new[]{"Configurações","⚙"}}){string name=item[0];var button=new Button{Text=item[1]+"   "+name,Width=190,Height=44,TextAlign=ContentAlignment.MiddleLeft,FlatStyle=FlatStyle.Flat,ForeColor=Color.White,BackColor=dark,Padding=new Padding(12,0,0,0),Margin=Padding.Empty};button.FlatAppearance.BorderSize=0;button.Click+=(s,e)=>{if(!busy&&Discard()){dirty=false;ShowPage(name);}};menu.Controls.Add(button);nav[name]=button;}var visit=new LinkLabel{Text="Ver site ↗",ForeColor=Color.LightGray,LinkColor=Color.LightGray,VisitedLinkColor=Color.LightGray,AutoSize=true,Margin=new Padding(18,26,0,0)};visit.LinkClicked+=(s,e)=>System.Diagnostics.Process.Start("https://videira-loja.vercel.app/");menu.Controls.Add(visit);var logout=new LinkLabel{Text="Sair da conta",LinkColor=Color.LightGray,AutoSize=true,Margin=new Padding(18,20,0,0)};logout.LinkClicked+=async(s,e)=>await Run(async()=>{if(!Discard())return;await api.Logout();products.Clear();categories.Clear();dirty=false;account.Text="Conta do administrador";ShowPage("Painel");});menu.Controls.Add(logout);
 var main=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=2,ColumnCount=1,Margin=Padding.Empty};main.RowStyles.Add(new RowStyle(SizeType.Percent,100));main.RowStyles.Add(new RowStyle(SizeType.Absolute,58));shell.Controls.Add(main,1,1);body=new Panel{Dock=DockStyle.Fill,AutoScroll=true,Padding=new Padding(28,24,28,24),Margin=Padding.Empty};body.Resize+=(s,e)=>FitPage();main.Controls.Add(body,0,0);notice=new Label{Text="Videira Site • Catálogo conectado à loja online",Dock=DockStyle.Fill,Padding=new Padding(20,12,20,0),BackColor=Color.White};main.Controls.Add(notice,0,1);}
 Panel Card(string heading,int height){var card=new Panel{Width=Math.Max(650,body.ClientSize.Width-78),Height=height,BackColor=Color.White,BorderStyle=BorderStyle.FixedSingle,Margin=new Padding(0,0,0,20),Padding=new Padding(20)};card.Controls.Add(new Label{Text=heading,Font=new Font("Segoe UI",12,FontStyle.Bold),AutoSize=true,Location=new Point(20,18)});return card;}
 void ShowPage(string name){SetShell(api.Connected||preview);page=name;foreach(var n in nav)n.Value.BackColor=n.Key==name?blue:dark;if(!api.Connected&&!preview){LoginPage();return;}if(name=="Painel")Dashboard();else if(name=="Produtos")ProductsPage();else if(name=="Adicionar produto")Editor(null);else if(name=="Categorias")CategoriesPage();else if(name=="Mídia")MediaPage();else SettingsPage();}
 void RecoveryDialog(){using(var d=new Form{Text="Recuperar acesso — Videira Site",Width=670,Height=390,StartPosition=FormStartPosition.CenterParent,Font=Font,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false}){var note=new Label{Text="1. Solicite o e-mail.\n2. No e-mail, copie o endereço do botão de recuperação sem abrir o link.\n3. Cole abaixo e defina sua nova senha.",Location=new Point(20,20),Size=new Size(610,70)};d.Controls.Add(note);var send=new Button{Text="Enviar e-mail de recuperação",Location=new Point(20,95),Size=new Size(245,32)};d.Controls.Add(send);var link=new TextBox{Location=new Point(20,166),Width=610};d.Controls.Add(new Label{Text="Endereço do link recebido no e-mail",Location=new Point(20,141),AutoSize=true});d.Controls.Add(link);var newpass=new TextBox{Location=new Point(20,224),Width=380,UseSystemPasswordChar=true};d.Controls.Add(new Label{Text="Nova senha — pelo menos 10 caracteres",Location=new Point(20,199),AutoSize=true});d.Controls.Add(newpass);var reset=new Button{Text="Definir nova senha",Location=new Point(20,265),Size=new Size(170,32)};d.Controls.Add(reset);var result=new Label{Location=new Point(20,305),Size=new Size(610,45)};d.Controls.Add(result);send.Click+=async(a,b)=>{send.Enabled=false;try{await api.SendRecovery();result.Text="E-mail solicitado. Confira também a caixa de spam.";}catch(Exception ex){result.Text=ex.Message;}finally{send.Enabled=true;}};reset.Click+=async(a,b)=>{reset.Enabled=false;try{await api.Recover(link.Text,newpass.Text);newpass.Clear();link.Clear();result.Text="Senha atualizada. Feche esta janela e entre com a nova senha.";}catch(Exception ex){result.Text=ex.Message;}finally{reset.Enabled=true;}};d.ShowDialog(this);}}
 DataGridView Grid(){var g=new DataGridView{ReadOnly=true,AllowUserToAddRows=false,AllowUserToDeleteRows=false,MultiSelect=true,SelectionMode=DataGridViewSelectionMode.FullRowSelect,RowHeadersVisible=false,BackgroundColor=Color.White,BorderStyle=BorderStyle.FixedSingle,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,EnableHeadersVisualStyles=false,ColumnHeadersHeight=42};g.ColumnHeadersDefaultCellStyle.BackColor=Color.FromArgb(246,247,247);g.ColumnHeadersDefaultCellStyle.ForeColor=Color.FromArgb(44,51,56);g.DefaultCellStyle.SelectionBackColor=Color.FromArgb(227,241,248);g.DefaultCellStyle.SelectionForeColor=Color.FromArgb(0,90,140);g.AlternatingRowsDefaultCellStyle.BackColor=Color.FromArgb(249,249,249);g.GridColor=Color.FromArgb(230,230,230);g.RowTemplate.Height=44;return g;}
 TextBox Input(Panel card,string label,int x,int y,int width,string value="",bool multiline=false){card.Controls.Add(new Label{Text=label,Location=new Point(x,y),AutoSize=true});var t=new TextBox{Text=value,Location=new Point(x,y+25),Size=new Size(width,multiline?110:28),Multiline=multiline,MaxLength=multiline?5000:200};t.TextChanged+=(s,e)=>dirty=true;card.Controls.Add(t);return t;}
 public void SavePreview(string path){using(var image=new Bitmap(Width,Height)){DrawToBitmap(image,new Rectangle(0,0,Width,Height));image.Save(path);}}
 [STAThread] public static void Main(string[] args){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);CultureInfo.DefaultThreadCurrentCulture=CultureInfo.GetCultureInfo("pt-BR");bool check=args.Contains("--self-test");bool demo=args.Contains("--preview")||check;using(var app=new VideiraSite(demo)){if(demo||args.Contains("--preview-login"))app.Shown+=(s,e)=>{var timer=new Timer{Interval=600};timer.Tick+=(a,b)=>{timer.Stop();if(check){try{app.CheckScreens();File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"ui-check.txt"),"PASS: painel, lista de produtos, editor, categorias, mídia e configurações renderizados.");}catch(Exception ex){File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"ui-check.txt"),"FAIL: "+ex.ToString());}}app.SavePreview(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"videira-site-preview.png"));app.Close();};timer.Start();};Application.Run(app);}}
}
public class ProductRow {public string Id{get;set;}public string Produto{get;set;}public string Categoria{get;set;}public string Preço{get;set;}public string Situação{get;set;}}
public class CategoryRow {public string Nome{get;set;}public int Produtos{get;set;}}
public class MediaRow {public string Produto{get;set;}public string Imagem{get;set;}}
}
