using System;
using System.Data;
using System.IO;
namespace Videira {
static class AdvancedTests {
 static void Check(bool b,string message){if(!b)throw new Exception(message);}
 public static void Run(){string root=Path.Combine(Environment.CurrentDirectory,"work","Tests12-"+Guid.NewGuid());var s=new Store(root);s.Data.Tables["Produtos"].Rows.Add(1,"A","Vinho A","F",50m,80m,10m,"Sim");s.Data.Tables["Produtos"].Rows.Add(2,"B","Vinho B","F",20m,40m,10m,"Sim");var a=s.Data.Tables["Produtos"].Rows.Find(1);a["Embalagem unitária"]=1.5m;a["Outros custos unitários"]=2m;a["Despesa variável %"]=5m;var b=s.Data.Tables["Produtos"].Rows.Find(2);b["Embalagem unitária"]=1m;
  var cart=new DataTable();cart.Columns.Add("Produto",typeof(int));cart.Columns.Add("Quantidade",typeof(decimal));cart.Columns.Add("Preço",typeof(decimal));cart.Rows.Add(1,2m,80m);cart.Rows.Add(2,3m,40m);int id=s.Sell(cart,"Teste","Cartão",2.5m);var v=s.Data.Tables["Vendas"].Rows.Find(id);Check((decimal)v["Total"]==280m,"Total com produtos distintos");Check((decimal)v["Embalagem"]==6m,"Embalagem variável por unidade");Check((decimal)v["Custo"]==160m,"Custo dos produtos");Check((decimal)v["Outras despesas"]==12m,"Custos adicionais e percentual");Check((decimal)v["Taxa R$"]==7m,"Taxa cartão");Check((decimal)v["Resultado"]==95m,"Resultado com todos os custos");
  a["Embalagem unitária"]=9m;a["Custo"]=99m;s.Save();s=new Store(root);Check((decimal)s.Data.Tables["Vendas"].Rows.Find(id)["Resultado"]==95m,"Histórico preservado");Check((decimal)s.Data.Tables["Itens"].Rows.Find(1)["Embalagem unitária"]==1.5m,"Embalagem registrada no item");s.Data.Tables["Despesas"].Rows.Add(1,DateTime.Today,"Gastos fixos","Aluguel",20m);s.Data.Tables["Despesas"].Rows.Add(2,DateTime.Today,"Gastos variáveis","Frete",5m);s.Data.Tables["Despesas"].Rows.Add(3,DateTime.Today.AddMonths(-2),"Gastos fixos","Anterior",100m);Check((decimal)s.Finance(DateTime.Today,DateTime.Today).Rows[8][1]==70m,"Resultado por período");Check((decimal)s.Finance(DateTime.Today.AddDays(1),DateTime.Today.AddDays(1)).Rows[0][1]==0m,"Exclusão fora do período");s.Cancel(id);Check((decimal)s.Finance(DateTime.Today,DateTime.Today).Rows[0][1]==0m,"Cancelamento excluído do financeiro");
  var old=s.Data.Copy();foreach(string col in new[]{"Outras despesas"})old.Tables["Vendas"].Columns.Remove(col);old.Tables["Itens"].Columns.Remove("Embalagem unitária");old.Tables["Itens"].Columns.Remove("Outras despesas");foreach(string col in new[]{"Embalagem unitária","Outros custos unitários","Despesa variável %"})old.Tables["Produtos"].Columns.Remove(col);Store.Upgrade(old);Check((decimal)old.Tables["Produtos"].Rows.Find(1)["Embalagem unitária"]==1m,"Migração padrão R$1");Check((decimal)old.Tables["Vendas"].Rows.Find(id)["Outras despesas"]==0m,"Migração histórico");
  Directory.Delete(root,true);File.AppendAllText(Path.Combine(Environment.CurrentDirectory,"work","test-result.txt"),"\r\nPASS 1.2: embalagem por produto, custos adicionais, percentuais, preservação do histórico, financeiro por período, cancelamento e migração da versão anterior.");
  string migrationRoot=Path.Combine(Environment.CurrentDirectory,"work","MigrationCheck");if(File.Exists(Path.Combine(migrationRoot,"videira.xml"))){var oldData=new DataSet();oldData.ReadXml(Path.Combine(migrationRoot,"videira.xml"),XmlReadMode.ReadSchema);var upgraded=new Store(migrationRoot);foreach(DataTable table in oldData.Tables){Check(table.TableName=="Taxas"?upgraded.Data.Tables[table.TableName].Rows.Count>=table.Rows.Count:upgraded.Data.Tables[table.TableName].Rows.Count==table.Rows.Count,"Quantidade de registros após migração");foreach(DataRow row in table.Rows){var migrated=upgraded.Data.Tables[table.TableName].Rows.Find(row["Id"]);foreach(DataColumn col in table.Columns)Check(row.IsNull(col)?!migrated.IsNull(col.ColumnName)||upgraded.Data.Tables[table.TableName].Columns[col.ColumnName].DefaultValue==DBNull.Value:object.Equals(row[col],migrated[col.ColumnName]),"Preservação de "+table.TableName+" / "+col.ColumnName);}}upgraded.Save();var reopened=new Store(migrationRoot);Check(reopened.Data.Tables["Produtos"].Rows.Count==oldData.Tables["Produtos"].Rows.Count,"Reabertura dos dados migrados");File.AppendAllText(Path.Combine(Environment.CurrentDirectory,"work","test-result.txt"),"\r\nPASS: cópia dos dados instalados migrada e reaberta, preservando todos os campos e registros existentes.");}
 }
}
}


