using System;using System.Data;using System.Linq;using System.IO;using System.Collections.Generic;using System.Net;using System.Net.Http;using System.Text;using System.Web.Script.Serialization;using System.Windows.Forms;using System.Drawing;
namespace Videira {
public sealed class CloudStore:IDisposable{
 const string Url="https://lahajlrombmoftevweaf.supabase.co",Key="sb_publishable_ixLS7JIsBDtPF75R-rZwcA_2eAD0bKV";
 readonly HttpClient http=new HttpClient{Timeout=TimeSpan.FromSeconds(40)};readonly JavaScriptSerializer json=new JavaScriptSerializer{MaxJsonLength=15000000};string token,refresh,owner;DateTime expires;long revision;
 public CloudStore(){ServicePointManager.SecurityProtocol=SecurityProtocolType.Tls12;}
 object Call(string path,string method,object body,bool auth=true){if(auth&&DateTime.UtcNow>=expires){var session=(Dictionary<string,object>)Call("/auth/v1/token?grant_type=refresh_token","POST",new{refresh_token=refresh},false);Session(session);}using(var r=new HttpRequestMessage(new HttpMethod(method),Url+path)){r.Headers.Add("apikey",Key);r.Headers.Add("Authorization","Bearer "+(auth?token:Key));if(body!=null)r.Content=new StringContent(json.Serialize(body),Encoding.UTF8,"application/json");using(var response=http.SendAsync(r).GetAwaiter().GetResult()){string text=response.Content.ReadAsStringAsync().GetAwaiter().GetResult();object value=text.Length==0?null:json.DeserializeObject(text);if(!response.IsSuccessStatusCode){var error=value as Dictionary<string,object>;string message=error!=null&&error.ContainsKey("message")?Convert.ToString(error["message"]):error!=null&&error.ContainsKey("msg")?Convert.ToString(error["msg"]):"Falha na conexão online.";if(message.Contains("Invalid login credentials"))message="E-mail ou senha recusados. Use a mesma conta do Videira Site.";throw new Exception(message);}return value;}}}
 void Session(Dictionary<string,object> data){token=Convert.ToString(data["access_token"]);refresh=Convert.ToString(data["refresh_token"]);expires=DateTime.UtcNow.AddSeconds(Convert.ToDouble(data["expires_in"])-60);if(data.ContainsKey("user"))owner=Convert.ToString(((Dictionary<string,object>)data["user"])["id"]);}
 public void Login(string email,string password){Session((Dictionary<string,object>)Call("/auth/v1/token?grant_type=password","POST",new{email=email.Trim(),password=password},false));Fetch();}
 public Dictionary<string,object> Fetch(){var rows=(object[])Call("/rest/v1/erp_workspaces?select=payload,revision","GET",null);if(rows.Length!=1)throw new Exception("Esta conta não tem acesso ao Gestão da Videira.");var row=(Dictionary<string,object>)rows[0];revision=Convert.ToInt64(row["revision"]);return (Dictionary<string,object>)row["payload"];}
 public void Commit(DataSet data){var result=(Dictionary<string,object>)Call("/rest/v1/rpc/save_erp_workspace","POST",new{expected_revision=revision,new_payload=Snapshot(data)});revision=Convert.ToInt64(result["revision"]);}
 public static Dictionary<string,object> Snapshot(DataSet data){var tables=new Dictionary<string,object>();foreach(DataTable table in data.Tables){var columns=table.Columns.Cast<DataColumn>().Select(c=>new{name=c.ColumnName,type=c.DataType==typeof(DateTime)?"date":c.DataType==typeof(bool)?"bool":c.DataType==typeof(int)?"int":c.DataType==typeof(decimal)?"number":"text",default_value=c.DefaultValue==DBNull.Value?null:c.DefaultValue}).ToArray();var rows=table.Rows.Cast<DataRow>().Where(r=>r.RowState!=DataRowState.Deleted).Select(r=>table.Columns.Cast<DataColumn>().ToDictionary(c=>c.ColumnName,c=>r[c]==DBNull.Value?null:c.DataType==typeof(DateTime)?(object)((DateTime)r[c]).ToString("o"):r[c])).ToArray();tables[table.TableName]=new{columns=columns,rows=rows};}return new Dictionary<string,object>{{"format",1},{"tables",tables}};}
 static DateTime LocalDate(object value){var date=DateTime.Parse(Convert.ToString(value),System.Globalization.CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.RoundtripKind);return date.Kind==DateTimeKind.Utc?date.ToLocalTime():date;}
 public static void Restore(DataSet data,Dictionary<string,object> snapshot){var tables=(Dictionary<string,object>)snapshot["tables"];var replacement=data.Clone();foreach(var entry in tables){if(!replacement.Tables.Contains(entry.Key))throw new Exception("Esta versão do Gestão não reconhece a tabela "+entry.Key+". Atualize o aplicativo.");var table=replacement.Tables[entry.Key];foreach(var value in (System.Collections.IEnumerable)((Dictionary<string,object>)entry.Value)["rows"]){var row=table.NewRow();foreach(var item in (Dictionary<string,object>)value){if(!table.Columns.Contains(item.Key))throw new Exception("Atualize o Gestão: existe um campo mais recente no banco online.");if(item.Value==null){row[item.Key]=DBNull.Value;continue;}Type type=table.Columns[item.Key].DataType;row[item.Key]=type==typeof(DateTime)?(object)LocalDate(item.Value):Convert.ChangeType(item.Value,type,System.Globalization.CultureInfo.InvariantCulture);}table.Rows.Add(row);}}data.Clear();data.Merge(replacement,false,MissingSchemaAction.Error);}
 public static CloudStore AskLogin(){var cloud=new CloudStore();using(var form=new Form{Text="Videira Gestão — Acesso online",Width=490,Height=390,StartPosition=FormStartPosition.CenterScreen,Font=new Font("Segoe UI",10),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false}){form.Controls.Add(new Label{Text="Entre para acessar seus dados online",AutoSize=true,Location=new Point(25,25)});var email=new TextBox{Text="videiravinhoteca@gmail.com",Location=new Point(25,86),Width=415};var password=new TextBox{UseSystemPasswordChar=true,Location=new Point(25,155),Width=415};form.Controls.Add(new Label{Text="E-mail",AutoSize=true,Location=new Point(25,60)});form.Controls.Add(email);form.Controls.Add(new Label{Text="Senha",AutoSize=true,Location=new Point(25,130)});form.Controls.Add(password);var status=new Label{Location=new Point(25,255),Size=new Size(415,65),ForeColor=Color.Firebrick};form.Controls.Add(status);var button=new Button{Text="Acessar",Location=new Point(25,205),Size=new Size(140,34)};form.Controls.Add(button);form.AcceptButton=button;bool busy=false;form.FormClosing+=(s,e)=>{if(busy)e.Cancel=true;};button.Click+=async(s,e)=>{busy=true;button.Enabled=false;status.Text="Conectando…";try{string mail=email.Text,secret=password.Text;await System.Threading.Tasks.Task.Run(()=>cloud.Login(mail,secret));password.Clear();busy=false;form.DialogResult=DialogResult.OK;form.Close();}catch(Exception ex){status.Text=ex.Message;}finally{busy=false;button.Enabled=true;}};if(form.ShowDialog()==DialogResult.OK)return cloud;cloud.Dispose();return null;}}
 public void Dispose(){token=null;refresh=null;http.Dispose();}
}
partial class Store{
 public CloudStore Cloud;
 public void ConnectCloud(CloudStore cloud){CloudStore.Restore(Data,cloud.Fetch());Cloud=cloud;}
 public void ReloadCloud(){if(Cloud!=null)CloudStore.Restore(Data,Cloud.Fetch());}
}
}

