using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Windows.Forms;
namespace Videira {
partial class MainForm {
 void CompanyForm(){using(var d=new Dialog("Minha empresa • Cadastro e estratégia",1050,720)){
  d.Fields.Visible=false;var tabs=new TabControl{Dock=DockStyle.Fill,Padding=new Point(16,7)};d.Controls.Add(tabs);tabs.BringToFront();var identity=new TabPage("Dados da empresa"){BackColor=Theme.Surface,AutoScroll=true};var strategy=new TabPage("Precificação"){BackColor=Theme.Surface,AutoScroll=true};tabs.TabPages.Add(identity);tabs.TabPages.Add(strategy);var c=db.Company;var fields=new Dictionary<string,Control>();
  string[] names={"Nome fantasia","Razão social","CNPJ","Inscrição estadual","Telefone","WhatsApp","Email","Responsável","Endereço","Cidade","UF","CEP"};for(int i=0;i<names.Length;i++){string key=names[i];var f=new TextBox{Text=c[key].ToString()};fields[key]=f;Theme.LabelField(identity,key,f,18+(i%2)*493,18+(i/2)*69,470);}
  var signature=new TextBox{Text=c["Assinatura"].ToString(),Multiline=true};fields["Assinatura"]=signature;Theme.LabelField(identity,"Mensagem de encerramento dos orçamentos",signature,18,438,963);signature.Height=85;
  var method=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList};method.Items.AddRange(new[]{"Por unidade","Por faturamento"});method.SelectedItem=c["Rateio"].ToString();fields["Rateio"]=method;Theme.LabelField(strategy,"Distribuição dos gastos mensais",method,18,20,963);
  foreach(string key in new[]{"Unidades mês","Faturamento mês","Margem padrão"}){var value=new NumericUpDown{Maximum=key=="Margem padrão"?99.99m:100000000,DecimalPlaces=key=="Unidades mês"?0:2,ThousandsSeparator=true,Value=(decimal)c[key]};fields[key]=value;int i=key=="Unidades mês"?0:key=="Faturamento mês"?1:2;Theme.LabelField(strategy,i==0?"Unidades estimadas por mês":i==1?"Faturamento estimado (R$)":"Margem de lucro padrão (%)",value,18+i*326,106,311);}
  var days=new NumericUpDown{Minimum=1,Maximum=365,Value=Math.Max(1,(int)c["Validade orçamento"])};fields["Validade orçamento"]=days;Theme.LabelField(strategy,"Validade padrão dos orçamentos (dias)",days,18,194,963);
  var instructions=new Label{Location=new Point(18,286),Size=new Size(963,160),Text="Como o preço é formado\n\n1. Custo do fornecedor + embalagem + outros custos por unidade.\n2. Parcela dos gastos mensais do Planejamento de despesas.\n3. Margem desejada, taxa de cartão e despesas percentuais incluídas no preço final.\n\nO plano mensal é uma previsão para precificar. Os gastos realizados são usados no resultado financeiro.",ForeColor=Color.FromArgb(57,76,99)};strategy.Controls.Add(instructions);
  var monthly=Theme.Readonly("R$ "+db.MonthlyPlan.ToString("N2"));Theme.LabelField(strategy,"Total do planejamento mensal",monthly,18,465,963);
  d.Commit(()=>{if(string.IsNullOrWhiteSpace(fields["Nome fantasia"].Text)&&string.IsNullOrWhiteSpace(fields["Razão social"].Text))throw new Exception("Informe o nome fantasia ou a razão social.");if(db.MonthlyPlan>0&&((method.Text=="Por unidade"&&((NumericUpDown)fields["Unidades mês"]).Value<=0)||(method.Text=="Por faturamento"&&((NumericUpDown)fields["Faturamento mês"]).Value<=0)))throw new Exception("Informe uma estimativa maior que zero para distribuir os gastos.");db.Atomic(()=>{foreach(var f in fields)c[f.Key]=f.Value is NumericUpDown?(f.Key=="Validade orçamento"?(object)(int)((NumericUpDown)f.Value).Value:((NumericUpDown)f.Value).Value):f.Value.Text.Trim();});Text="VIDEIRA GESTÃO • "+(string.IsNullOrWhiteSpace(c["Nome fantasia"].ToString())?c["Razão social"]:c["Nome fantasia"]);});if(preview&&activePreviewMode=="--preview-company-strategy")d.Shown+=(s,e)=>tabs.SelectedIndex=1;d.ShowDialog(this);
 }}
 void PricingPage(){page="Precificação";Header("Produtos • Formação estratégica do preço");var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(14),RowCount=3,ColumnCount=1};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,85));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,54));content.Controls.Add(layout);layout.BringToFront();var info=new Label{Dock=DockStyle.Fill,Text="Preço sugerido = custos por unidade + gastos mensais distribuídos, com margem e taxa embutidas.\nOs preços atuais só mudam ao aplicar a sugestão. Nas vendas e orçamentos, o preço automático usa a taxa de referência do produto e permanece igual no Pix e no cartão.",ForeColor=Color.DimGray};layout.Controls.Add(info,0,0);var g=Theme.Grid();g.Dock=DockStyle.Fill;layout.Controls.Add(g,0,1);
  Action refresh=()=>{var t=new DataTable();t.Columns.Add("Id",typeof(int));t.Columns.Add("Código");t.Columns.Add("Produto");t.Columns.Add("Compra",typeof(decimal));t.Columns.Add("Embalagem",typeof(decimal));t.Columns.Add("Preço atual",typeof(decimal));t.Columns.Add("Margem %",typeof(decimal));t.Columns.Add("Pagamento");t.Columns.Add("Preço sugerido",typeof(decimal));t.Columns.Add("Observação");foreach(DataRow p in db.Data.Tables["Produtos"].Rows){decimal suggested=0;string note="";try{suggested=db.Price(p,p["Taxa padrão"].ToString()).Price;}catch(Exception ex){note=ex.Message;}t.Rows.Add(p["Id"],p["Código"],p["Nome"],p["Custo"],p["Embalagem unitária"],p["Preço"],p["Margem desejada %"],p["Taxa padrão"],suggested,note);}g.DataSource=t;g.Columns["Id"].Visible=false;g.Columns["Produto"].FillWeight=250;g.Columns["Observação"].FillWeight=240;foreach(DataGridViewColumn c in g.Columns)if(c.ValueType==typeof(decimal))c.DefaultCellStyle.Format="N2";};Func<DataRow> selected=()=>{if(g.CurrentRow==null)throw new Exception("Selecione um produto.");return db.Data.Tables["Produtos"].Rows.Find(g.CurrentRow.Cells["Id"].Value);};
  var actions=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false,Padding=new Padding(0,6,0,0)};layout.Controls.Add(actions,0,2);var edit=Btn("Editar produto",()=>{Product(selected());refresh();});edit.Width=165;actions.Controls.Add(edit);var apply=Btn("Aplicar sugestão",()=>{var p=selected();decimal price=db.Price(p,p["Taxa padrão"].ToString()).Price;if(MessageBox.Show("Aplicar R$ "+price.ToString("N2")+" ao produto "+p["Nome"]+"?","Precificação",MessageBoxButtons.YesNo)==DialogResult.Yes){db.Atomic(()=>{p["Preço"]=price;p["Precificação automática"]="Sim";});refresh();}});apply.Width=175;actions.Controls.Add(apply);var company=Btn("Minha empresa",()=>{CompanyForm();refresh();});company.Width=165;actions.Controls.Add(company);var expenses=Btn("Planejar gastos",ExpenseHub);expenses.Width=175;actions.Controls.Add(expenses);actions.Controls.Add(Btn("Atualizar",refresh));actions.Controls.Add(Btn("Sair",Home));refresh();
 }
}
}

