using System;using System.Data;using System.Linq;using System.Drawing;using System.Windows.Forms;using System.Net;using System.Xml;using System.IO;using System.Globalization;
namespace Videira {
partial class Store {
 public static void DeliverySchema(DataSet d){if(!d.Tables.Contains("Entregas taxas"))Table(d,"Entregas taxas","Região","Cidade","Valor:n","Adicional condomínio:n","Ativo");Add(d.Tables["Empresa"],"Entregas importadas",typeof(string),"Não");Add(d.Tables["Empresa"],"Origem Porto Meira confirmada",typeof(string),"Não");Add(d.Tables["Empresa"],"Taxas somente 1x",typeof(string),"Não");Add(d.Tables["Empresa"],"Taxas Stone importadas",typeof(string),"Não");Add(d.Tables["Produtos"],"Confirmado",typeof(bool),true);foreach(string t in new[]{"Orçamentos","Vendas"}){foreach(string c in new[]{"CEP entrega","Endereço entrega","Região entrega","Tipo entrega"})Add(d.Tables[t],c,typeof(string),"");Add(d.Tables[t],"Entrega R$",typeof(decimal),0m);}}
 public void SetupFourRates(){if(Company["Taxas somente 1x"].ToString()=="Sim")return;Atomic(()=>{Data.Tables["Taxas"].Clear();Data.Tables["Taxas"].Rows.Add(1,"Débito VISA/MASTER",1.37m);Data.Tables["Taxas"].Rows.Add(2,"Crédito VISA/MASTER 1x",4.20m);Data.Tables["Taxas"].Rows.Add(3,"Crédito AMEX/ELO 1x",0m);Data.Tables["Taxas"].Rows.Add(4,"Débito ELO",2.58m);foreach(DataRow p in Data.Tables["Produtos"].Rows){string old=p["Taxa padrão"].ToString();p["Taxa padrão"]=old.IndexOf("Amex",StringComparison.OrdinalIgnoreCase)>=0||old.IndexOf("Elo",StringComparison.OrdinalIgnoreCase)>=0?"Crédito AMEX/ELO 1x":"Crédito VISA/MASTER 1x";if((decimal)p["Preço"]<=0&&(decimal)p["Estoque"]<=0)p["Confirmado"]=false;}Company["Taxas somente 1x"]="Sim";});}
 public bool SetupDelivery(){if(Company["Entregas importadas"].ToString()=="Sim")return false;using(var stream=typeof(Store).Assembly.GetManifestResourceStream("EntregasSpeed"))using(var reader=new StreamReader(stream)){string line;while((line=reader.ReadLine())!=null){var a=line.Split('|');decimal v=decimal.Parse(a[0],CultureInfo.InvariantCulture);foreach(string region in a[1].Split(';'))Data.Tables["Entregas taxas"].Rows.Add(Next("Entregas taxas"),region.Trim(),"Foz do Iguaçu",v,3m,"Sim");}}Company["Entregas importadas"]="Sim";return true;}
 public static string DeliveryRegionKey(string region){string key=MarketKey(region);if(key.StartsWith("JARDIM"))return key.Substring(6);if(key.StartsWith("JD"))return key.Substring(2);return key;}
 public DataRow ResolveDeliveryRegion(string region){var rows=Data.Tables["Entregas taxas"].AsEnumerable().Where(r=>r["Ativo"].ToString()=="Sim").ToArray();var matches=rows.Where(r=>MarketKey(r["Região"].ToString())==MarketKey(region)).ToArray();if(matches.Length==0&&!string.IsNullOrWhiteSpace(region))matches=rows.Where(r=>DeliveryRegionKey(r["Região"].ToString())==DeliveryRegionKey(region)).ToArray();if(matches.Length!=1)throw new Exception(matches.Length>1?"A região tem mais de uma tarifa. Confirme com a transportadora e ajuste o cadastro.":"Região não encontrada na tabela. Selecione o bairro correspondente ou cadastre a tarifa.");return matches[0];}
 public decimal DeliveryFee(string region,bool condo){if(Company["Origem Porto Meira confirmada"].ToString()!="Sim")throw new Exception("Confirme a origem Porto Meira em Financeiro > Entregas taxas antes de usar a tabela.");var row=ResolveDeliveryRegion(region);return (decimal)row["Valor"]+(condo?(decimal)row["Adicional condomínio"]:0);}
 public void SaveQuoteDelivery(int id,bool pickup,string cep,string address,string region,decimal fee){var q=Data.Tables["Orçamentos"].Rows.Find(id);if(!pickup&&(string.IsNullOrWhiteSpace(address)||string.IsNullOrWhiteSpace(region)))throw new Exception("Informe endereço e região da entrega.");q["Tipo entrega"]=pickup?"Retirada":"Entrega";q["CEP entrega"]=pickup?"":cep;q["Endereço entrega"]=pickup?"":address;q["Região entrega"]=pickup?"":region;q["Entrega R$"]=pickup?0:fee;q["Total"]=(decimal)q["Total"]+(decimal)q["Entrega R$"];q["Mensagem"]=QuoteMessage(q);}
 public string NextProductNumericCode(){int max=0;foreach(DataRow p in Data.Tables["Produtos"].Rows){int n;if(int.TryParse(p["Código"].ToString(),out n)&&n>max)max=n;}if(max==int.MaxValue)throw new Exception("Limite de códigos atingido.");return (max+1).ToString(System.Globalization.CultureInfo.InvariantCulture);}
 public void ConfirmMarketProduct(DataRow m){ConfirmMarketProducts(new[]{m});}
 public int ConfirmMarketProducts(System.Collections.Generic.IEnumerable<DataRow> entries){var ids=entries.Select(m=>(int)m["Id"]).Distinct().ToArray();if(ids.Length==0)throw new Exception("Selecione um ou mais produtos.");int count=0;Atomic(()=>{foreach(int id in ids){var m=Data.Tables["Mercado"].Rows.Find(id);if(m==null)throw new Exception("Referência não encontrada.");var p=Data.Tables["Produtos"].Rows.Find(m["Produto"]);if(p==null)throw new Exception("Produto não encontrado.");if((bool)p["Confirmado"])continue;if((decimal)p["Preço"]<=0){p["Preço"]=Price(p,p["Taxa padrão"].ToString()).Price;p["Precificação automática"]="Sim";}p["Código"]=NextProductNumericCode();if((decimal)p["Estoque"]==0){p["Estoque"]=1m;Move(p,1m,"Inicial","Confirmação do catálogo Mercado • estoque inicial");}p["Confirmado"]=true;p["Ativo"]="Sim";count++;}});return count;}

}
partial class MainForm {
 void DeliveryPage(){page="Entregas taxas";Header("Financeiro • Entregas taxas • Speed Moto Frete");var l=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12),RowCount=3};l.RowStyles.Add(new RowStyle(SizeType.Absolute,75));l.RowStyles.Add(new RowStyle(SizeType.Percent,100));l.RowStyles.Add(new RowStyle(SizeType.Absolute,55));content.Controls.Add(l);l.BringToFront();var origin=new CheckBox{Dock=DockStyle.Fill,Text="Confirmo que as entregas saem de Porto Meira, Foz do Iguaçu. Tabela enviada: condomínio + R$ 3,00.\nBairros sem tarifa: consultar a transportadora; nunca assumir entrega grátis.",Checked=db.Company["Origem Porto Meira confirmada"].ToString()=="Sim"};origin.CheckedChanged+=(s,e)=>db.Atomic(()=>db.Company["Origem Porto Meira confirmada"]=origin.Checked?"Sim":"Não");l.Controls.Add(origin,0,0);var g=Theme.Grid();g.Dock=DockStyle.Fill;l.Controls.Add(g,0,1);Action refresh=()=>{g.DataSource=db.Data.Tables["Entregas taxas"].Copy();g.Columns["Id"].Visible=false;g.Columns["Região"].FillWeight=250;};Action<DataRow> edit=r=>{using(var d=new Dialog("Taxa de entrega",650,460)){var name=d.TextField("Região / bairro",r==null?"":r["Região"].ToString());var city=d.TextField("Cidade",r==null?"Foz do Iguaçu":r["Cidade"].ToString());var value=d.Number("Entrega R$",r==null?0:(decimal)r["Valor"]);var condo=d.Number("Adicional condomínio R$",r==null?3:(decimal)r["Adicional condomínio"]);var active=d.Choice("Ativo",new[]{"Sim","Não"});active.SelectedItem=r==null?"Sim":r["Ativo"].ToString();d.Commit(()=>{if(name.Text.Trim()==""||value.Value<=0)throw new Exception("Informe região e tarifa maior que zero.");if(db.Data.Tables["Entregas taxas"].AsEnumerable().Any(x=>x!=r&&Store.MarketKey(x["Região"].ToString())==Store.MarketKey(name.Text)))throw new Exception("Região já cadastrada.");db.Atomic(()=>{if(r==null)db.Data.Tables["Entregas taxas"].Rows.Add(db.Next("Entregas taxas"),name.Text.Trim(),city.Text.Trim(),value.Value,condo.Value,active.Text);else{r["Região"]=name.Text.Trim();r["Cidade"]=city.Text.Trim();r["Valor"]=value.Value;r["Adicional condomínio"]=condo.Value;r["Ativo"]=active.Text;}});});if(d.ShowDialog(this)==DialogResult.OK)refresh();}};var bar=new FlowLayoutPanel{Dock=DockStyle.Fill};bar.Controls.Add(Btn("Nova região",()=>edit(null)));bar.Controls.Add(Btn("Editar",()=>{if(g.CurrentRow!=null)edit(db.Data.Tables["Entregas taxas"].Rows.Find(g.CurrentRow.Cells["Id"].Value));}));bar.Controls.Add(Btn("Sair",Home));l.Controls.Add(bar,0,2);refresh();}
}
class QuoteDeliveryPanel:Panel {
 Store db;public CheckBox Pickup=new CheckBox{Text="Retirada • sem entrega",Checked=true,AutoSize=true};public TextBox Cep=new TextBox(),Address=new TextBox(),HouseNumber=new TextBox();public string FullAddress{get{return Address.Text.Trim()+", nº "+HouseNumber.Text.Trim();}}public new ComboBox Region=new ComboBox{DropDownStyle=ComboBoxStyle.DropDown,AutoCompleteMode=AutoCompleteMode.SuggestAppend,AutoCompleteSource=AutoCompleteSource.ListItems};CheckBox condo=new CheckBox{Text="Condomínio (+ adicional cadastrado)",AutoSize=true};Label status=new Label{AutoSize=false};public Action Changed;public bool FeeKnown{get;private set;}public decimal Fee{get;private set;}public bool Condominium{get{return condo.Checked;}set{condo.Checked=value;}}bool busy=false;
 public QuoteDeliveryPanel(Store store){db=store;Dock=DockStyle.Fill;Pickup.Location=new Point(20,20);Controls.Add(Pickup);Theme.LabelField(this,"CEP (8 dígitos)",Cep,20,65,280);Theme.LabelField(this,"Número da residência",HouseNumber,650,65,300);Theme.LabelField(this,"Rua / complemento",Address,20,135,950);Theme.LabelField(this,"Região da tabela / bairro",Region,20,205,950);Region.Items.AddRange(db.Data.Tables["Entregas taxas"].AsEnumerable().Where(r=>r["Ativo"].ToString()=="Sim").Select(r=>r["Região"].ToString()).OrderBy(x=>x).ToArray());condo.Location=new Point(20,280);Controls.Add(condo);status.Location=new Point(20,330);status.Size=new Size(950,100);Controls.Add(status);var lookup=new Button{Text="Consultar CEP / rua",Location=new Point(330,87),Size=new Size(180,28)};Controls.Add(lookup);lookup.Click+=async(s,e)=>{if(busy)return;string cep=new string(Cep.Text.Where(char.IsDigit).ToArray());bool byAddress=cep.Length==0;string street=Address.Text.Split(',')[0].Trim();if(!byAddress&&cep.Length!=8){status.Text="Informe CEP com 8 dígitos.";return;}if(byAddress&&street.Length<3){status.Text="Informe o CEP ou a rua no endereço.";return;}busy=true;lookup.Enabled=false;status.Text="Consultando CEP...";try{ServicePointManager.SecurityProtocol=(SecurityProtocolType)3072;string xml;using(var web=new WebClient()){web.Encoding=System.Text.Encoding.UTF8;xml=await web.DownloadStringTaskAsync(new Uri(byAddress?"https://viacep.com.br/ws/PR/Foz%20do%20Igua%C3%A7u/"+Uri.EscapeDataString(street)+"/xml/":"https://viacep.com.br/ws/"+cep+"/xml/"));}if(IsDisposed)return;if(new string(Cep.Text.Where(char.IsDigit).ToArray())!=cep)return;var doc=new XmlDocument();doc.LoadXml(xml);Func<string,string> get=k=>doc.SelectSingleNode("//"+k)==null?"":doc.SelectSingleNode("//"+k).InnerText;if(byAddress){var neighborhoods=doc.SelectNodes("//bairro").Cast<XmlNode>().Select(n=>n.InnerText).Distinct().ToArray();if(neighborhoods.Length!=1)throw new Exception("Rua não encontrada ou com mais de uma região. Informe o CEP exato.");}if(get("erro")=="true")throw new Exception("CEP não encontrado.");if(Store.MarketKey(get("localidade"))!=Store.MarketKey("Foz do Iguaçu"))throw new Exception("Endereço fora de Foz do Iguaçu. Entrega a combinar com a transportadora.");if(!byAddress)Address.Text=get("logradouro");Region.Text=get("bairro");RefreshFee();}catch(Exception ex){if(!IsDisposed){Region.Text="";status.Text="Não foi possível definir entrega: "+ex.Message;}}finally{busy=false;if(!lookup.IsDisposed)lookup.Enabled=true;}};Cep.Leave+=(s,e)=>{if(!Pickup.Checked&&new string(Cep.Text.Where(char.IsDigit).ToArray()).Length==8)lookup.PerformClick();};Pickup.CheckedChanged+=(s,e)=>RefreshFee();Region.TextChanged+=(s,e)=>RefreshFee();condo.CheckedChanged+=(s,e)=>RefreshFee();RefreshFee();}
 void RefreshFee(){Cep.Enabled=Address.Enabled=HouseNumber.Enabled=Region.Enabled=condo.Enabled=!Pickup.Checked;Fee=0;FeeKnown=Pickup.Checked;if(Pickup.Checked)status.Text="Retirada: não há cobrança nem endereço de entrega na mensagem.";else try{Fee=db.DeliveryFee(Region.Text,condo.Checked);FeeKnown=true;string canonical=db.ResolveDeliveryRegion(Region.Text)["Região"].ToString();if(Region.Text!=canonical)Region.Text=canonical;status.Text="Entrega: R$ "+Fee.ToString("N2")+". Confira a região e complete o número do endereço.";}catch(Exception ex){status.Text=ex.Message;}if(Changed!=null)Changed();}
 public void ValidateDelivery(){if(Pickup.Checked)return;if(busy)throw new Exception("Aguarde a consulta do CEP.");Fee=db.DeliveryFee(Region.Text,condo.Checked);if(string.IsNullOrWhiteSpace(HouseNumber.Text))throw new Exception("Informe o número da residência ou S/N.");if(string.IsNullOrWhiteSpace(Address.Text)||Address.Text.EndsWith(": "))throw new Exception("Complete o endereço, incluindo número e complemento.");}
}
}
