using System;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
namespace Videira { partial class MainForm {
 void FinancePage(){page="Painel financeiro";Header("Financeiro • Resultado, lançamentos e planejamento");var body=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(14),ColumnCount=1,RowCount=5};body.RowStyles.Add(new RowStyle(SizeType.Absolute,60));body.RowStyles.Add(new RowStyle(SizeType.Absolute,200));body.RowStyles.Add(new RowStyle(SizeType.Absolute,50));body.RowStyles.Add(new RowStyle(SizeType.Percent,100));body.RowStyles.Add(new RowStyle(SizeType.Absolute,54));content.Controls.Add(body);body.BringToFront();
 var filters=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false};body.Controls.Add(filters,0,0);var start=new DateTimePicker{Format=DateTimePickerFormat.Short,Value=new DateTime(DateTime.Today.Year,DateTime.Today.Month,1),Width=145};var end=new DateTimePicker{Format=DateTimePickerFormat.Short,Value=DateTime.Today,Width=145};filters.Controls.Add(new Label{Text="Período:",AutoSize=true,Margin=new Padding(0,9,6,0)});filters.Controls.Add(start);filters.Controls.Add(new Label{Text="até",AutoSize=true,Margin=new Padding(6,9,6,0)});filters.Controls.Add(end);
 var cards=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=2};for(int i=0;i<3;i++)cards.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100f/3));for(int i=0;i<2;i++)cards.RowStyles.Add(new RowStyle(SizeType.Percent,50));body.Controls.Add(cards,0,1);var values=new Label[6];string[] names={"VENDAS NO PERÍODO","CUSTOS DAS VENDAS","GASTOS NO PERÍODO","RESULTADO APÓS GASTOS","LANÇAMENTOS FUTUROS • APÓS HOJE","PLANEJAMENTO MENSAL • PRECIFICAÇÃO"};for(int i=0;i<6;i++){var box=new Panel{Dock=DockStyle.Fill,BackColor=i==3?Color.FromArgb(228,238,233):Color.White,Margin=new Padding(0,0,12,8),Padding=new Padding(14,9,14,8)};box.Controls.Add(new Label{Text=names[i],Dock=DockStyle.Top,Height=24,Font=new Font(Theme.Font,FontStyle.Bold),ForeColor=Color.FromArgb(65,80,83)});values[i]=new Label{Dock=DockStyle.Bottom,Height=38,Font=new Font("Tahoma",20,FontStyle.Bold)};box.Controls.Add(values[i]);cards.Controls.Add(box,i%3,i/3);}
 var info=new Label{Dock=DockStyle.Fill,ForeColor=Color.DimGray,TextAlign=ContentAlignment.MiddleLeft};body.Controls.Add(info,0,2);var tabs=new TabControl{Dock=DockStyle.Fill};body.Controls.Add(tabs,0,3);var grids=new DataGridView[5];string[] tabNames={"Composição do resultado","Despesas do período","Vendas do período","Produtos mais vendidos","Evolução mensal"};for(int i=0;i<5;i++){var tab=new TabPage(tabNames[i]){BackColor=Theme.Surface,Padding=new Padding(8)};tabs.TabPages.Add(tab);grids[i]=Theme.Grid();grids[i].BindingContext=new BindingContext();grids[i].Dock=DockStyle.Fill;tab.Controls.Add(grids[i]);}Action<DataGridView,DataTable> bind=(g,t)=>{g.DataSource=t;foreach(DataGridViewColumn c in g.Columns){if(c.Name=="Id"||c.Name=="Plano mensal")c.Visible=false;if(c.ValueType==typeof(decimal)){c.DefaultCellStyle.Format="N2";c.DefaultCellStyle.Alignment=DataGridViewContentAlignment.MiddleRight;}if(c.ValueType==typeof(DateTime))c.DefaultCellStyle.Format="dd/MM/yyyy";c.FillWeight=c.Name=="Descrição"||c.Name=="Indicador"||c.Name=="Produto"?280:100;}};
 Action refresh=()=>{if(end.Value.Date<start.Value.Date)throw new Exception("A data final deve ser igual ou posterior à inicial.");var t=db.Finance(start.Value,end.Value);bind(grids[0],t);Func<int,decimal> n=i=>(decimal)t.Rows[i][1];decimal sales=n(0),cost=n(1)+n(2)+n(3)+n(4),expenses=n(6)+n(7),result=n(8);decimal[] amounts={sales,cost,expenses,result,db.FutureExpenses(DateTime.Today),db.MonthlyPlan};for(int i=0;i<6;i++)values[i].Text="R$ "+amounts[i].ToString("N2");values[3].ForeColor=result<0?Color.Firebrick:Color.SeaGreen;info.Text="Período: "+start.Value.ToString("dd/MM/yyyy")+" a "+end.Value.ToString("dd/MM/yyyy")+"  |  Margem após gastos: "+(sales==0?"—":(result/sales*100).ToString("N2")+"%")+"\nO resultado usa a data de cada lançamento. Valores futuros e planejamento aparecem separados; o plano não é descontado novamente. Compras de embalagem aparecem como saída de caixa; o resultado já considera embalagem nas vendas.";bind(grids[1],db.PeriodRows("Despesas",start.Value,end.Value));var vs=db.PeriodRows("Vendas",start.Value,end.Value).DefaultView.ToTable(false,"Id","Data","Cliente","Pagamento","Total","Taxa R$","Resultado","Situação");bind(grids[2],vs);bind(grids[3],db.BestProducts(start.Value,end.Value));var trend=new DataTable();trend.Columns.Add("Mês");foreach(string c in new[]{"Vendas R$","Gastos R$","Resultado R$"})trend.Columns.Add(c,typeof(decimal));DateTime month=new DateTime(end.Value.Year,end.Value.Month,1);for(int i=5;i>=0;i--){var m=month.AddMonths(-i);var f=db.Finance(m,m.AddMonths(1).AddDays(-1));trend.Rows.Add(m.ToString("MM/yyyy"),f.Rows[0][1],(decimal)f.Rows[6][1]+(decimal)f.Rows[7][1],f.Rows[8][1]);}bind(grids[4],trend);};
 filters.Controls.Add(Btn("Atualizar",()=>Run(refresh)));filters.Controls.Add(Btn("Este mês",()=>{start.Value=new DateTime(DateTime.Today.Year,DateTime.Today.Month,1);end.Value=DateTime.Today;refresh();}));filters.Controls.Add(Btn("Hoje",()=>{start.Value=end.Value=DateTime.Today;refresh();}));Button all=Btn("Todos",()=>{start.Value=new DateTime(2000,1,1);var dates=db.Data.Tables["Despesas"].AsEnumerable().Select(r=>(DateTime)r["Data"]).Concat(db.Data.Tables["Vendas"].AsEnumerable().Select(r=>(DateTime)r["Data"])).Concat(new[]{DateTime.Today});end.Value=dates.Max();refresh();});filters.Controls.Add(all);var future=Btn("Futuros",()=>{start.Value=DateTime.Today.AddDays(1);end.Value=db.Data.Tables["Despesas"].AsEnumerable().Select(r=>(DateTime)r["Data"]).Concat(new[]{start.Value}).Max();refresh();tabs.SelectedIndex=1;});filters.Controls.Add(future);
 var actions=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false,Padding=new Padding(0,6,0,0)};body.Controls.Add(actions,0,4);var expense=Btn("Lançar gasto",()=>ExpenseEditor("Despesas",null,refresh));expense.Width=160;actions.Controls.Add(expense);foreach(string label in new[]{"Despesas","Taxa de maquininha","Precificação"}){string name=label;var b=Btn(name,()=>Navigate(name));b.Width=name=="Taxa de maquininha"?210:155;actions.Controls.Add(b);}var export=Btn("Exportar CSV",()=>{grid=grids[tabs.SelectedIndex];Export();});export.Width=160;actions.Controls.Add(export);actions.Controls.Add(Btn("Sair",Home));grids[1].CellDoubleClick+=(s,e)=>{if(e.RowIndex>=0)Run(()=>{var row=(DataRowView)grids[1].Rows[e.RowIndex].DataBoundItem;ExpenseEditor("Despesas",db.Data.Tables["Despesas"].Rows.Find(row["Id"]),refresh);});};refresh();
 }
}}

