using System;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
namespace Videira { partial class MainForm {
 void Home(){page="Início";Header("VIDEIRA GESTÃO • Visão da empresa");var body=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(16),ColumnCount=1,RowCount=5};body.RowStyles.Add(new RowStyle(SizeType.Absolute,95));body.RowStyles.Add(new RowStyle(SizeType.Absolute,108));body.RowStyles.Add(new RowStyle(SizeType.Absolute,125));body.RowStyles.Add(new RowStyle(SizeType.Absolute,65));body.RowStyles.Add(new RowStyle(SizeType.Percent,100));content.Controls.Add(body);body.BringToFront();var brand=new Panel{Dock=DockStyle.Fill};body.Controls.Add(brand,0,0);string company=db.Company["Nome fantasia"].ToString();if(string.IsNullOrWhiteSpace(company))company="Sua empresa";brand.Controls.Add(new Label{Text=company,Font=new Font("Tahoma",18,FontStyle.Bold),ForeColor=Color.FromArgb(68,78,74),Location=new Point(0,12),Size=new Size(760,33)});brand.Controls.Add(new Label{Text="Visão do mês • "+DateTime.Today.ToString("MMMM/yyyy")+"   |   Produtos, vendas e financeiro no mesmo banco",Location=new Point(0,52),Size=new Size(1000,26),ForeColor=Color.DimGray});
 DateTime month=new DateTime(DateTime.Today.Year,DateTime.Today.Month,1);var f=db.Finance(month,DateTime.Today);var kpis=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=4};for(int i=0;i<4;i++)kpis.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,25));body.Controls.Add(kpis,0,1);string[] names={"VENDAS DO MÊS","GASTOS DO MÊS","RESULTADO APÓS GASTOS","VALOR DE ESTOQUE • CUSTO"};decimal[] amounts={(decimal)f.Rows[0][1],(decimal)f.Rows[6][1]+(decimal)f.Rows[7][1],(decimal)f.Rows[8][1],db.Data.Tables["Produtos"].AsEnumerable().Sum(r=>(decimal)r["Estoque"]*(decimal)r["Custo"])};for(int i=0;i<4;i++){var box=new Panel{Dock=DockStyle.Fill,BackColor=i==2?Color.FromArgb(228,238,233):Color.White,Padding=new Padding(12),Margin=new Padding(0,0,12,12)};box.Controls.Add(new Label{Text=names[i],Dock=DockStyle.Top,Height=23,Font=new Font(Theme.Font,FontStyle.Bold),ForeColor=Color.FromArgb(66,80,73)});box.Controls.Add(new Label{Text="R$ "+amounts[i].ToString("N2"),Dock=DockStyle.Bottom,Height=35,Font=new Font("Tahoma",19,FontStyle.Bold),ForeColor=amounts[i]<0?Color.Firebrick:Color.FromArgb(57,83,69)});kpis.Controls.Add(box,i,0);}
 var quick=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=4,RowCount=2};for(int i=0;i<4;i++)quick.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,25));for(int i=0;i<2;i++)quick.RowStyles.Add(new RowStyle(SizeType.Percent,50));body.Controls.Add(quick,0,2);string[] nav={"Nova venda","Novo orçamento","Produtos","Resumo financeiro","Despesas","Precificação","Entradas de estoque","Minha empresa"};for(int i=0;i<nav.Length;i++){string name=nav[i];var b=Btn(name,()=>Navigate(name));b.Dock=DockStyle.Fill;b.Margin=new Padding(0,0,12,8);b.Font=new Font(Theme.Font,FontStyle.Bold);quick.Controls.Add(b,i%4,i/4);}
 int low=db.Data.Tables["Produtos"].AsEnumerable().Count(r=>r["Ativo"].ToString()=="Sim"&&(decimal)r["Estoque"]<=(decimal)r["Estoque mínimo"]);int open=db.Data.Tables["Orçamentos"].AsEnumerable().Count(r=>r["Situação"].ToString()=="Aberto");var alerts=new Label{Dock=DockStyle.Fill,ForeColor=Color.FromArgb(110,69,39),Text=low+" produto(s) no limite de estoque  |  "+open+" orçamento(s) aberto(s)  |  Gastos futuros: R$ "+db.FutureExpenses(DateTime.Today).ToString("N2")+"\nPlanejamento mensal: R$ "+db.MonthlyPlan.ToString("N2")+". Revise sua estimativa de unidades e as taxas de cartão para calcular os preços."};body.Controls.Add(alerts,0,3);
 var split=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2};split.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,55));split.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,45));body.Controls.Add(split,0,4);var topBox=new GroupBox{Text="Produtos mais vendidos no mês",Dock=DockStyle.Fill,Padding=new Padding(10),Margin=new Padding(0,0,12,0)};split.Controls.Add(topBox,0,0);var top=Theme.Grid();top.BindingContext=new BindingContext();top.Dock=DockStyle.Fill;topBox.Controls.Add(top);top.DataSource=db.BestProducts(month,DateTime.Today);top.Columns[0].FillWeight=280;top.Columns[3].Visible=false;top.Columns[1].DefaultCellStyle.Format="N0";top.Columns[2].DefaultCellStyle.Format="N2";
 var tabs=new TabControl{Dock=DockStyle.Fill};split.Controls.Add(tabs,1,0);var expenseTab=new TabPage("Próximos gastos"){Padding=new Padding(8)};var stockTab=new TabPage("Reposição de estoque"){Padding=new Padding(8)};tabs.TabPages.Add(expenseTab);tabs.TabPages.Add(stockTab);var future=Theme.Grid();future.BindingContext=new BindingContext();future.Dock=DockStyle.Fill;expenseTab.Controls.Add(future);var ft=db.Data.Tables["Despesas"].DefaultView.ToTable(false,"Data","Descrição","Valor");foreach(DataRow r in ft.Rows.Cast<DataRow>().ToArray())if((DateTime)r["Data"]<=DateTime.Today)ft.Rows.Remove(r);ft.DefaultView.Sort="Data ASC";future.DataSource=ft;future.Columns["Descrição"].FillWeight=250;future.Columns["Data"].DefaultCellStyle.Format="dd/MM/yyyy";future.Columns["Valor"].DefaultCellStyle.Format="N2";future.CellDoubleClick+=(s,e)=>ExpenseHub();var stock=Theme.Grid();stock.BindingContext=new BindingContext();stock.Dock=DockStyle.Fill;stockTab.Controls.Add(stock);var st=db.Data.Tables["Produtos"].DefaultView.ToTable(false,"Código","Nome","Estoque","Estoque mínimo");foreach(DataRow r in st.Rows.Cast<DataRow>().ToArray())if((decimal)r["Estoque"]>(decimal)r["Estoque mínimo"])st.Rows.Remove(r);stock.DataSource=st;stock.Columns["Nome"].FillWeight=280;stock.CellDoubleClick+=(s,e)=>ShowPage("Inventário");
 }
}}


