using System;
using System.Data;
using System.IO;
namespace Videira { static class IntegrationTests {
 static void Check(bool condition,string message){if(!condition)throw new Exception(message);}
 public static void Run(){string root=Path.Combine(Environment.CurrentDirectory,"work","Integration-"+Guid.NewGuid());var db=new Store(root);Check(db.Rate("Link • 1x • 1 dia útil")==4.20m&&db.Rate("Link • 12x • 1 dia útil")==16.66m,"Taxas Link das fotos");Check(db.Rate("InfiniteTap • Débito Visa • 1 dia útil")==1.37m&&db.Rate("InfiniteTap • Débito Elo • 1 dia útil")==2.58m,"Débito por bandeira");Check(44m-Store.Money(44m*db.Rate("InfiniteTap • Crédito Amex 1x • 1 dia útil")/100)==41.84m,"Crédito Amex líquido da foto");Check(44m-Store.Money(44m*db.Rate("InfiniteTap • Débito Visa • 1 dia útil")/100)==43.40m,"Débito Visa líquido da foto");Check(44m-Store.Money(44m*db.Rate("InfiniteTap • Débito Elo • 1 dia útil")/100)==42.86m,"Débito Elo líquido da foto");int initialRates=db.Data.Tables["Taxas"].Rows.Count;Check(!db.ImportInfiniteRates()&&db.Data.Tables["Taxas"].Rows.Count==initialRates,"Importação de taxas sem duplicar");db.Data.Tables["Produtos"].Rows.Add(1,"V1","Vinho teste","Fornecedor",50m,80m,10m,"Sim");var product=db.Data.Tables["Produtos"].Rows.Find(1);var cart=new DataTable();cart.Columns.Add("Produto",typeof(int));cart.Columns.Add("Código");cart.Columns.Add("Descrição");foreach(string col in new[]{"Quantidade","Preço original","Desconto %","Preço","Total"})cart.Columns.Add(col,typeof(decimal));db.SetCartItem(cart,null,product,2m,80m,10m);var row=cart.Rows[0];Check((decimal)row["Total"]==144m,"Total após desconto");db.SetCartItem(cart,row,product,3m,80m,5m);Check(cart.Rows.Count==1&&(decimal)row["Total"]==228m,"Editar quantidade e desconto sem duplicar");db.SetCartItem(cart,null,product,4m,80m,0m);bool blocked=false;try{db.SetCartItem(cart,row,product,7m,80m,5m);}catch{blocked=true;}Check(blocked&&(decimal)row["Quantidade"]==3m,"Edição valida estoque de todos os itens e preserva original");blocked=false;try{db.SetCartItem(cart,row,product,1.5m,80m,0m);}catch{blocked=true;}Check(blocked,"Quantidade fracionária bloqueada");blocked=false;try{db.SetCartItem(cart,row,product,1m,80m,101m);}catch{blocked=true;}Check(blocked,"Desconto inválido bloqueado");cart.Rows.RemoveAt(1);int sale=db.Sell(cart,"Teste","Crédito",3m);Check((decimal)db.Data.Tables["Vendas"].Rows.Find(sale)["Total"]==228m&&(decimal)product["Estoque"]==7m,"Venda usa item editado");db.Cancel(sale);Check((decimal)db.Data.Tables["Produtos"].Rows.Find(1)["Estoque"]==10m,"Cancelamento devolve quantidade editada");
 db.Data.Tables["Despesas"].Rows.Add(1,new DateTime(2026,11,13),"Gastos fixos","DAS",83m);Check((decimal)db.Finance(new DateTime(2026,10,1),new DateTime(2026,10,31)).Rows[6][1]==0m,"DAS futuro fora de outubro");Check(db.FutureExpenses(new DateTime(2026,10,7))==83m,"DAS visível no indicador futuro");Check((decimal)db.Finance(new DateTime(2026,11,1),new DateTime(2026,11,30)).Rows[6][1]==83m,"DAS integrado em novembro");db.Data.Tables["Despesas"].Rows.Find(1)["Data"]=new DateTime(2026,10,7);Check((decimal)db.Finance(new DateTime(2026,10,1),new DateTime(2026,10,31)).Rows[8][1]==-83m,"Editar data atualiza resumo financeiro");db.Data.Tables["Plano mensal"].Rows.Add(1,"Gastos fixos","Aluguel",1000m,31);Check(db.GenerateMonth(new DateTime(2027,2,1))==1,"Gerar mês");Check(db.GenerateMonth(new DateTime(2027,2,20))==0,"Gerar mês duas vezes não duplica");var recurring=db.Data.Tables["Despesas"].Rows.Find(2);Check((DateTime)recurring["Data"]==new DateTime(2027,2,28),"Dia mensal ajustado ao fim de fevereiro");Check(db.MonthlyPlan==1000m&&(decimal)db.Finance(new DateTime(2027,2,1),new DateTime(2027,2,28)).Rows[6][1]==1000m,"Plano integra preço e lançamento integra financeiro sem dupla contagem");db=new Store(root);Check(db.Data.Tables["Despesas"].Rows.Count==2&&db.MonthlyPlan==1000m,"Integração persistida após reabrir");Directory.Delete(root,true);File.AppendAllText(Path.Combine(Environment.CurrentDirectory,"work","test-result.txt"),"\r\nPASS 2.2: edição de item, desconto, estoque acumulado, cancelamento, DAS por data, futuro visível, correção de data, geração mensal única, fevereiro, plano sem dupla contagem e persistência.");}
}}

