using System;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
namespace Videira {
partial class MainForm {
 DataRow ProductLookup(){DataRow chosen=null;using(var f=new Form{Text="Pesquisa de Produtos",Size=new Size(1100,630),StartPosition=FormStartPosition.CenterParent,Font=Theme.Font,BackColor=Theme.Surface,MinimizeBox=false,MaximizeBox=false,KeyPreview=true}){
  var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12),ColumnCount=1,RowCount=4};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,35));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,51));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,51));f.Controls.Add(layout);
  var onlyStock=new CheckBox{Text="Somente com estoque",Checked=true,AutoSize=true,Font=new Font(Theme.Font,FontStyle.Bold)};layout.Controls.Add(onlyStock,0,0);var top=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false};layout.Controls.Add(top,0,1);var by=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=160};by.Items.AddRange(new[]{"Descrição","Código","EAN"});by.SelectedIndex=0;top.Controls.Add(by);var find=new TextBox{Width=480};top.Controls.Add(find);var g=Theme.Grid();g.AutoGenerateColumns=false;g.Columns.Add(new DataGridViewTextBoxColumn{Name="Id",DataPropertyName="Id",Visible=false});string[] cols={"Código","Nome","EAN","Unidade","Estoque","Preço"};foreach(string col in cols)g.Columns.Add(new DataGridViewTextBoxColumn{Name=col,DataPropertyName=col,HeaderText=col=="Nome"?"Descrição":col=="Preço"?"Preço referência":col});g.Columns["Nome"].FillWeight=360;g.Columns["EAN"].FillWeight=150;g.Columns["Unidade"].FillWeight=55;g.Columns["Estoque"].DefaultCellStyle.Format="N0";g.Columns["Preço"].DefaultCellStyle.Format="N2";g.Dock=DockStyle.Fill;layout.Controls.Add(g,0,2);var found=new Label{AutoSize=true,Margin=new Padding(8,12,8,0)};
  Action refresh=()=>{var t=db.Data.Tables["Produtos"].Clone();string field=by.SelectedIndex==0?"Nome":by.SelectedIndex==1?"Código":"EAN";foreach(DataRow p in db.Data.Tables["Produtos"].Rows)if(p["Ativo"].ToString()=="Sim"&&(bool)p["Confirmado"]&&(!onlyStock.Checked||(decimal)p["Estoque"]>0)&&(find.Text.Trim()==""||p[field].ToString().IndexOf(find.Text.Trim(),StringComparison.CurrentCultureIgnoreCase)>=0))t.ImportRow(p);g.DataSource=t;found.Text="Registros encontrados: "+t.Rows.Count;};find.TextChanged+=(s,e)=>refresh();by.SelectedIndexChanged+=(s,e)=>refresh();onlyStock.CheckedChanged+=(s,e)=>refresh();var searchButton=Btn("Pesquisar",refresh);searchButton.Width=150;top.Controls.Add(searchButton);
  Action confirm=()=>{if(g.CurrentRow==null)return;chosen=db.Data.Tables["Produtos"].Rows.Find(g.CurrentRow.Cells["Id"].Value);f.DialogResult=DialogResult.OK;f.Close();};var buttons=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(0,6,0,0)};layout.Controls.Add(buttons,0,3);var cancel=Btn("Sair",()=>f.Close());buttons.Controls.Add(cancel);var ok=Btn("Confirmar",confirm);ok.Width=150;buttons.Controls.Add(ok);buttons.Controls.Add(found);f.CancelButton=cancel;g.CellClick+=(s,e)=>{if(e.RowIndex>=0)confirm();};g.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Enter){e.SuppressKeyPress=true;confirm();}};find.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Enter){e.SuppressKeyPress=true;if(g.Rows.Count==1)confirm();else g.Focus();}};f.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Escape)f.Close();};f.Shown+=(s,e)=>find.Focus();refresh();
  if(preview&&activePreviewMode=="--preview-lookup-flow")f.Shown+=(s,e)=>{if(g.Rows.Count==0)throw new Exception("Pesquisa sem produtos de teste.");confirm();};
  if(preview&&activePreviewMode=="--preview-lookup")f.Shown+=(s,e)=>{var timer=new Timer{Interval=700};timer.Tick+=(a,b)=>{timer.Stop();using(var bmp=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bmp,new Rectangle(0,0,f.Width,f.Height));bmp.Save(System.IO.Path.Combine(Environment.CurrentDirectory,"work","lookup.png"));}f.Close();};timer.Start();};
  f.ShowDialog(this);
 }return chosen;}
 DataRow ClientLookup(){DataRow selected=null;using(var f=new Form{Text="Pesquisa de Clientes",Size=new Size(820,520),StartPosition=FormStartPosition.CenterParent,Font=Theme.Font,BackColor=Theme.Surface}){var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12),RowCount=3,ColumnCount=1};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,45));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,49));f.Controls.Add(layout);var find=new TextBox{Dock=DockStyle.Fill};layout.Controls.Add(find,0,0);var g=Theme.Grid();g.AutoGenerateColumns=false;foreach(string col in new[]{"Id","Nome","Telefone","Email"})g.Columns.Add(new DataGridViewTextBoxColumn{Name=col,DataPropertyName=col,HeaderText=col=="Id"?"Código":col});g.Columns["Nome"].FillWeight=260;g.Dock=DockStyle.Fill;layout.Controls.Add(g,0,1);Action refresh=()=>{var t=db.Data.Tables["Clientes"].Clone();foreach(DataRow r in db.Data.Tables["Clientes"].Rows)if(r["Nome"].ToString().IndexOf(find.Text.Trim(),StringComparison.CurrentCultureIgnoreCase)>=0||r["Id"].ToString()==find.Text.Trim())t.ImportRow(r);g.DataSource=t;};find.TextChanged+=(s,e)=>refresh();Action choose=()=>{if(g.CurrentRow==null)return;selected=db.Data.Tables["Clientes"].Rows.Find(g.CurrentRow.Cells["Id"].Value);f.Close();};g.CellClick+=(s,e)=>{if(e.RowIndex>=0)choose();};g.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Enter){e.SuppressKeyPress=true;choose();}};find.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Enter){e.SuppressKeyPress=true;g.Focus();}};var bar=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.RightToLeft};layout.Controls.Add(bar,0,2);bar.Controls.Add(Btn("Sair",()=>f.Close()));bar.Controls.Add(Btn("Confirmar",choose));refresh();f.ShowDialog(this);}return selected;}
}
class EntryNumber : NumericUpDown {
 public Action EnterAction;public bool HasFocus {get{return ContainsFocus;}}
 protected override bool ProcessCmdKey(ref Message msg,Keys keyData){if(keyData==Keys.Enter&&EnterAction!=null){ValidateEditText();EnterAction();return true;}return base.ProcessCmdKey(ref msg,keyData);}
 public void FocusValue(){Focus();Select(0,Text.Length);}
 public void Advance(){ValidateEditText();if(EnterAction!=null)EnterAction();}
}
}
