using System;
using System.Data;
using System.Linq;
using System.IO;
using System.Text;
using System.Globalization;
using System.Drawing;
using System.Windows.Forms;
namespace Videira {
partial class Store {
 public static void MarketSchema(DataSet ds){if(!ds.Tables.Contains("Mercado"))Table(ds,"Mercado","Produto:i","Catálogo","Bodega","Preço referência:n","Moeda","Fonte","URL","Situação","Consulta:d","Observações","Página PDF:i");Add(ds.Tables["Mercado"],"Editado pelo usuário",typeof(bool),false);}
 public static string MarketKey(string s){s=s.ToUpperInvariant().Normalize(NormalizationForm.FormD);return new string(s.Where(c=>CharUnicodeInfo.GetUnicodeCategory(c)!=UnicodeCategory.NonSpacingMark&&char.IsLetterOrDigit(c)).ToArray()).Replace("750ML","").Replace("CARMENERE","CARMENERE");}
 public int ImportPortfolio(){MarketSchema(Data);int added=0;var stream=typeof(Store).Assembly.GetManifestResourceStream("PortfolioMercado");if(stream==null)return 0;
 using(stream)using(var reader=new StreamReader(stream,Encoding.UTF8)){Atomic(()=>{string line;while((line=reader.ReadLine())!=null){if(string.IsNullOrWhiteSpace(line))continue;string[] f=line.Split('\t');if(Data.Tables["Mercado"].AsEnumerable().Any(r=>r["Catálogo"].ToString()==f[0]))continue;
 decimal ml=decimal.Parse(f[3],CultureInfo.InvariantCulture),cost=decimal.Parse(f[2],CultureInfo.InvariantCulture);string fullname=f[1]+" "+f[3]+"ML";
 var p=Data.Tables["Produtos"].AsEnumerable().FirstOrDefault(r=>MarketKey(r["Nome"].ToString())==MarketKey(fullname)&&((decimal)r["Volume ml"]==ml||(decimal)r["Volume ml"]==0));
 if(p==null){p=Data.Tables["Produtos"].NewRow();p["Id"]=Next("Produtos");string code="DUQ"+int.Parse(f[0]).ToString("D3");while(Data.Tables["Produtos"].AsEnumerable().Any(r=>r["Código"].ToString()==code))code+="A";
 p["Código"]=code;p["Nome"]=fullname;p["Fornecedor"]="DUQUINTAL";p["Custo"]=cost;p["Preço"]=0m;p["Estoque"]=0m;p["Ativo"]="Sim";p["Volume ml"]=ml;p["Marca"]=f[4];p["Embalagem unitária"]=1m;p["Precificação automática"]="Não";p["Confirmado"]=false;if(Company["Taxas Stone importadas"].ToString()=="Sim")p["Taxa padrão"]="Crédito VISA/MASTER 1x • Stone";else if(Company["Taxas somente 1x"].ToString()=="Sim")p["Taxa padrão"]="Crédito VISA/MASTER 1x";p["Observações"]="Importado do portfólio Duquintal 2026, página "+f[12]+". Defina o preço de venda antes de vender. "+f[11];Data.Tables["Produtos"].Rows.Add(p);added++;}
 else {p["Nome"]=fullname;if((decimal)p["Volume ml"]==0)p["Volume ml"]=ml;}
 var m=Data.Tables["Mercado"].NewRow();m["Id"]=Next("Mercado");m["Produto"]=p["Id"];m["Catálogo"]=f[0];m["Bodega"]=f[4];if(f[5]!="")m["Preço referência"]=decimal.Parse(f[5],CultureInfo.InvariantCulture);m["Moeda"]=f[6];m["Fonte"]=f[7];m["URL"]=f[8];m["Situação"]=f[9];m["Consulta"]=DateTime.ParseExact(f[10],"yyyy-MM-dd",CultureInfo.InvariantCulture);m["Observações"]=f[11];m["Página PDF"]=int.Parse(f[12]);Data.Tables["Mercado"].Rows.Add(m);
 }});}return added;
 }
 public void EditMarketRecord(DataRow m,string code,string name,decimal ml,string supplier,decimal cost,string winery,decimal? price,string currency,string source,string url,string status,DateTime date,string note){
var p=Data.Tables["Produtos"].Rows.Find(m["Produto"]);code=code.Trim().ToUpperInvariant();name=name.Trim().ToUpperInvariant();
if(code==""||name==""||ml<=0||ml!=Math.Truncate(ml)||cost<0)throw new Exception("Informe código, nome, volume inteiro positivo e custo válido.");
if(Data.Tables["Produtos"].AsEnumerable().Any(r=>r!=p&&string.Equals(r["Código"].ToString(),code,StringComparison.OrdinalIgnoreCase)))throw new Exception("Este código já pertence a outro produto.");
if(!new[]{"BRL","CLP","ARS","EUR","USD"}.Contains(currency))throw new Exception("Selecione uma moeda válida.");
if(price.HasValue&&(price.Value<=0||string.IsNullOrWhiteSpace(source)))throw new Exception("Informe preço positivo e a loja ou fonte da referência.");
Uri u;if(!string.IsNullOrWhiteSpace(url)&&(!Uri.TryCreate(url,UriKind.Absolute,out u)||(u.Scheme!="http"&&u.Scheme!="https")))throw new Exception("Use um link http/https válido ou deixe o link vazio.");
Atomic(()=>{p["Código"]=code;p["Nome"]=name;p["Volume ml"]=ml;p["Fornecedor"]=supplier.Trim();p["Custo"]=cost;m["Bodega"]=winery.Trim().ToUpperInvariant();m["Preço referência"]=price.HasValue?(object)price.Value:DBNull.Value;m["Moeda"]=currency;m["Fonte"]=source.Trim();m["URL"]=url.Trim();m["Situação"]=price.HasValue||status=="Rótulo a confirmar"?status:"Sem preço confirmado";m["Consulta"]=date.Date;m["Observações"]=note;m["Editado pelo usuário"]=true;});}
 public int FillMissingMarketReferences(){int filled=0;using(var stream=typeof(Store).Assembly.GetManifestResourceStream("PortfolioMercado"))using(var reader=new StreamReader(stream,Encoding.UTF8)){Atomic(()=>{string line;while((line=reader.ReadLine())!=null){var f=line.Split('\t');var m=Data.Tables["Mercado"].AsEnumerable().FirstOrDefault(r=>r["Catálogo"].ToString()==f[0]);if(m!=null&&!(bool)m["Editado pelo usuário"]&&m.IsNull("Preço referência")&&f[5]==""&&m["URL"].ToString()==""&&f[8]!=""){m["URL"]=f[8];m["Observações"]=f[11];}if(m==null||(bool)m["Editado pelo usuário"]||!m.IsNull("Preço referência")||f[5]==""||m["Situação"].ToString()=="Rótulo a confirmar"||!string.IsNullOrEmpty(m["Fonte"].ToString()))continue;m["Preço referência"]=decimal.Parse(f[5],CultureInfo.InvariantCulture);m["Moeda"]=f[6];m["Fonte"]=f[7];m["URL"]=f[8];m["Situação"]=f[9];m["Consulta"]=DateTime.ParseExact(f[10],"yyyy-MM-dd",CultureInfo.InvariantCulture);m["Observações"]=f[11];filled++;}});}return filled;}
 public DataTable MarketView(bool onlyPending=false){var t=new DataTable();t.Columns.Add("Id",typeof(int));t.Columns.Add("Produto",typeof(int));t.Columns.Add("Código");t.Columns.Add("Nome");t.Columns.Add("ML",typeof(decimal));t.Columns.Add("Custo fornecedor R$",typeof(decimal));t.Columns.Add("Bodega / mercado R$",typeof(decimal));t.Columns.Add("Markup %",typeof(decimal));t.Columns.Add("Lucro bruto R$",typeof(decimal));t.Columns.Add("Preço original",typeof(decimal));t.Columns.Add("Moeda");t.Columns.Add("Bodega");t.Columns.Add("Fonte");t.Columns.Add("Situação");t.Columns.Add("Consulta",typeof(DateTime));foreach(string key in new[]{"Embalagem R$","Gastos rateados R$","Taxa R$","Custo total R$","Resultado estimado R$","Markup custo total %"})t.Columns.Add(key,typeof(decimal));t.Columns.Add("Cálculo de custos");
 foreach(DataRow m in Data.Tables["Mercado"].Rows){var p=Data.Tables["Produtos"].Rows.Find(m["Produto"]);if(p==null||(onlyPending&&(bool)p["Confirmado"]))continue;var r=t.NewRow();r["Id"]=m["Id"];r["Produto"]=p["Id"];r["Código"]=p["Código"];r["Nome"]=p["Nome"];r["ML"]=p["Volume ml"];decimal c=(decimal)p["Custo"];r["Custo fornecedor R$"]=c;r["Preço original"]=m["Preço referência"];r["Moeda"]=m["Moeda"];if(!m.IsNull("Preço referência")&&m["Moeda"].ToString()=="BRL"&&m["Situação"].ToString()!="Rótulo a confirmar"){decimal v=(decimal)m["Preço referência"];r["Bodega / mercado R$"]=v;r["Lucro bruto R$"]=Money(v-c);try{var x=CostsAt(p,v);decimal total=x.Base+x.Overhead+x.Fee+x.Variable;r["Embalagem R$"]=p["Embalagem unitária"];r["Gastos rateados R$"]=Money(x.Overhead);r["Taxa R$"]=Money(x.Fee);r["Custo total R$"]=Money(total);r["Resultado estimado R$"]=Money(x.Profit);if(total>0)r["Markup custo total %"]=Money(x.Profit/total*100);r["Cálculo de custos"]="Taxa de referência: "+p["Taxa padrão"];}catch(Exception ex){r["Cálculo de custos"]=ex.Message;}if(c>0)r["Markup %"]=Money((v-c)/c*100);}
 foreach(string field in new[]{"Bodega","Fonte","Situação","Consulta"})r[field]=m[field];t.Rows.Add(r);}return t;
 }
}
partial class MainForm {
 void MarketPage(){page="Mercado";Header("Mercado • comparação por garrafa");var panel=new Panel{Dock=DockStyle.Fill,Padding=new Padding(12,8,12,8)};content.Controls.Add(panel);panel.BringToFront();var layout=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=4};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,68));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,48));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,48));panel.Controls.Add(layout);
 Action marketSelectAll=()=>{};var filter=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(0,10,0,0)};var query=new TextBox{Width=310};var state=new ComboBox{Width=220,DropDownStyle=ComboBoxStyle.DropDownList};state.Items.AddRange(new[]{"Todos","Com referência em reais","Sem referência em reais","Moeda estrangeira","Rótulo a confirmar"});state.SelectedIndex=0;filter.Controls.Add(new Label{Text="Código / nome / bodega",AutoSize=true,Margin=new Padding(0,6,8,0)});filter.Controls.Add(query);filter.Controls.Add(state);filter.Controls.Add(Btn("Selecionar todos",()=>marketSelectAll()));layout.Controls.Add(filter,0,0);
 var market=Theme.Grid();market.MultiSelect=true;marketSelectAll=()=>market.SelectAll();market.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.None;market.Dock=DockStyle.Fill;market.ColumnHeadersHeightSizeMode=DataGridViewColumnHeadersHeightSizeMode.EnableResizing;market.ColumnHeadersHeight=48;layout.Controls.Add(market,0,1);var info=new Label{Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft};layout.Controls.Add(info,0,2);
 Action refresh=()=>{var t=db.MarketView(true);foreach(DataRow r in t.Rows.Cast<DataRow>().ToArray()){bool match=(r["Código"]+" "+r["Nome"]+" "+r["Bodega"]).IndexOf(query.Text.Trim(),StringComparison.CurrentCultureIgnoreCase)>=0;bool br=!r.IsNull("Bodega / mercado R$");if(!match||(state.SelectedIndex==1&&!br)||(state.SelectedIndex==2&&br)||(state.SelectedIndex==3&&r["Moeda"].ToString()=="BRL")||(state.SelectedIndex==4&&r["Situação"].ToString()!="Rótulo a confirmar"))t.Rows.Remove(r);}
 market.DataSource=t;market.Columns["Id"].Visible=false;market.Columns["Produto"].Visible=false;foreach(DataGridViewColumn col in market.Columns){col.Width=col.Name=="Nome"?350:col.Name=="Fonte"?260:col.Name=="Situação"?190:col.Name=="Bodega"?150:110;col.DefaultCellStyle.NullValue="—";if(col.ValueType==typeof(decimal)){col.DefaultCellStyle.Format=col.Name=="ML"?"N0":"N2";col.DefaultCellStyle.Alignment=DataGridViewContentAlignment.MiddleRight;}if(col.ValueType==typeof(DateTime))col.DefaultCellStyle.Format="dd/MM/yyyy";}
 foreach(DataGridViewRow r in market.Rows)if(r.Cells["Lucro bruto R$"].Value!=DBNull.Value&&Convert.ToDecimal(r.Cells["Lucro bruto R$"].Value)<0)r.DefaultCellStyle.ForeColor=Color.Firebrick;
 info.Text=t.Rows.Count+" rótulos • "+t.AsEnumerable().Count(r=>!r.IsNull("Bodega / mercado R$"))+" referências em reais. Resultado estimado = mercado − fornecedor − embalagem − gastos rateados − taxa − outros custos. Lucro bruto considera apenas fornecedor.\nMateriais cadastrados: R$ "+db.MaterialsPerBottle.ToString("N4")+"/garrafa. Usa a embalagem do produto, sem somar materiais novamente. Mercado não altera seu preço de venda.";};
 Func<DataRow> selected=()=>{if(market.CurrentRow==null)throw new Exception("Selecione um rótulo.");return db.Data.Tables["Mercado"].Rows.Find(market.CurrentRow.Cells["Id"].Value);};
 Action edit=()=>EditMarket(selected(),refresh);

 var buttons=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false};buttons.Controls.Add(Btn("Confirmar",()=>{var rows=market.SelectedRows.Cast<DataGridViewRow>().OrderBy(r=>r.Index).Select(r=>db.Data.Tables["Mercado"].Rows.Find(r.Cells["Id"].Value)).ToArray();db.ConfirmMarketProducts(rows);refresh();}));buttons.Controls.Add(Btn("Editar rótulo",edit));buttons.Controls.Add(Btn("Editar markup",()=>{var m=selected();MarkupEditor(db.Data.Tables["Produtos"].Rows.Find(m["Produto"]),m,refresh);}));buttons.Controls.Add(Btn("Abrir fonte",()=>{var m=selected();if(!ValidMarketUrl(m["URL"].ToString()))throw new Exception("Este rótulo ainda não tem fonte de preço confirmada.");System.Diagnostics.Process.Start(m["URL"].ToString());}));buttons.Controls.Add(Btn("Editar produto",()=>{Product(db.Data.Tables["Produtos"].Rows.Find(selected()["Produto"]));refresh();}));buttons.Controls.Add(Btn("Exportar CSV",()=>{using(var s=new SaveFileDialog{Filter="CSV|*.csv",FileName="Mercado.csv"})if(s.ShowDialog()==DialogResult.OK){var t=((DataTable)market.DataSource);var fields=t.Columns.Cast<DataColumn>().Where(c=>c.ColumnName!="Id"&&c.ColumnName!="Produto").ToArray();Func<object,string> quote=v=>"\""+Convert.ToString(v).Replace("\"","\"\"")+"\"";File.WriteAllLines(s.FileName,new[]{string.Join(";",fields.Select(c=>quote(c.ColumnName)))}.Concat(t.AsEnumerable().Select(r=>string.Join(";",fields.Select(c=>quote(r[c]))))),new UTF8Encoding(true));}}));buttons.Controls.Add(Btn("Sair",Home));foreach(Control b in buttons.Controls)b.Width=125;layout.Controls.Add(buttons,0,3);
 query.TextChanged+=(s,e)=>refresh();state.SelectedIndexChanged+=(s,e)=>refresh();market.CellDoubleClick+=(s,e)=>{if(e.RowIndex>=0)Run(edit);};refresh();
 }
 void EditMarket(DataRow m,Action refresh){var p=db.Data.Tables["Produtos"].Rows.Find(m["Produto"]);using(var d=new Dialog("Mercado • editar rótulo e referência",840,820)){
d.Fields.ColumnStyles[0].Width=180;var code=d.TextField("Código",p["Código"].ToString());var name=d.TextField("Nome do rótulo",p["Nome"].ToString());var ml=d.Number("Volume (ML)",(decimal)p["Volume ml"],100000,0);var supplier=d.TextField("Fornecedor",p["Fornecedor"].ToString());var cost=d.Number("Custo fornecedor R$",(decimal)p["Custo"]);var winery=d.TextField("Bodega / produtor",m["Bodega"].ToString());
var hint=new Label{Text="Código, nome, ML, fornecedor e custo são compartilhados com Produtos. Markup e lucro são calculados.",AutoSize=true};d.Add("Integração",hint);d.Fields.RowStyles[d.Fields.RowStyles.Count-1].Height=45;
var has=new CheckBox{Checked=!m.IsNull("Preço referência"),Text="Existe preço de referência"};d.Add("Preço disponível",has);var value=d.Number("Preço por garrafa",m.IsNull("Preço referência")?0:(decimal)m["Preço referência"]);var currency=d.Choice("Moeda",new[]{"BRL","CLP","ARS","EUR","USD"});currency.SelectedItem=m["Moeda"].ToString();var source=d.TextField("Loja / fonte",m["Fonte"].ToString());var url=d.TextField("Link da fonte",m["URL"].ToString());var status=d.Choice("Situação",new[]{"Confirmado","Indisponível na fonte","Sem preço confirmado","Rótulo a confirmar","Referência estrangeira","Simulação manual"});status.SelectedItem=m["Situação"].ToString();var date=new DateTimePicker{Format=DateTimePickerFormat.Short,Value=(DateTime)m["Consulta"]};d.Add("Data da consulta",date);var profit=new Label{AutoSize=true};d.Add("Cálculo por unidade",profit);
Action calculate=()=>{profit.Text=!has.Checked||currency.Text!="BRL"||status.Text=="Rótulo a confirmar"?"Sem comparação em reais.":"Lucro bruto: R$ "+(value.Value-cost.Value).ToString("N2")+"   |   Markup: "+(cost.Value==0?"—":((value.Value-cost.Value)/cost.Value*100).ToString("N2")+"%");};cost.ValueChanged+=(a,b)=>calculate();value.ValueChanged+=(a,b)=>calculate();has.CheckedChanged+=(a,b)=>calculate();currency.SelectedIndexChanged+=(a,b)=>calculate();status.SelectedIndexChanged+=(a,b)=>calculate();calculate();
var note=d.TextField("Observações",m["Observações"].ToString());note.Multiline=true;d.Fields.RowStyles[d.Fields.RowStyles.Count-1].Height=90;
d.Commit(()=>{db.EditMarketRecord(m,code.Text,name.Text,ml.Value,supplier.Text,cost.Value,winery.Text,has.Checked?(decimal?)value.Value:null,currency.Text,source.Text,url.Text,status.Text,date.Value,note.Text);});if(d.ShowDialog(this)==DialogResult.OK)refresh();}}
 static bool ValidMarketUrl(string value){Uri uri;return Uri.TryCreate(value,UriKind.Absolute,out uri)&&(uri.Scheme=="https"||uri.Scheme=="http");}
}
}
