using System;using System.Data;using System.IO;using System.Windows.Forms;
namespace Videira {
partial class Store {
 public static decimal PriceForMarkup(decimal cost,decimal markup){if(cost<=0)throw new Exception("Informe um custo do fornecedor maior que zero para calcular o markup.");if(markup<=-100||markup>100000)throw new Exception("Informe markup maior que -100% e até 100.000%.");return Money(cost*(1+markup/100));}
 public void ApplyMarkup(DataRow product,DataRow market,decimal markup){decimal price=PriceForMarkup((decimal)product["Custo"],markup);if(price<=0)throw new Exception("O preço calculado deve ser maior que zero.");if(market!=null&&market["Moeda"].ToString()!="BRL")throw new Exception("Use uma referência em reais para editar o markup contra o custo do fornecedor.");
 Atomic(()=>{if(market==null){product["Preço"]=price;product["Precificação automática"]="Não";}else{if(market["Situação"].ToString()!="Simulação manual")market["Observações"]="Referência anterior: "+(market.IsNull("Preço referência")?"sem preço":Convert.ToDecimal(market["Preço referência"]).ToString("N2")+" "+market["Moeda"])+"; fonte: "+market["Fonte"]+"; link: "+market["URL"]+".\r\n"+market["Observações"];market["Preço referência"]=price;market["Fonte"]="Simulação manual por markup";market["URL"]="";market["Situação"]="Simulação manual";market["Consulta"]=DateTime.Today;market["Editado pelo usuário"]=true;}});}
}
partial class MainForm {
 void MarkupEditor(DataRow product,DataRow market,Action refresh){decimal cost=(decimal)product["Custo"];if(cost<=0)throw new Exception("Edite o produto e informe o custo do fornecedor antes de definir o markup.");if(market!=null&&market["Moeda"].ToString()!="BRL")throw new Exception("A referência está em moeda estrangeira. Selecione BRL em Editar rótulo para calcular contra o custo em reais.");decimal price=market==null?(decimal)product["Preço"]:market.IsNull("Preço referência")?cost:(decimal)market["Preço referência"];
 using(var d=new Dialog("Editar markup • "+product["Nome"],700,390)){d.Add("Custo fornecedor R$",new Label{Text=cost.ToString("N2"),AutoSize=true});var markup=d.Number("Markup sobre custo %",0,100000,2);markup.Minimum=-99.99m;markup.Value=Math.Min(100000,Math.Max(-99.99m,Store.Money((price-cost)/cost*100)));var result=new Label{AutoSize=true};d.Add("Preço calculado R$",result);var profit=new Label{AutoSize=true};d.Add("Lucro bruto R$",profit);var hint=new Label{Text=market==null?"Ao salvar, atualiza o preço de venda e usa precificação manual. Embalagem, taxas e despesas não estão incluídas neste cálculo.":"Ao salvar, cria uma referência manual em Mercado. A fonte anterior fica nas observações. O preço de venda do produto permanece igual.",AutoSize=true};d.Add("Aplicação",hint);d.Fields.RowStyles[d.Fields.RowStyles.Count-1].Height=90;Action calculate=()=>{decimal p=Store.PriceForMarkup(cost,markup.Value);result.Text=p.ToString("N2");profit.Text=(p-cost).ToString("N2");};markup.ValueChanged+=(s,e)=>calculate();calculate();d.Commit(()=>db.ApplyMarkup(product,market,markup.Value));if(d.ShowDialog(this)==DialogResult.OK)refresh();}}
}
static class MarkupTests {
public static void Run(){if(Store.PriceForMarkup(50m,30m)!=65m||Store.PriceForMarkup(50m,-20m)!=40m)throw new Exception("Preço por markup");bool failed=false;try{Store.PriceForMarkup(0,20);}catch{failed=true;}if(!failed)throw new Exception("Custo zero");var db=new Store(Path.Combine(Environment.CurrentDirectory,"work","Markup-"+Guid.NewGuid()));db.ImportPortfolio();var m=db.Data.Tables["Mercado"].Rows[0];var p=db.Data.Tables["Produtos"].Rows.Find(m["Produto"]);p["Custo"]=50m;p["Preço"]=70m;p["Estoque"]=7m;db.ApplyMarkup(p,null,30m);if((decimal)p["Preço"]!=65m||p["Precificação automática"].ToString()!="Não")throw new Exception("Markup estoque");db.ApplyMarkup(p,m,60m);if((decimal)m["Preço referência"]!=80m||(decimal)p["Preço"]!=65m||(decimal)p["Estoque"]!=7m||m["Situação"].ToString()!="Simulação manual")throw new Exception("Markup Mercado independente");if(db.FillMissingMarketReferences()!=0)throw new Exception("Preservar markup manual");File.AppendAllText(Path.Combine(Environment.CurrentDirectory,"work","test-result.txt"),"\r\nPASS 2.5: markup editável, preço por custo, negativo, custo zero, estoque, simulação de mercado independente e preservação de referência manual.");}
}
}
