using System;
using System.Data;
using System.Linq;
namespace Videira { partial class Store {
 public void SetCartItem(DataTable cart,DataRow existing,DataRow product,decimal quantity,decimal original,decimal discount){
  if(product==null||product["Ativo"].ToString()!="Sim")throw new Exception("Selecione um produto ativo.");if(quantity<=0||quantity!=Math.Truncate(quantity))throw new Exception("A quantidade deve ser inteira e maior que zero.");if(original<0||discount<0||discount>100)throw new Exception("Informe preço válido e desconto entre 0 e 100%.");decimal others=cart.AsEnumerable().Where(r=>r!=existing&&(int)r["Produto"]==(int)product["Id"]).Sum(r=>(decimal)r["Quantidade"]);if(others+quantity>(decimal)product["Estoque"])throw new Exception("Estoque insuficiente. Disponível: "+product["Estoque"]+" unidade(s).");decimal net=Money(original*(1-discount/100));var row=existing??cart.NewRow();row["Produto"]=product["Id"];row["Código"]=product["Código"];row["Descrição"]=product["Nome"];row["Quantidade"]=quantity;row["Preço original"]=original;row["Desconto %"]=discount;row["Preço"]=net;row["Total"]=Money(quantity*net);if(existing==null)cart.Rows.Add(row);
 }
 public decimal FutureExpenses(DateTime after){return Data.Tables["Despesas"].AsEnumerable().Where(r=>(DateTime)r["Data"]>after.Date).Sum(r=>(decimal)r["Valor"]);}
 public DataTable PeriodRows(string table,DateTime start,DateTime end){var t=Data.Tables[table].Clone();foreach(DataRow row in Data.Tables[table].Rows)if((DateTime)row["Data"]>=start.Date&&(DateTime)row["Data"]<end.Date.AddDays(1))t.ImportRow(row);return t;}
 public int GenerateMonth(DateTime month){int count=0;Atomic(()=>{foreach(DataRow plan in Data.Tables["Plano mensal"].Rows){bool exists=Data.Tables["Despesas"].AsEnumerable().Any(existing=>((int)existing["Plano mensal"]==(int)plan["Id"]||((int)existing["Plano mensal"]==0&&existing["Descrição"].ToString().Equals(plan["Descrição"].ToString(),StringComparison.CurrentCultureIgnoreCase)&&existing["Categoria"].ToString()==plan["Categoria"].ToString()))&&((DateTime)existing["Data"]).Year==month.Year&&((DateTime)existing["Data"]).Month==month.Month);if(exists)continue;var r=Data.Tables["Despesas"].NewRow();r["Id"]=Next("Despesas");r["Data"]=new DateTime(month.Year,month.Month,Math.Min((int)plan["Dia do mês"],DateTime.DaysInMonth(month.Year,month.Month)));r["Categoria"]=plan["Categoria"];r["Descrição"]=plan["Descrição"];r["Valor"]=plan["Valor"];r["Plano mensal"]=plan["Id"];Data.Tables["Despesas"].Rows.Add(r);count++;}});return count;}
 public DataTable BestProducts(DateTime from,DateTime to){var sales=Data.Tables["Vendas"].AsEnumerable().Where(r=>r["Situação"].ToString()=="Concluída"&&(DateTime)r["Data"]>=from.Date&&(DateTime)r["Data"]<to.Date.AddDays(1)).Select(r=>(int)r["Id"]).ToArray();var t=new DataTable();t.Columns.Add("Produto");t.Columns.Add("Unidades",typeof(decimal));t.Columns.Add("Vendas R$",typeof(decimal));t.Columns.Add("Resultado antes da taxa R$",typeof(decimal));foreach(var g in Data.Tables["Itens"].AsEnumerable().Where(r=>sales.Contains((int)r["Venda"])).GroupBy(r=>r["Nome"].ToString()).OrderByDescending(g=>g.Sum(r=>(decimal)r["Total"]))){t.Rows.Add(g.Key,g.Sum(r=>(decimal)r["Quantidade"]),g.Sum(r=>(decimal)r["Total"]),g.Sum(r=>(decimal)r["Total"]-(decimal)r["Quantidade"]*((decimal)r["Custo"]+(decimal)r["Embalagem unitária"])-(decimal)r["Outras despesas"]));}return t;}
}}


