using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
namespace Videira {
partial class MainForm {
 void Product(DataRow product){using(var d=new Dialog("Cadastro de Produtos • VIDEIRA GESTÃO",1050,Math.Min(830,Screen.PrimaryScreen.WorkingArea.Height-30))){
  d.Fields.Visible=false;d.AutoScaleMode=AutoScaleMode.None;d.MinimumSize=new Size(920,620);d.Size=new Size(Math.Min(1100,Screen.PrimaryScreen.WorkingArea.Width-40),Math.Min(860,Screen.PrimaryScreen.WorkingArea.Height-40));var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2};root.RowStyles.Add(new RowStyle(SizeType.Absolute,40));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));d.Controls.Add(root);root.BringToFront();
  var title=new Label{Dock=DockStyle.Fill,Text=product==null?"NOVO PRODUTO":product["Nome"].ToString(),BackColor=Color.FromArgb(211,220,231),ForeColor=Color.FromArgb(47,73,109),Padding=new Padding(14,10,0,0),Font=new Font(Theme.Font,FontStyle.Bold),AutoEllipsis=true};root.Controls.Add(title,0,0);
  var tabs=new TabControl{Dock=DockStyle.Fill,Padding=new Point(16,7)};root.Controls.Add(tabs,0,1);var pages=new[]{new TabPage("Principal"),new TabPage("Custos e preço"),new TabPage("Estoque e observações")};foreach(var p in pages){p.BackColor=Theme.Surface;p.AutoScroll=true;p.Padding=new Padding(10);tabs.TabPages.Add(p);}
  var fields=new Dictionary<string,Control>();
  Func<string,string> text=name=>product==null?"":Convert.ToString(product[name]);Func<string,decimal> num=name=>product==null?(name=="Embalagem unitária"||name=="Unidades por caixa"?1m:name=="Margem desejada %"?(decimal)db.Company["Margem padrão"]:0m):(decimal)product[name];
  Func<string,Control> tx=name=>{var c=new TextBox{Text=text(name)};fields[name]=c;return c;};Func<string,int,Control> nm=(name,dec)=>{var c=new NumericUpDown{Maximum=100000000,DecimalPlaces=dec,ThousandsSeparator=true,Value=num(name)};fields[name]=c;return c;};
  Func<TabPage,string,int,int,GroupBox> group=(p,titleText,y,h)=>{var box=new GroupBox{Text=titleText,Location=new Point(12,y),Size=new Size(988,h)};p.Controls.Add(box);return box;};
  var codes=group(pages[0],"Codificação e situação",12,96);Theme.LabelField(codes,"Código *",tx("Código"),14,24,145);Theme.LabelField(codes,"EAN / código de barras",tx("EAN"),174,24,224);Theme.LabelField(codes,"EAN da caixa",tx("EAN Caixa"),414,24,224);Theme.LabelField(codes,"Código de fábrica",tx("Código fábrica"),654,24,145);var active=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList};active.Items.AddRange(new[]{"Sim","Não"});active.SelectedItem=product==null?"Sim":product["Ativo"].ToString();fields["Ativo"]=active;Theme.LabelField(codes,"Ativo",active,815,24,155);
  var desc=group(pages[0],"Descrição",118,96);var productName=tx("Nome");Theme.LabelField(desc,"Descrição / nome do produto *",productName,14,24,500);Theme.LabelField(desc,"Abreviação",tx("Abreviação"),530,24,280);Theme.LabelField(desc,"Sigla",tx("Sigla"),826,24,144);productName.TextChanged+=(s,e)=>title.Text=string.IsNullOrWhiteSpace(productName.Text)?"NOVO PRODUTO":productName.Text;
  var classification=group(pages[0],"Classificação e fornecedor",224,166);string[] cls={"Linha","Grupo","Subgrupo","Família","Marca","Fabricante"};for(int i=0;i<cls.Length;i++)Theme.LabelField(classification,cls[i],tx(cls[i]),14+(i%3)*322,22+(i/3)*54,306);var supplier=new ComboBox{DropDownStyle=ComboBoxStyle.DropDown,Text=text("Fornecedor")};supplier.Items.AddRange(db.Data.Tables["Fornecedores"].AsEnumerable().Select(r=>r["Nome"].ToString()).ToArray());fields["Fornecedor"]=supplier;Theme.LabelField(classification,"Fornecedor",supplier,14,130,950);classification.Height=196;
  var specs=group(pages[0],"Especificações",430,96);var unit=tx("Unidade");if(product==null)unit.Text="UN";Theme.LabelField(specs,"Unidade de medida",unit,14,24,180);var type=tx("Tipo embalagem");if(product==null)type.Text="Garrafa";Theme.LabelField(specs,"Tipo de embalagem",type,210,24,260);Theme.LabelField(specs,"Unidades por caixa",nm("Unidades por caixa",0),486,24,224);Theme.LabelField(specs,"Volume (ml)",nm("Volume ml",0),726,24,244);
  var wine=group(pages[0],"Detalhes do vinho (usados no orçamento)",536,153);string[] wineKeys={"Tipo de vinho","Uva","Safra","País","Região"};for(int i=0;i<wineKeys.Length;i++)Theme.LabelField(wine,wineKeys[i],tx(wineKeys[i]),14+(i%3)*322,24+(i/3)*58,306);
  var prices=group(pages[1],"Custos do produto",12,100);Theme.LabelField(prices,"Custo do fornecedor (R$)",nm("Custo",2),14,24,300);Theme.LabelField(prices,"Embalagem por garrafa R$",nm("Embalagem unitária",2),338,24,300);Theme.LabelField(prices,"Outros custos por unidade (R$)",nm("Outros custos unitários",2),662,24,308);
  var percentages=group(pages[1],"Margem e despesas incluídas no preço",122,100);var margin=(NumericUpDown)nm("Margem desejada %",2);margin.Maximum=99.99m;Theme.LabelField(percentages,"Margem desejada sobre a venda (%)",margin,14,24,300);var variable=(NumericUpDown)nm("Despesa variável %",2);variable.Maximum=99.99m;Theme.LabelField(percentages,"Outras despesas sobre a venda (%)",variable,338,24,300);var rateMode=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList};rateMode.Items.AddRange(new[]{"Dinheiro","Pix"}.Concat(db.Data.Tables["Taxas"].AsEnumerable().Select(r=>r["Modalidade"].ToString())).ToArray());rateMode.SelectedItem=product==null?(db.Company["Taxas Stone importadas"].ToString()=="Sim"?"Crédito VISA/MASTER 1x • Stone":db.Company["Taxas somente 1x"].ToString()=="Sim"?"Crédito VISA/MASTER 1x":"Crédito à vista"):product["Taxa padrão"].ToString();if(rateMode.SelectedIndex<0)rateMode.SelectedIndex=0;fields["Taxa padrão"]=rateMode;Theme.LabelField(percentages,"Pagamento de referência",rateMode,662,24,308);
  var strategy=group(pages[1],"Formação do preço e resultado por garrafa",232,165);var overhead=Theme.Readonly("");var card=Theme.Readonly("");var profit=Theme.Readonly("");Theme.LabelField(strategy,"Gastos mensais distribuídos (R$)",overhead,14,24,300);Theme.LabelField(strategy,"Taxa embutida no preço (R$)",card,338,24,300);Theme.LabelField(strategy,"Lucro estimado por unidade (R$)",profit,662,24,308);var explanation=new Label{Location=new Point(14,93),Size=new Size(956,59),ForeColor=Color.DimGray};strategy.Controls.Add(explanation);
  var final=group(pages[1],"Preço final e controle",407,120);var auto=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList};auto.Items.AddRange(new[]{"Sim","Não"});auto.SelectedItem=product==null?"Sim":product["Precificação automática"].ToString();fields["Precificação automática"]=auto;Theme.LabelField(final,"Calcular preço automaticamente",auto,14,24,300);var salePrice=(NumericUpDown)nm("Preço",2);Theme.LabelField(final,"Preço final salvo (R$)",salePrice,338,24,300);var markup=Theme.Readonly("");Theme.LabelField(final,"Markup sobre compra (%)",markup,662,24,308);
  Action calc=()=>{salePrice.Enabled=auto.Text!="Sim";try{var calculated=db.Calculate(((NumericUpDown)fields["Custo"]).Value,((NumericUpDown)fields["Embalagem unitária"]).Value,((NumericUpDown)fields["Outros custos unitários"]).Value,variable.Value,margin.Value,db.Rate(rateMode.Text));if(auto.Text=="Sim")salePrice.Value=calculated.Price;decimal price=salePrice.Value,cost=((NumericUpDown)fields["Custo"]).Value;decimal distributed=calculated.Overhead;if(db.Company["Rateio"].ToString()=="Por faturamento"&&(decimal)db.Company["Faturamento mês"]>0)distributed=price*db.MonthlyPlan/(decimal)db.Company["Faturamento mês"];overhead.Text=distributed.ToString("N2");card.Text=(price*calculated.Rate/100).ToString("N2");profit.Text=Store.Money(price-calculated.Base-distributed-price*(variable.Value+calculated.Rate)/100).ToString("N2");markup.Text=cost==0?"—":((price-cost)/cost*100).ToString("N2");explanation.Text="Preço sugerido: R$ "+calculated.Price.ToString("N2")+". Meta: "+margin.Value.ToString("N2")+"% de margem após os custos configurados.\nMateriais cadastrados: R$ "+db.MaterialsPerBottle.ToString("N4")+"/garrafa. O valor do campo embalagem substitui esse custo; não somar novamente.";}catch(Exception ex){overhead.Text=card.Text=profit.Text="—";explanation.Text=ex.Message;}};
  foreach(string key in new[]{"Custo","Embalagem unitária","Outros custos unitários","Despesa variável %","Margem desejada %","Preço"})((NumericUpDown)fields[key]).ValueChanged+=(s,e)=>calc();rateMode.SelectedIndexChanged+=(s,e)=>calc();auto.SelectedIndexChanged+=(s,e)=>calc();calc();
  var location=group(pages[1],"Armazenamento",537,100);Theme.LabelField(location,"Local de armazenagem",tx("Localização"),14,24,622);Theme.LabelField(location,"Fileira / prateleira",tx("Prateleira"),654,24,316);
  var inventory=group(pages[2],"Estoque e cadastro",12,100);var stock=nm("Estoque",0);stock.Enabled=true;stock.BackColor=Color.White;Theme.LabelField(inventory,product==null?"Estoque inicial (un.)":"Quantidade em estoque (un.)",stock,14,24,300);Theme.LabelField(inventory,"Estoque mínimo (un.)",nm("Estoque mínimo",0),338,24,300);Theme.LabelField(inventory,"Data de cadastro",Theme.Readonly(product==null?DateTime.Today.ToString("dd/MM/yyyy"):((DateTime)product["Cadastro"]).ToString("dd/MM/yyyy")),662,24,308);
  var other=group(pages[2],"Peso e validade",122,100);Theme.LabelField(other,"Peso líquido (kg)",nm("Peso líquido",3),14,24,300);Theme.LabelField(other,"Peso bruto (kg)",nm("Peso bruto",3),338,24,300);Theme.LabelField(other,"Validade (dias)",nm("Validade dias",0),662,24,308);
  var notes=group(pages[2],"Observações",232,220);var note=(TextBox)tx("Observações");note.Multiline=true;note.ScrollBars=ScrollBars.Vertical;note.Location=new Point(14,28);note.Size=new Size(956,175);notes.Controls.Add(note);
  pages[2].Controls.Add(new Label{Text="Altere a quantidade e clique em Salvar. A diferença será registrada como ajuste nas movimentações de estoque.",Location=new Point(18,470),Size=new Size(960,48),ForeColor=Color.DimGray});
  d.Commit(()=>{if(auto.Text=="Sim"){var validated=db.Calculate(((NumericUpDown)fields["Custo"]).Value,((NumericUpDown)fields["Embalagem unitária"]).Value,((NumericUpDown)fields["Outros custos unitários"]).Value,variable.Value,margin.Value,db.Rate(rateMode.Text));salePrice.Value=validated.Price;}if(string.IsNullOrWhiteSpace(fields["Código"].Text)||string.IsNullOrWhiteSpace(productName.Text))throw new Exception("Informe código e descrição.");if(db.Data.Tables["Produtos"].AsEnumerable().Any(r=>r!=product&&string.Equals(r["Código"].ToString(),fields["Código"].Text.Trim(),StringComparison.OrdinalIgnoreCase)))throw new Exception("Código já cadastrado.");db.Atomic(()=>{var r=product??db.Data.Tables["Produtos"].NewRow();if(product==null){r["Id"]=db.Next("Produtos");r["Cadastro"]=DateTime.Today;}decimal oldStock=product==null?0m:(decimal)r["Estoque"];foreach(var field in fields){if(field.Key=="Estoque"&&product!=null)continue;r[field.Key]=field.Value is NumericUpDown?(object)((NumericUpDown)field.Value).Value:field.Value.Text.Trim();}if(product==null){db.Data.Tables["Produtos"].Rows.Add(r);if((decimal)r["Estoque"]>0)db.Move(r,(decimal)r["Estoque"],"Inicial","Cadastro do produto");}else db.AdjustProductStock(r,((NumericUpDown)stock).Value);});});
  foreach(TabPage tab in pages){foreach(GroupBox box in tab.Controls.OfType<GroupBox>()){box.BackColor=Color.White;box.ForeColor=Color.FromArgb(47,73,109);foreach(Control field in box.Controls){field.ForeColor=Color.FromArgb(35,42,51);if(field is Label)field.Font=new Font(Theme.Font.FontFamily,9.5f,FontStyle.Regular);}var bounds=box.Controls.Cast<Control>().ToDictionary(c=>c,c=>c.Bounds);Action fit=()=>{int width=Math.Max(840,tab.ClientSize.Width-40);box.Width=width;foreach(var pair in bounds){Rectangle b=pair.Value;pair.Key.Bounds=new Rectangle((int)(b.X*width/988.0),b.Y,(int)(b.Width*width/988.0),b.Height);}};tab.SizeChanged+=(sender,args)=>fit();fit();}tab.AutoScrollMinSize=new Size(0,tab.Controls.Cast<Control>().Max(c=>c.Bottom)+18);}title.TextAlign=ContentAlignment.MiddleLeft;title.Padding=new Padding(16,0,12,0);title.BackColor=Color.FromArgb(226,235,245);tabs.Font=new Font(Theme.Font.FontFamily,10f);d.Shown+=(sender,args)=>{foreach(TabPage tab in pages)foreach(GroupBox box in tab.Controls.OfType<GroupBox>())box.Invalidate();};
  if(preview){d.Shown+=(s,e)=>{if(previewTab==1)tabs.SelectedIndex=1;if(previewTab==2)tabs.SelectedIndex=2;if(activePreviewMode=="--preview-product-flow"){fields["Código"].Text="UI-"+db.Next("Produtos");productName.Text="VINHO DE TESTE DA INTERFACE";((NumericUpDown)fields["Custo"]).Value=50;((Button)d.AcceptButton).PerformClick();}};}
  if(d.ShowDialog(this)==DialogResult.OK&&(page=="Produtos"||page=="Inventário"))RefreshGrid();
 }}
}
}
