using System;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
using System.Diagnostics;
namespace Videira {
partial class MainForm {
 void QuotesPage(){page="Orçamentos";Header("Comercial • Gestão de Orçamentos");var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(14),RowCount=3,ColumnCount=1};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,65));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,54));content.Controls.Add(layout);layout.BringToFront();var top=new FlowLayoutPanel{Dock=DockStyle.Fill};top.Controls.Add(new Label{Text="Pesquisar cliente ou número:",AutoSize=true,Margin=new Padding(0,10,8,0)});var find=new TextBox{Width=390};top.Controls.Add(find);layout.Controls.Add(top,0,0);var g=Theme.Grid();g.Dock=DockStyle.Fill;layout.Controls.Add(g,0,1);Action refresh=()=>{var t=db.Data.Tables["Orçamentos"].Copy();string q=find.Text.Trim();foreach(DataRow r in t.Rows.Cast<DataRow>().ToArray())if(q!=""&&!r["Cliente"].ToString().ToLower().Contains(q.ToLower())&&!r["Id"].ToString().Contains(q))t.Rows.Remove(r);g.DataSource=t;foreach(string c in new[]{"Mensagem","Observações","Venda","Taxa %"})g.Columns[c].Visible=false;g.Columns["Id"].HeaderText="Número";g.Columns["Cliente"].FillWeight=220;g.Columns["Data"].DefaultCellStyle.Format="dd/MM/yyyy";g.Columns["Validade"].DefaultCellStyle.Format="dd/MM/yyyy";g.Columns["Total"].DefaultCellStyle.Format="N2";};find.TextChanged+=(s,e)=>refresh();Func<DataRow> selected=()=>{if(g.CurrentRow==null)throw new Exception("Selecione um orçamento.");return db.Data.Tables["Orçamentos"].Rows.Find(g.CurrentRow.Cells["Id"].Value);};var actions=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false,Padding=new Padding(0,6,0,0)};layout.Controls.Add(actions,0,2);var create=Btn("Novo orçamento",()=>{QuoteForm();refresh();});create.Width=180;actions.Controls.Add(create);var message=Btn("Texto WhatsApp",()=>QuoteText(selected()));message.Width=180;actions.Controls.Add(message);var sale=Btn("Confirmar venda",()=>{var r=selected();string warning=(DateTime)r["Validade"]<DateTime.Today?"Este orçamento venceu. ":"";if(MessageBox.Show(warning+"Confirmar o orçamento nº "+r["Id"]+" como venda e baixar o estoque?","Confirmar venda",MessageBoxButtons.YesNo)==DialogResult.Yes){int id=db.ConvertQuote((int)r["Id"]);MessageBox.Show("Venda nº "+id+" registrada.");refresh();}});sale.Width=180;actions.Controls.Add(sale);var cancel=Btn("Cancelar",()=>{var r=selected();if(r["Situação"].ToString()!="Aberto")throw new Exception("Somente orçamentos abertos podem ser cancelados.");if(MessageBox.Show("Cancelar este orçamento?","Cancelar",MessageBoxButtons.YesNo)==DialogResult.Yes){db.Atomic(()=>r["Situação"]="Cancelado");refresh();}});actions.Controls.Add(cancel);actions.Controls.Add(Btn("Sair",Home));refresh();}
 void QuoteText(DataRow quote){using(var d=new Dialog("Mensagem para WhatsApp • Orçamento nº "+quote["Id"],900,740)){d.Fields.Visible=false;var text=new TextBox{Dock=DockStyle.Fill,Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Vertical,Text=quote["Mensagem"].ToString(),BackColor=Color.White,Font=new Font("Segoe UI",11)};d.Controls.Add(text);text.BringToFront();var close=Btn("Sair",()=>d.Close());d.Buttons.Controls.Add(close);var copy=Btn("Copiar mensagem",()=>{Clipboard.SetText(text.Text);MessageBox.Show("Mensagem copiada. Cole na conversa do cliente no WhatsApp.");});copy.Width=190;d.Buttons.Controls.Add(copy);var whatsapp=Btn("Abrir WhatsApp",()=>{string number=new string(quote["Telefone"].ToString().Where(char.IsDigit).ToArray());if(number.Length==10||number.Length==11)number="55"+number;if(number!=""&&(number.Length<12||number.Length>15))throw new Exception("Verifique o WhatsApp do cliente com DDD.");string uri="https://wa.me/"+number+"?text="+Uri.EscapeDataString(text.Text);if(uri.Length>6500){Clipboard.SetText(text.Text);MessageBox.Show("Mensagem longa copiada. Cole diretamente no WhatsApp.");return;}Process.Start(new ProcessStartInfo(uri){UseShellExecute=true});});whatsapp.Width=190;d.Buttons.Controls.Add(whatsapp);d.ShowDialog(this);}}
}
}
