using System;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
namespace Videira { partial class MainForm {
 void Sale(){using(var d=new Dialog("Lançamento de Venda • VIDEIRA GESTÃO",1120,880)){
 d.Fields.Visible=false;var tabs=new TabControl{Dock=DockStyle.Fill};var main=new TabPage("Principal"){BackColor=Theme.Surface,Padding=new Padding(12)};tabs.TabPages.Add(main);d.Controls.Add(tabs);tabs.BringToFront();
 var layout=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=5};layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));foreach(float h in new[]{145f,115f})layout.RowStyles.Add(new RowStyle(SizeType.Absolute,h));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,150));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,28));main.Controls.Add(layout);
 var head=new Panel{Dock=DockStyle.Fill};layout.Controls.Add(head,0,0);Theme.LabelField(head,"Número",Theme.Readonly(db.Next("Vendas").ToString("D6")),0,0,140);Theme.LabelField(head,"Data / hora",Theme.Readonly(DateTime.Now.ToString("dd/MM/yyyy HH:mm")),154,0,215);Theme.LabelField(head,"Situação",Theme.Readonly("EM LANÇAMENTO"),805,0,240);
 var clientCode=new TextBox();Theme.LabelField(head,"Cliente (opcional)",clientCode,0,48,140);var clientName=Theme.Readonly("Consumidor");clientName.Location=new Point(205,70);clientName.Size=new Size(640,28);head.Controls.Add(clientName);Action chooseClient=()=>{var c=ClientLookup();if(c!=null){clientCode.Text=c["Id"].ToString();clientName.Text=c["Nome"].ToString();}};var clientSearch=Btn("Consultar",chooseClient);clientSearch.Location=new Point(857,65);clientSearch.Size=new Size(188,32);head.Controls.Add(clientSearch);clientCode.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Enter){e.SuppressKeyPress=true;Run(()=>{if(clientCode.Text.Trim()==""){clientName.Text="Consumidor";return;}var c=db.Data.Tables["Clientes"].Rows.Find(int.Parse(clientCode.Text));if(c==null)throw new Exception("Cliente não encontrado. Use Consultar.");clientName.Text=c["Nome"].ToString();});}};
 var pay=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList};pay.Items.AddRange(new[]{"Dinheiro","Pix"}.Concat(db.Data.Tables["Taxas"].AsEnumerable().Select(r=>r["Modalidade"].ToString())).Distinct().ToArray());pay.SelectedIndex=0;pay.Location=new Point(205,108);pay.Size=new Size(490,28);head.Controls.Add(pay);head.Controls.Add(new Label{Text="Forma de pagamento:",Location=new Point(0,111),AutoSize=true});var rate=Theme.Readonly("0,00 %");rate.Location=new Point(857,108);rate.Size=new Size(188,28);head.Controls.Add(rate);head.Controls.Add(new Label{Text="Taxa maquininha:",Location=new Point(708,111),AutoSize=true});
 var strip=new Panel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(232,234,237),BorderStyle=BorderStyle.FixedSingle};layout.Controls.Add(strip,0,1);var code=new TextBox();Theme.LabelField(strip,"Produto",code,8,5,125);var stock=Theme.Readonly("0");Theme.LabelField(strip,"Estoque",stock,190,5,95);var qty=new EntryNumber{Minimum=1,Maximum=100000000,Value=1};Theme.LabelField(strip,"Quantidade",qty,297,5,116);var price=new EntryNumber{Maximum=100000000,DecimalPlaces=2};Theme.LabelField(strip,"Valor unitário",price,425,5,143);var discount=new EntryNumber{Maximum=100,DecimalPlaces=2};Theme.LabelField(strip,"Desc. %",discount,580,5,99);var lineTotal=Theme.Readonly("0,00");Theme.LabelField(strip,"Valor total",lineTotal,691,5,105);var description=Theme.Readonly("Consulte um produto pela lupa ou digite seu código.");description.Location=new Point(8,75);description.Size=new Size(850,28);strip.Controls.Add(description);DataRow selected=null;DataRow editing=null;Button add=null;Action reset=null;
 var cart=new DataTable();cart.Columns.Add("Produto",typeof(int));cart.Columns.Add("Código");cart.Columns.Add("Descrição");cart.Columns.Add("Quantidade",typeof(decimal));cart.Columns.Add("Preço original",typeof(decimal));cart.Columns.Add("Desconto %",typeof(decimal));cart.Columns.Add("Preço",typeof(decimal));cart.Columns.Add("Total",typeof(decimal));var grid=Theme.Grid();grid.BindingContext=new BindingContext();grid.DataSource=cart;grid.Columns["Produto"].Visible=false;grid.Columns["Preço"].Visible=false;grid.Columns["Descrição"].FillWeight=350;grid.Columns["Preço original"].HeaderText="Valor unitário";grid.Columns["Total"].HeaderText="Valor total";foreach(DataGridViewColumn col in grid.Columns)if(col.ValueType==typeof(decimal)){col.DefaultCellStyle.Format=col.Name=="Quantidade"?"N0":"N2";col.DefaultCellStyle.Alignment=DataGridViewContentAlignment.MiddleRight;}grid.Dock=DockStyle.Fill;layout.Controls.Add(grid,0,2);
 var bottom=new Panel{Dock=DockStyle.Fill};layout.Controls.Add(bottom,0,3);var units=Theme.Readonly("0");Theme.LabelField(bottom,"Unidades",units,0,5,100);var supplier=Theme.Readonly("0,00");Theme.LabelField(bottom,"Fornecedor R$",supplier,112,5,230);var pack=Theme.Readonly("0,00");Theme.LabelField(bottom,"Embalagem R$",pack,354,5,210);var extras=Theme.Readonly("0,00");Theme.LabelField(bottom,"Outros custos R$",extras,576,5,215);var fee=Theme.Readonly("0,00");Theme.LabelField(bottom,"Taxa Stone R$",fee,803,5,242);
 var overhead=Theme.Readonly("0,00");Theme.LabelField(bottom,"Gastos mensais rateados R$",overhead,0,63,275);var allCosts=Theme.Readonly("0,00");Theme.LabelField(bottom,"Total dos custos R$",allCosts,287,63,220);var result=Theme.Readonly("0,00");Theme.LabelField(bottom,"Lucro estimado R$",result,519,63,250);var total=Theme.Readonly("0,00");Theme.LabelField(bottom,"Total da venda R$",total,781,63,264);total.Font=new Font(Theme.Font,FontStyle.Bold);total.BackColor=Color.FromArgb(222,235,248);result.Font=new Font(Theme.Font,FontStyle.Bold);var allocation=new Label{Location=new Point(0,122),Size=new Size(1045,27),AutoEllipsis=true,ForeColor=Color.DimGray};bottom.Controls.Add(allocation);var hint=new ToolTip();layout.Controls.Add(new Label{Text="Enter: quantidade → preço → desconto → adicionar    |    F2: consultar produto",Dock=DockStyle.Fill,ForeColor=Color.FromArgb(53,72,93)},0,4);
 decimal percent=0;Action totals=()=>{decimal sum=cart.AsEnumerable().Sum(r=>(decimal)r["Total"]),qTotal=cart.AsEnumerable().Sum(r=>(decimal)r["Quantidade"]),packaging=0,cost=0,other=0;foreach(DataRow row in cart.Rows){var p=db.Data.Tables["Produtos"].Rows.Find(row["Produto"]);decimal q=(decimal)row["Quantidade"];packaging+=Store.Money(q*(decimal)p["Embalagem unitária"]);cost+=Store.Money(q*(decimal)p["Custo"]);other+=Store.Money(q*(decimal)p["Outros custos unitários"]+(decimal)row["Total"]*(decimal)p["Despesa variável %"]/100);}units.Text=qTotal.ToString("N0");supplier.Text=cost.ToString("N2");pack.Text=packaging.ToString("N2");extras.Text=other.ToString("N2");decimal cardFee=Store.Money(sum*percent/100);fee.Text=cardFee.ToString("N2");total.Text=sum.ToString("N2");try{decimal factor=db.SaleAllocationFactor(qTotal,sum),allocated=db.MonthlyPlan*factor;decimal complete=cost+packaging+other+cardFee+allocated;overhead.Text=Store.Money(allocated).ToString("N2");allCosts.Text=Store.Money(complete).ToString("N2");decimal profit=Store.Money(sum-complete);result.Text=profit.ToString("N2");result.ForeColor=profit<0?Color.Firebrick:Color.SeaGreen;string breakdown=string.Join(" • ",db.Data.Tables["Plano mensal"].AsEnumerable().Select(p=>p["Descrição"]+": R$ "+Store.Money((decimal)p["Valor"]*factor).ToString("N2")));allocation.Text=breakdown==""?"Sem gastos mensais cadastrados no planejamento.":"Rateio: "+breakdown;hint.SetToolTip(allocation,allocation.Text+"\nEstimativa por venda; o financeiro desconta os gastos efetivamente lançados no período.");}catch(Exception ex){overhead.Text=allCosts.Text=result.Text="—";allocation.Text=ex.Message;}};
 Action line=()=>lineTotal.Text=Store.Money(qty.Value*Store.Money(price.Value*(1-discount.Value/100))).ToString("N2");qty.ValueChanged+=(s,e)=>line();price.ValueChanged+=(s,e)=>line();discount.ValueChanged+=(s,e)=>line();Action<DataRow> select=p=>{if(p==null)return;selected=p;code.Text=p["Código"].ToString();description.Text=p["Nome"].ToString();stock.Text=((decimal)p["Estoque"]).ToString("N0");price.Value=p["Precificação automática"].ToString()=="Sim"?db.SellingPrice(p):(decimal)p["Preço"];qty.Value=1;discount.Value=0;line();qty.FocusValue();};Action lookup=()=>select(ProductLookup());var lupa=Btn("🔎",lookup);lupa.Text="";lupa.Image=Theme.Icon("search");lupa.Location=new Point(139,27);lupa.Size=new Size(39,28);strip.Controls.Add(lupa);
 code.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Enter){e.SuppressKeyPress=true;Run(()=>{var p=db.Data.Tables["Produtos"].AsEnumerable().FirstOrDefault(r=>r["Ativo"].ToString()=="Sim"&&(r["Código"].ToString()==code.Text.Trim()||r["EAN"].ToString()==code.Text.Trim())&&code.Text.Trim()!="");if(p==null)lookup();else select(p);});}};
 add=Btn("Adicionar",()=>{db.SetCartItem(cart,editing,selected,qty.Value,price.Value,discount.Value);totals();reset();});add.Location=new Point(808,27);add.Size=new Size(120,38);strip.Controls.Add(add);var remove=Btn("Remover",()=>{if(grid.CurrentRow!=null){var view=grid.CurrentRow.DataBoundItem as DataRowView;if(view!=null){bool wasEditing=view.Row==editing;cart.Rows.Remove(view.Row);if(wasEditing)reset();totals();}}});remove.Location=new Point(934,27);remove.Size=new Size(110,38);strip.Controls.Add(remove);reset=()=>{editing=null;selected=null;add.Text="Adicionar";code.Clear();description.Text="Consulte o próximo produto ou clique duas vezes em um item para editar.";stock.Text="0";qty.Value=1;price.Value=0;discount.Value=0;code.Focus();};Action edit=()=>{if(grid.CurrentRow==null)return;var view=grid.CurrentRow.DataBoundItem as DataRowView;if(view==null)return;editing=view.Row;select(db.Data.Tables["Produtos"].Rows.Find(editing["Produto"]));qty.Value=(decimal)editing["Quantidade"];price.Value=(decimal)editing["Preço original"];discount.Value=(decimal)editing["Desconto %"];description.Text="EDITANDO ITEM: "+editing["Descrição"]+" — confirme para aplicar a alteração.";add.Text="Aplicar";qty.FocusValue();};var editButton=Btn("Editar item",edit);editButton.Location=new Point(868,71);editButton.Size=new Size(167,36);strip.Controls.Add(editButton);grid.CellDoubleClick+=(s,e)=>{if(e.RowIndex>=0)Run(edit);};grid.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Enter){e.SuppressKeyPress=true;Run(edit);}};var itemMenu=new ContextMenuStrip();itemMenu.Items.Add("Editar quantidade, preço e desconto",null,(s,e)=>Run(edit));itemMenu.Items.Add("Remover item",null,(s,e)=>remove.PerformClick());itemMenu.Items.Add("Cancelar edição do item",null,(s,e)=>reset());grid.ContextMenuStrip=itemMenu;code.TextChanged+=(s,e)=>{if(selected!=null&&code.Text!=selected["Código"].ToString())selected=null;};qty.EnterAction=()=>price.FocusValue();price.EnterAction=()=>discount.FocusValue();discount.EnterAction=()=>add.PerformClick();pay.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Enter){e.SuppressKeyPress=true;pay.DroppedDown=false;code.Focus();}};
 pay.SelectedIndexChanged+=(s,e)=>Run(()=>{percent=db.Rate(pay.Text);rate.Text=percent.ToString("N2")+" %";foreach(DataRow row in cart.Rows){var p=db.Data.Tables["Produtos"].Rows.Find(row["Produto"]);if(p["Precificação automática"].ToString()=="Sim"){row["Preço original"]=db.SellingPrice(p);row["Preço"]=Store.Money((decimal)row["Preço original"]*(1-(decimal)row["Desconto %"]/100));row["Total"]=Store.Money((decimal)row["Quantidade"]*(decimal)row["Preço"]);}}if(selected!=null&&selected["Precificação automática"].ToString()=="Sim")price.Value=db.SellingPrice(selected);totals();});
 d.KeyPreview=true;d.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.F2){e.SuppressKeyPress=true;Run(lookup);}};d.FormClosing+=(s,e)=>{if(!preview&&d.DialogResult!=DialogResult.OK&&cart.Rows.Count>0&&MessageBox.Show(d,"Descartar esta venda em lançamento?","Venda não salva",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)e.Cancel=true;};d.Commit(()=>{if(editing!=null&&selected==null)throw new Exception("Conclua a seleção do produto ou cancele a edição pelo botão direito no item.");if(selected!=null){db.SetCartItem(cart,editing,selected,qty.Value,price.Value,discount.Value);totals();reset();}int id=db.Sell(cart,clientName.Text,pay.Text,percent);MessageBox.Show("Venda nº "+id+" registrada. Estoque atualizado.","VIDEIRA GESTÃO");});d.AcceptButton=null;d.Shown+=(s,e)=>{code.Focus();if(preview&&(activePreviewMode=="--preview-sale"||activePreviewMode=="--preview-sale-edit")){var sample=db.Data.Tables["Produtos"].Rows.Find(1);sample["Estoque"]=100m;select(sample);qty.Value=2;discount.Value=10;add.PerformClick();if(activePreviewMode=="--preview-sale-edit"){edit();qty.Value=1;discount.Value=5;add.PerformClick();if(cart.Rows.Count!=1||(decimal)cart.Rows[0]["Quantidade"]!=1m||(decimal)cart.Rows[0]["Desconto %"]!=5m)throw new Exception("Falha ao editar item.");System.IO.File.WriteAllText(System.IO.Path.Combine(Environment.CurrentDirectory,"work","edit-result.txt"),"PASS: editar item existente recalcula quantidade, desconto e totais sem duplicar.");}}if(preview&&activePreviewMode.StartsWith("--preview-lookup")){lookup();if(activePreviewMode=="--preview-lookup-flow"){qty.Value=2;qty.Advance();if(!price.HasFocus)throw new Exception("Enter quantidade.");price.Advance();if(!discount.HasFocus)throw new Exception("Enter preço.");discount.Value=10;discount.Advance();if(cart.Rows.Count!=1||!code.Focused)throw new Exception("Enter desconto.");System.IO.File.WriteAllText(System.IO.Path.Combine(Environment.CurrentDirectory,"work","keyboard-result.txt"),"PASS: consulta, seleção, Enter quantidade/preço/desconto, item adicionado e foco no próximo produto.");}}};if(d.ShowDialog(this)==DialogResult.OK)ShowPage("Vendas");
 }}
}}





