using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows.Forms;

namespace Videira {
public sealed class SiteApi : IDisposable {
 public const string BaseUrl="https://lahajlrombmoftevweaf.supabase.co";
 public const string PublicKey="sb_publishable_ixLS7JIsBDtPF75R-rZwcA_2eAD0bKV";
 public const string AdminEmail="videiravinhoteca@gmail.com";
 readonly HttpClient http=new HttpClient{Timeout=TimeSpan.FromSeconds(35)};
 readonly JavaScriptSerializer json=new JavaScriptSerializer{MaxJsonLength=10000000};
 string access,refresh; DateTime expiry;
 public bool Connected {get{return !String.IsNullOrEmpty(access);}}
 public SiteApi(){ServicePointManager.SecurityProtocol=SecurityProtocolType.Tls12;}
 public async Task<object> Request(string path,string method="GET",object body=null,bool authorized=true){
  if(authorized){if(!Connected)throw new Exception("Entre com a conta administradora do site.");if(DateTime.UtcNow>=expiry)await Refresh();}
  using(var req=new HttpRequestMessage(new HttpMethod(method),BaseUrl+path)){
   req.Headers.Add("apikey",PublicKey);req.Headers.Add("Authorization","Bearer "+(authorized?access:PublicKey));req.Headers.Add("Prefer","return=representation");
   if(body!=null)req.Content=new StringContent(json.Serialize(body),Encoding.UTF8,"application/json");
   using(var response=await http.SendAsync(req)){string text=await response.Content.ReadAsStringAsync();object value=null;try{if(text.Length>0)value=json.DeserializeObject(text);}catch{}
    if(!response.IsSuccessStatusCode){if(response.StatusCode==HttpStatusCode.Unauthorized&&authorized){access=null;refresh=null;}var error=value as Dictionary<string,object>;string message=error==null?"":Read(error,"msg");if(message=="")message=error==null?"":Read(error,"message");if(message=="")message=error==null?"":Read(error,"error_description");throw new Exception("O site não confirmou a operação ("+(int)response.StatusCode+"). "+message);}
    return value;
   }
  }
 }
 public static string Read(Dictionary<string,object> row,string key){object v;return row.TryGetValue(key,out v)&&v!=null?Convert.ToString(v,CultureInfo.InvariantCulture):"";}
 void Session(Dictionary<string,object> s){access=Read(s,"access_token");refresh=Read(s,"refresh_token");expiry=DateTime.UtcNow.AddSeconds(Convert.ToDouble(s["expires_in"])-60);}
 async Task Refresh(){try{Session((Dictionary<string,object>)await Request("/auth/v1/token?grant_type=refresh_token","POST",new{refresh_token=refresh},false));}catch{access=null;refresh=null;throw new Exception("Sua sessão expirou. Entre novamente para continuar.");}}
 public async Task Login(string email,string password){Session((Dictionary<string,object>)await Request("/auth/v1/token?grant_type=password","POST",new{email=email,password=password},false));try{var user=(Dictionary<string,object>)await Request("/auth/v1/user");var meta=user["app_metadata"] as Dictionary<string,object>;if(meta==null||Read(meta,"role")!="admin")throw new Exception("Esta conta não tem permissão para editar o site.");}catch{access=null;refresh=null;throw;}}
 public async Task Signup(string password){await Request("/auth/v1/signup?redirect_to=https%3A%2F%2Fvideira-loja.vercel.app%2Fadmin","POST",new{email=AdminEmail,password=password},false);}
 public async Task Logout(){try{if(Connected)await Request("/auth/v1/logout","POST");}finally{access=null;refresh=null;}}
 public async Task<List<Dictionary<string,object>>> Products(){var rows=new List<Dictionary<string,object>>();int offset=0;while(true){var batch=(object[])await Request("/rest/v1/products?select=*&order=created_at.desc&limit=500&offset="+offset);rows.AddRange(batch.Cast<Dictionary<string,object>>());if(batch.Length<500)return rows;offset+=batch.Length;}}
 public async Task Save(Dictionary<string,object> item,string id){var rows=(object[])await Request("/rest/v1/products"+(id==""?"":"?id=eq."+Uri.EscapeDataString(id)),id==""?"POST":"PATCH",item);if(rows==null||rows.Length!=1)throw new Exception("Nenhum produto foi alterado. Atualize a lista e confira suas permissões.");var saved=(Dictionary<string,object>)rows[0];if(Read(saved,"name")!=Read(item,"name"))throw new Exception("O site retornou dados diferentes. Atualize a lista antes de continuar.");}
 public async Task Hide(string id){var rows=(object[])await Request("/rest/v1/products?id=eq."+Uri.EscapeDataString(id),"PATCH",new{active=false});if(rows==null||rows.Length!=1)throw new Exception("O site não confirmou a alteração.");}
 public async Task<string> UploadPhoto(string path){if(!Connected)throw new Exception("Entre na conta do site antes de enviar fotos.");if(DateTime.UtcNow>=expiry)await Refresh();string ext=Path.GetExtension(path).ToLowerInvariant();string mime=ext==".png"?"image/png":ext==".webp"?"image/webp":ext==".jpg"||ext==".jpeg"?"image/jpeg":"";if(mime=="")throw new Exception("Escolha uma imagem JPG, PNG ou WebP.");var file=new FileInfo(path);if(file.Length>6000000)throw new Exception("Use uma imagem de até 6 MB.");string key="produtos/"+Guid.NewGuid().ToString("N")+ext;using(var req=new HttpRequestMessage(HttpMethod.Post,BaseUrl+"/storage/v1/object/catalog-images/"+key)){req.Headers.Add("apikey",PublicKey);req.Headers.Add("Authorization","Bearer "+access);req.Content=new ByteArrayContent(File.ReadAllBytes(path));req.Content.Headers.ContentType=new System.Net.Http.Headers.MediaTypeHeaderValue(mime);using(var response=await http.SendAsync(req)){if(!response.IsSuccessStatusCode)throw new Exception("Não foi possível enviar a foto ("+(int)response.StatusCode+"). Confira a sessão e tente novamente.");}}return BaseUrl+"/storage/v1/object/public/catalog-images/"+key;}
 public void Dispose(){access=null;refresh=null;http.Dispose();}
}
public sealed class SitePanel : UserControl {
 readonly SiteApi api=new SiteApi();readonly Color wine=SystemColors.ControlText,paper=Theme.Surface;
 TextBox email,password,search,name,country,grape,winery,description,image,price,whatsapp;ComboBox category,filter;CheckBox active,featured;DataGridView grid;Label status;Panel login,editor;Button save,refreshButton;string id="";bool dirty,busy,loading;List<Dictionary<string,object>> products=new List<Dictionary<string,object>>();
 public SitePanel(){Dock=DockStyle.Fill;Font=Theme.Font;BackColor=paper;Padding=new Padding(10,5,10,5);Build();Disposed+=(s,e)=>api.Dispose();}
 Button Button(string text,Func<Task> action){var b=new Button{Text=text,AutoSize=true};Theme.Button(b);b.MinimumSize=new Size(110,36);b.Click+=async(s,e)=>await Run(action);return b;}
 async Task Run(Func<Task> action){if(busy)return;busy=true;UseWaitCursor=true;Enabled=false;try{await action();}catch(Exception ex){status.Text=ex is HttpRequestException?"Sem conexão. Confira sua internet; o salvamento não foi confirmado.":ex.Message;status.ForeColor=Color.Firebrick;}finally{UseWaitCursor=false;Enabled=true;busy=false;}}
 void Message(string text){status.Text=text;status.ForeColor=wine;}
 TextBox Field(TableLayoutPanel table,string title,bool multi=false){int row=table.RowCount++;table.RowStyles.Add(new RowStyle(SizeType.Absolute,multi?96:61));var box=new TextBox{Dock=DockStyle.Fill,Multiline=multi,MaxLength=multi?5000:200,Margin=new Padding(0,0,0,6)};var wrap=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=2,ColumnCount=1,Margin=new Padding(0)};wrap.RowStyles.Add(new RowStyle(SizeType.Absolute,24));wrap.RowStyles.Add(new RowStyle(SizeType.Percent,100));wrap.Controls.Add(new Label{Text=title,Dock=DockStyle.Fill},0,0);wrap.Controls.Add(box,0,1);table.Controls.Add(wrap,0,row);box.TextChanged+=(s,e)=>{if(!loading)dirty=true;};return box;}
 void Build(){var layout=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=4};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,45));layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,62));Controls.Add(layout);
  var top=new FlowLayoutPanel{Dock=DockStyle.Fill};top.Controls.Add(Button("Abrir loja ↗",()=>{System.Diagnostics.Process.Start("https://videira-loja.vercel.app/loja");return Task.FromResult(0);}));top.Controls.Add(Button("Sair da conta",async()=>{if(!Discard())return;await api.Logout();products.Clear();grid.DataSource=null;editor.Enabled=false;login.Visible=true;Message("Sessão encerrada. Os dados locais do Gestão não foram alterados.");}));layout.Controls.Add(top,0,0);
  login=new Panel{Dock=DockStyle.Top,Height=112};var auth=new FlowLayoutPanel{Dock=DockStyle.Fill,BackColor=Theme.Surface};auth.Controls.Add(new Label{Text="Conta do site",AutoSize=true,Margin=new Padding(0,14,8,0)});email=new TextBox{Text=SiteApi.AdminEmail,Width=250,ReadOnly=true,Margin=new Padding(4,10,4,4)};password=new TextBox{Width=200,UseSystemPasswordChar=true,Margin=new Padding(4,10,4,4)};auth.Controls.Add(email);auth.Controls.Add(new Label{Text="Senha",AutoSize=true,Margin=new Padding(8,14,4,0)});auth.Controls.Add(password);auth.Controls.Add(Button("Entrar",async()=>{string secret=password.Text;password.Clear();await api.Login(email.Text,secret);await LoadProducts();login.Visible=false;editor.Enabled=true;Message("Conectado ao site. Salvar grava as alterações no catálogo publicado.");}));auth.Controls.Add(Button("Criar primeiro acesso",async()=>{if(password.Text.Length<10)throw new Exception("Digite uma senha com pelo menos 10 caracteres para criar seu acesso.");string secret=password.Text;password.Clear();await api.Signup(secret);Message("Confira o e-mail videiravinhoteca@gmail.com e confirme o acesso. Depois entre com sua senha. Se já tem conta, use Entrar.");}));auth.Controls.Add(new Label{Text="Primeiro acesso: digite sua nova senha, clique em Criar primeiro acesso e confirme o e-mail. Sua senha não é salva no computador.",AutoSize=false,Width=1000,Height=35,ForeColor=wine,Margin=new Padding(0,9,0,0)});login.Controls.Add(auth);layout.Controls.Add(login,0,1);
  var split=new SplitContainer{Size=new Size(1100,600),Dock=DockStyle.Fill,SplitterDistance=560,Panel1MinSize=260,Panel2MinSize=380};layout.Controls.Add(split,0,2);var left=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=3,ColumnCount=1};left.RowStyles.Add(new RowStyle(SizeType.Absolute,45));left.RowStyles.Add(new RowStyle(SizeType.Percent,100));left.RowStyles.Add(new RowStyle(SizeType.Absolute,50));split.Panel1.Controls.Add(left);var filters=new FlowLayoutPanel{Dock=DockStyle.Fill};filters.Controls.Add(new Label{Text="Pesquisar",AutoSize=true,Margin=new Padding(4,12,6,0)});search=new TextBox{Width=160,Margin=new Padding(4,8,4,4)};search.TextChanged+=(s,e)=>Render();filter=new ComboBox{Width=125,DropDownStyle=ComboBoxStyle.DropDownList,Margin=new Padding(4,8,4,4)};filter.Items.AddRange(new object[]{"Todos","Publicados","Ocultos"});filter.SelectedIndex=0;filter.SelectedIndexChanged+=(s,e)=>Render();refreshButton=Button("Atualizar",async()=>{if(!Discard())return;await LoadProducts();Reset();Message("Catálogo atualizado a partir do site.");});filters.Controls.Add(search);filters.Controls.Add(filter);filters.Controls.Add(refreshButton);left.Controls.Add(filters,0,0);
  grid=Theme.Grid();grid.Dock=DockStyle.Fill;grid.AutoGenerateColumns=false;foreach(var c in new[]{new[]{"name","Produto"},new[]{"category","Categoria"},new[]{"price","Preço (R$)"},new[]{"state","Status"}})grid.Columns.Add(new DataGridViewTextBoxColumn{DataPropertyName=c[0],HeaderText=c[1],FillWeight=c[0]=="name"?180:85});grid.CellDoubleClick+=(s,e)=>{if(e.RowIndex>=0)EditSelected();};left.Controls.Add(grid,0,1);var actions=new FlowLayoutPanel{Dock=DockStyle.Fill};actions.Controls.Add(Button("Editar selecionado",()=>{EditSelected();return Task.FromResult(0);}));actions.Controls.Add(Button("Novo produto",()=>{if(Discard())Reset();return Task.FromResult(0);}));actions.Controls.Add(Button("Ocultar no site",async()=>{var p=Selected();if(p==null)throw new Exception("Selecione um produto.");if(MessageBox.Show("Ocultar este produto no catálogo do site? Você poderá republicá-lo ao editar.","Videira",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;await api.Hide(SiteApi.Read(p,"id"));await LoadProducts();Message("Produto ocultado no site.");}));left.Controls.Add(actions,0,2);
  editor=new Panel{Dock=DockStyle.Fill,AutoScroll=true,Enabled=false,Padding=new Padding(18,0,0,0)};split.Panel2.Controls.Add(editor);var fields=new TableLayoutPanel{Dock=DockStyle.Top,AutoSize=true,ColumnCount=1,RowCount=0};fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));editor.Controls.Add(fields);var pinnedSave=Button("Salvar produto no site",SaveProduct);pinnedSave.Dock=DockStyle.Bottom;pinnedSave.Height=40;split.Panel2.Controls.Add(pinnedSave);name=Field(fields,"Nome do vinho *");price=Field(fields,"Preço em R$ — vazio significa sob consulta");var cat=Field(fields,"Categoria — escolha ou digite uma nova");category=new ComboBox{Dock=DockStyle.Fill,DropDownStyle=ComboBoxStyle.DropDown};category.Items.AddRange(new object[]{"Tinto","Branco","Rosé","Espumante","Fortificado","Outro"});((TableLayoutPanel)cat.Parent).Controls.Remove(cat);((TableLayoutPanel)fields.Controls[fields.Controls.Count-1]).Controls.Add(category,0,1);category.TextChanged+=(s,e)=>{if(!loading)dirty=true;};country=Field(fields,"País");grape=Field(fields,"Uva");winery=Field(fields,"Bodega / produtor");image=Field(fields,"Foto — URL HTTPS da imagem");image.MaxLength=2000;fields.Controls.Add(Button("Escolher e enviar foto",async()=>{using(var dialog=new OpenFileDialog{Filter="Fotos|*.jpg;*.jpeg;*.png;*.webp",Title="Escolha a foto do produto"}){if(dialog.ShowDialog()!=DialogResult.OK)return;image.Text=await api.UploadPhoto(dialog.FileName);Message("Foto enviada. Clique em Salvar no site para associá-la ao produto.");}}),0,fields.RowCount++);description=Field(fields,"Descrição",true);active=new CheckBox{Text="Publicado na loja",Checked=true,AutoSize=true};featured=new CheckBox{Text="Destaque na página inicial",AutoSize=true};active.CheckedChanged+=(s,e)=>{if(!loading)dirty=true;};featured.CheckedChanged+=(s,e)=>{if(!loading)dirty=true;};var flags=new FlowLayoutPanel{AutoSize=true,Dock=DockStyle.Fill};flags.Controls.Add(active);flags.Controls.Add(featured);fields.Controls.Add(flags,0,fields.RowCount++);save=Button("Salvar no site",SaveProduct);fields.Controls.Add(save,0,fields.RowCount++);whatsapp=Field(fields,"WhatsApp com país e DDD");whatsapp.MaxLength=15;fields.Controls.Add(Button("Salvar WhatsApp",async()=>{string number=new string(whatsapp.Text.Where(Char.IsDigit).ToArray());if(number.Length<10||number.Length>15)throw new Exception("Informe o WhatsApp com código do país e DDD.");var rows=(object[])await api.Request("/rest/v1/store_settings?id=eq.true","PATCH",new{whatsapp=number});if(rows.Length!=1)throw new Exception("O site não confirmou a alteração do contato.");Message("WhatsApp atualizado no site.");}),0,fields.RowCount++);
  status=new Label{Dock=DockStyle.Fill,ForeColor=wine,Text="Entre para editar o site. Os produtos desta área ficam separados do estoque e das vendas do Gestão.",Padding=new Padding(0,12,0,0)};layout.Controls.Add(status,0,3);dirty=false;
 }
 public bool Discard(){return !dirty||MessageBox.Show("Há alterações que ainda não foram salvas no site. Descartar e continuar?","Videira",MessageBoxButtons.YesNo,MessageBoxIcon.Question)==DialogResult.Yes;}
 Dictionary<string,object> Selected(){if(grid.CurrentRow==null)return null;var row=grid.CurrentRow.DataBoundItem as SiteListItem;return row==null?null:products.FirstOrDefault(p=>SiteApi.Read(p,"id")==row.id);}
 void Render(){if(grid==null)return;string q=search.Text.Trim();var list=products.Where(p=>String.Join(" ",new[]{SiteApi.Read(p,"name"),SiteApi.Read(p,"category"),SiteApi.Read(p,"country"),SiteApi.Read(p,"grape"),SiteApi.Read(p,"winery")}).IndexOf(q,StringComparison.CurrentCultureIgnoreCase)>=0).Where(p=>filter.SelectedIndex==0||(Convert.ToBoolean(p["active"])==(filter.SelectedIndex==1)));grid.DataSource=list.Select(p=>new SiteListItem{id=SiteApi.Read(p,"id"),name=SiteApi.Read(p,"name"),category=SiteApi.Read(p,"category"),price=p["price"]==null?"Sob consulta":Convert.ToDecimal(p["price"]).ToString("N2"),state=Convert.ToBoolean(p["active"])?"Publicado":"Oculto"}).ToList();}
 async Task LoadProducts(){products=await api.Products();Render();foreach(string c in products.Select(p=>SiteApi.Read(p,"category")).Where(c=>c!="").Distinct())if(!category.Items.Contains(c))category.Items.Add(c);var settings=(object[])await api.Request("/rest/v1/store_settings?select=whatsapp");loading=true;whatsapp.Text=settings.Length==0?"":SiteApi.Read((Dictionary<string,object>)settings[0],"whatsapp");loading=false;}
 void EditSelected(){var p=Selected();if(p==null){Message("Selecione um produto na lista.");return;}if(!Discard())return;loading=true;id=SiteApi.Read(p,"id");name.Text=SiteApi.Read(p,"name");price.Text=p["price"]==null?"":Convert.ToDecimal(p["price"]).ToString("0.00",CultureInfo.GetCultureInfo("pt-BR"));category.Text=SiteApi.Read(p,"category");country.Text=SiteApi.Read(p,"country");grape.Text=SiteApi.Read(p,"grape");winery.Text=SiteApi.Read(p,"winery");image.Text=SiteApi.Read(p,"image_url");description.Text=SiteApi.Read(p,"description");active.Checked=Convert.ToBoolean(p["active"]);featured.Checked=Convert.ToBoolean(p["featured"]);loading=false;dirty=false;Message("Editando "+name.Text+". Clique em Salvar no site para publicar as alterações.");}
 void Reset(){loading=true;id="";foreach(var field in new[]{name,price,country,grape,winery,image,description})field.Clear();category.Text="Tinto";active.Checked=true;featured.Checked=false;loading=false;dirty=false;}
 async Task SaveProduct(){if(name.Text.Trim()=="")throw new Exception("Informe o nome do vinho.");if(category.Text.Trim()=="")throw new Exception("Informe a categoria.");decimal number;object value=null;if(price.Text.Trim()!=""){if(!Decimal.TryParse(price.Text.Trim().Replace('.',','),NumberStyles.AllowDecimalPoint,CultureInfo.GetCultureInfo("pt-BR"),out number)||number<0||number>9999999999m)throw new Exception("Informe um preço válido, usando vírgula para os centavos.");value=Math.Round(number,2);}Uri uri;if(image.Text.Trim()!=""&&(!Uri.TryCreate(image.Text.Trim(),UriKind.Absolute,out uri)||uri.Scheme!="https"))throw new Exception("A foto precisa ter uma URL HTTPS válida.");var p=new Dictionary<string,object>{{"name",name.Text.Trim()},{"category",category.Text.Trim()},{"country",country.Text.Trim()},{"grape",grape.Text.Trim()},{"winery",winery.Text.Trim()},{"image_url",image.Text.Trim()},{"description",description.Text.Trim()},{"price",value},{"active",active.Checked},{"featured",featured.Checked}};await api.Save(p,id);dirty=false;await LoadProducts();Reset();Message("Salvo no site e conferido no servidor. Atualize a loja no navegador para ver o resultado.");}
}
public sealed class SiteListItem {public string id{get;set;}public string name{get;set;}public string category{get;set;}public string price{get;set;}public string state{get;set;}}
public static class SiteStandalone {
 [STAThread] public static void Main(string[] args){if(args.Contains("--connection-test")){try{using(var api=new SiteApi()){var rows=(object[])api.Request("/rest/v1/products?select=id&active=eq.true","GET",null,false).GetAwaiter().GetResult();var contact=(object[])api.Request("/rest/v1/store_settings?select=whatsapp","GET",null,false).GetAwaiter().GetResult();bool denied=false;try{api.Request("/rest/v1/products","POST",new{name="Verificação de acesso do painel",active=false},false).GetAwaiter().GetResult();}catch(Exception ex){denied=ex.Message.Contains("401")||ex.Message.Contains("403");}if(!denied)throw new Exception("A edição anônima não foi bloqueada.");File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"connection-test.txt"),"PASS: conexão HTTPS, leitura do catálogo e do contato; edição sem login bloqueada. Rótulos publicados: "+rows.Length+"; configurações: "+contact.Length);}}catch(Exception ex){File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"connection-test.txt"),"FAIL: "+ex.Message);}return;}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);var form=new Form{Text="VIDEIRA • Painel do site",Width=1280,Height=860,MinimumSize=new Size(1100,700),StartPosition=FormStartPosition.CenterScreen};var panel=new SitePanel();form.Controls.Add(panel);form.FormClosing+=(s,e)=>{if(!panel.Discard())e.Cancel=true;};if(args.Contains("--preview-site"))form.Shown+=(s,e)=>{var timer=new Timer{Interval=800};timer.Tick+=(a,b)=>{timer.Stop();using(var bmp=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bmp,new Rectangle(0,0,form.Width,form.Height));bmp.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"painel-site.png"));}form.Close();};timer.Start();};Application.Run(form);}
}
}
