using System;using System.Data;using System.Linq;using System.IO;
namespace Videira {
partial class Store {
 public bool SetupStoneRates(){if(Company["Taxas Stone importadas"].ToString()=="Sim")return false;Atomic(()=>{Data.Tables["Taxas"].Clear();Data.Tables["Taxas"].Rows.Add(1,"Débito VISA/MASTER • Stone",1.37m);Data.Tables["Taxas"].Rows.Add(2,"Crédito VISA/MASTER 1x • Stone",4.19m);Data.Tables["Taxas"].Rows.Add(3,"Crédito AMEX/ELO 1x • Stone",4.19m);Data.Tables["Taxas"].Rows.Add(4,"Débito ELO • Stone",2.48m);Data.Tables["Taxas"].Rows.Add(5,"Pix na maquininha • Stone",0.99m);
 foreach(DataRow p in Data.Tables["Produtos"].Rows){string old=p["Taxa padrão"].ToString();if(old=="Pix"||old=="Dinheiro")continue;bool elo=old.IndexOf("ELO",StringComparison.OrdinalIgnoreCase)>=0||old.IndexOf("AMEX",StringComparison.OrdinalIgnoreCase)>=0;bool debit=old.IndexOf("Débito",StringComparison.OrdinalIgnoreCase)>=0;p["Taxa padrão"]=debit?(elo?"Débito ELO • Stone":"Débito VISA/MASTER • Stone"):(elo?"Crédito AMEX/ELO 1x • Stone":"Crédito VISA/MASTER 1x • Stone");}
 Company["Taxas Stone importadas"]="Sim";Company["Taxas somente 1x"]="Sim";Company["Taxas Infinite importadas"]="Sim";});return true;}
}
static class StoneTests {
 static void Check(bool b,string m){if(!b)throw new Exception("Stone: "+m);}
 public static void Run(){var db=new Store(Path.Combine(Environment.CurrentDirectory,"work","Stone-"+Guid.NewGuid()));db.Data.Tables["Produtos"].Rows.Add(1,"V","VINHO","F",44.90m,65m,10m,"Sim");var p=db.Data.Tables["Produtos"].Rows.Find(1);p["Taxa padrão"]="Crédito AMEX/ELO 1x";db.SetupStoneRates();Check(db.Data.Tables["Taxas"].Rows.Count==5,"somente taxas Stone");Check(db.Rate("Crédito AMEX/ELO 1x • Stone")==4.19m&&db.Rate("Crédito VISA/MASTER 1x • Stone")==4.19m,"crédito 1x");Check(db.Rate("Débito ELO • Stone")==2.48m&&db.Rate("Débito VISA/MASTER • Stone")==1.37m,"débito");Check(db.Rate("Pix")==0&&db.Rate("Pix na maquininha • Stone")==0.99m,"Pix transferência separado da maquininha");Check((decimal)p["Preço"]==65m&&p["Taxa padrão"].ToString()=="Crédito AMEX/ELO 1x • Stone","referência atualizada e preço manual preservado");var cart=new DataTable();cart.Columns.Add("Produto",typeof(int));cart.Columns.Add("Quantidade",typeof(decimal));cart.Columns.Add("Preço",typeof(decimal));cart.Rows.Add(1,1m,65m);int a=db.Sell(cart,"CLIENTE","Crédito VISA/MASTER 1x • Stone",db.Rate("Crédito VISA/MASTER 1x • Stone"));int b=db.Sell(cart,"CLIENTE","Pix",0);int c=db.Sell(cart,"CLIENTE","Pix na maquininha • Stone",db.Rate("Pix na maquininha • Stone"));Check((decimal)db.Data.Tables["Vendas"].Rows.Find(a)["Taxa R$"]==2.72m&&(decimal)db.Data.Tables["Vendas"].Rows.Find(b)["Taxa R$"]==0&&(decimal)db.Data.Tables["Vendas"].Rows.Find(c)["Taxa R$"]==0.64m,"taxa real sobre o mesmo preço final");db.Save();db=new Store(db.Root);Check(!db.SetupStoneRates()&&db.Data.Tables["Taxas"].Rows.Count==5,"idempotência e taxas antigas não voltam");Check((decimal)db.Data.Tables["Vendas"].Rows.Find(a)["Total"]==65m,"histórico preservado");File.AppendAllText(Path.Combine(Environment.CurrentDirectory,"work","test-result.txt"),"\r\nPASS 2.9 Stone: migração única, taxas das fotos, limite 1x, referências, preço manual, Pix transferência e maquininha, taxas sobre venda e persistência.");}
}
}
