using System;
using System.Data;
using System.Linq;
using System.Text;
namespace Videira {
partial class Store {
 public static void StrategySchema(DataSet data){
  var p=data.Tables["Produtos"];foreach(string name in new[]{"País","Região","Uva","Safra","Tipo de vinho","Taxa padrão"})Add(p,name,typeof(string),name=="Taxa padrão"?"Crédito à vista":"");
  Add(p,"Margem desejada %",typeof(decimal),30m);Add(p,"Precificação automática",typeof(string),"Não");
  if(!data.Tables.Contains("Empresa"))Table(data,"Empresa","Nome fantasia","Razão social","CNPJ","Inscrição estadual","Telefone","WhatsApp","Email","Endereço","Cidade","UF","CEP","Responsável","Rateio","Unidades mês:n","Faturamento mês:n","Margem padrão:n","Validade orçamento:i","Assinatura");
  if(!data.Tables.Contains("Plano mensal"))Table(data,"Plano mensal","Categoria","Descrição","Valor:n");
  if(!data.Tables.Contains("Orçamentos"))Table(data,"Orçamentos","Data:d","Validade:d","Cliente","Telefone","Pagamento","Taxa %:n","Total:n","Situação","Mensagem","Observações","Venda:i");
  if(!data.Tables.Contains("Orçamento itens"))Table(data,"Orçamento itens","Orçamento:i","Produto:i","Código","Nome","Detalhes","Quantidade:n","Preço:n","Total:n");
 }
 public DataRow Company {get {var t=Data.Tables["Empresa"];if(t.Rows.Count==0){var r=t.NewRow();r["Id"]=1;foreach(DataColumn col in t.Columns){if(col.DataType==typeof(string))r[col]="";if(col.DataType==typeof(decimal))r[col]=0m;}r["Rateio"]="Por unidade";r["Margem padrão"]=30m;r["Validade orçamento"]=7;r["Assinatura"]="Fico à disposição para ajudar na escolha dos seus vinhos.";t.Rows.Add(r);}return t.Rows[0];}}
 public decimal Rate(string mode){if(mode=="Dinheiro"||mode=="Pix")return 0;var r=Data.Tables["Taxas"].AsEnumerable().FirstOrDefault(x=>x["Modalidade"].ToString()==mode);if(r==null)throw new Exception("Cadastre a taxa para "+mode+".");decimal rate=(decimal)r["Percentual"];if(mode.StartsWith("Crédito")&&rate<=0)throw new Exception("Confirme a taxa de "+mode+" em Financeiro antes de usar essa modalidade.");return rate;}
 public decimal SaleAllocationFactor(decimal units,decimal revenue){if(MonthlyPlan==0)return 0;bool byRevenue=Company["Rateio"].ToString()=="Por faturamento";decimal basis=(decimal)Company[byRevenue?"Faturamento mês":"Unidades mês"];if(basis<=0)throw new Exception("Informe a estimativa mensal em Minha empresa para calcular o lucro após os gastos.");return (byRevenue?revenue:units)/basis;}
 public decimal MonthlyPlan {get{return Data.Tables["Plano mensal"].AsEnumerable().Sum(r=>(decimal)r["Valor"]);}}
 public Pricing Price(DataRow p,string mode){return Calculate((decimal)p["Custo"],(decimal)p["Embalagem unitária"],(decimal)p["Outros custos unitários"],(decimal)p["Despesa variável %"],(decimal)p["Margem desejada %"],Rate(mode));}
 public Pricing CostsAt(DataRow p,decimal price){
 decimal monthly=MonthlyPlan,overhead=0;
 if(monthly>0){decimal basis=(decimal)Company[Company["Rateio"].ToString()=="Por faturamento"?"Faturamento mês":"Unidades mês"];if(basis<=0)throw new Exception("Informe a estimativa mensal em Minha empresa.");overhead=Company["Rateio"].ToString()=="Por faturamento"?price*monthly/basis:monthly/basis;}
 decimal direct=(decimal)p["Custo"]+(decimal)p["Embalagem unitária"]+(decimal)p["Outros custos unitários"],fee=price*Rate(p["Taxa padrão"].ToString())/100,variable=price*(decimal)p["Despesa variável %"]/100;
 return new Pricing{Price=price,Base=direct,Overhead=overhead,Fee=fee,Variable=variable,Profit=price-direct-overhead-fee-variable};
 }
 public decimal SellingPrice(DataRow p){return p["Precificação automática"].ToString()=="Sim"?Price(p,p["Taxa padrão"].ToString()).Price:(decimal)p["Preço"];}
 public Pricing Calculate(decimal supplier,decimal pack,decimal extras,decimal variable,decimal margin,decimal card){
  decimal monthly=MonthlyPlan,allocated=0,overheadPercent=0;if(monthly>0){if(Company["Rateio"].ToString()=="Por faturamento"){decimal expected=(decimal)Company["Faturamento mês"];if(expected<=0)throw new Exception("Informe o faturamento mensal estimado em Minha empresa > Precificação.");overheadPercent=monthly/expected*100;}else{decimal units=(decimal)Company["Unidades mês"];if(units<=0)throw new Exception("Informe a quantidade mensal estimada em Minha empresa > Precificação.");allocated=monthly/units;}}
  decimal denominator=1-(variable+margin+card+overheadPercent)/100;if(denominator<=0)throw new Exception("Margem, taxa e despesas percentuais devem somar menos de 100%. Revise as metas e o rateio.");
  decimal price=Math.Ceiling((supplier+pack+extras+allocated)/denominator*100)/100;decimal overhead=allocated+price*overheadPercent/100;return new Pricing{Price=price,Base=supplier+pack+extras,Overhead=overhead,Fee=price*card/100,Variable=price*variable/100,Profit=price-supplier-pack-extras-overhead-price*(variable+card)/100,Rate=card};
 }
 public string WineDetails(DataRow p){string[] keys={"Tipo de vinho","Uva","Safra","País","Região"};var parts=keys.Where(k=>!string.IsNullOrWhiteSpace(p[k].ToString())).Select(k=>k+": "+p[k]);if((decimal)p["Volume ml"]>0)parts=parts.Concat(new[]{((decimal)p["Volume ml"]).ToString("N0")+" ml"});return string.Join(" | ",parts);}
 public int Quote(DataTable cart,string client,string phone,string payment,DateTime valid,string note){int id=Next("Orçamentos");Atomic(()=>{
  if(cart.Rows.Count==0)throw new Exception("Adicione produtos ao orçamento.");if(valid.Date<DateTime.Today)throw new Exception("A validade não pode estar no passado.");
  decimal total=0;foreach(DataRow item in cart.Rows){var p=Data.Tables["Produtos"].Rows.Find(item["Produto"]);decimal q=(decimal)item["Quantidade"],price=(decimal)item["Preço"];if(p==null||q<=0||q!=Math.Truncate(q)||price<0)throw new Exception("Verifique produtos, quantidades e preços.");decimal line=Money(q*price);total+=line;Data.Tables["Orçamento itens"].Rows.Add(Next("Orçamento itens"),id,p["Id"],p["Código"],p["Nome"],WineDetails(p),q,price,line);}
  var r=Data.Tables["Orçamentos"].Rows.Add(id,DateTime.Now,valid.Date,client,phone,payment,Rate(payment),total,"Aberto","",note,0);r["Mensagem"]=QuoteMessage(r);
 });return id;}
 public string QuoteMessage(DataRow quote){var c=Company;var b=new StringBuilder();string name=c["Nome fantasia"].ToString();if(string.IsNullOrWhiteSpace(name))name=c["Razão social"].ToString();b.AppendLine("*"+(string.IsNullOrWhiteSpace(name)?"VIDEIRA GESTÃO":name)+"*");if(!string.IsNullOrWhiteSpace(c["CNPJ"].ToString()))b.AppendLine("CNPJ: "+c["CNPJ"]);b.AppendLine("*Orçamento nº "+((int)quote["Id"]).ToString("D6")+"*");if(!string.IsNullOrWhiteSpace(quote["Cliente"].ToString()))b.AppendLine("Olá, "+quote["Cliente"]+"!");b.AppendLine();foreach(DataRow i in Data.Tables["Orçamento itens"].Select("[Orçamento] = "+quote["Id"])){b.AppendLine("*"+i["Nome"]+"*");if(!string.IsNullOrWhiteSpace(i["Detalhes"].ToString()))b.AppendLine(i["Detalhes"].ToString());b.AppendLine(((decimal)i["Quantidade"]).ToString("N0")+" un. × R$ "+((decimal)i["Preço"]).ToString("N2")+" = *R$ "+((decimal)i["Total"]).ToString("N2")+"*");b.AppendLine();}if(quote["Tipo entrega"].ToString()=="Entrega"){b.AppendLine("Entrega: R$ "+((decimal)quote["Entrega R$"]).ToString("N2"));b.AppendLine("Destino: "+quote["Endereço entrega"]+" | "+quote["Região entrega"]+" | CEP "+quote["CEP entrega"]);b.AppendLine();}b.AppendLine("*Total: R$ "+((decimal)quote["Total"]).ToString("N2")+"*");b.AppendLine("Pagamento: "+quote["Pagamento"]);b.AppendLine("Válido até: "+((DateTime)quote["Validade"]).ToString("dd/MM/yyyy"));if(!string.IsNullOrWhiteSpace(quote["Observações"].ToString()))b.AppendLine(quote["Observações"].ToString());b.AppendLine();if(!string.IsNullOrWhiteSpace(c["WhatsApp"].ToString()))b.AppendLine("Contato: "+c["WhatsApp"]);b.Append(c["Assinatura"].ToString());return b.ToString();}
 public int ConvertQuote(int id){int sale=0;Atomic(()=>{var quote=Data.Tables["Orçamentos"].Rows.Find(id);if(quote==null||quote["Situação"].ToString()!="Aberto")throw new Exception("Somente orçamentos abertos podem virar venda.");var cart=new DataTable();cart.Columns.Add("Produto",typeof(int));cart.Columns.Add("Quantidade",typeof(decimal));cart.Columns.Add("Preço",typeof(decimal));foreach(DataRow i in Data.Tables["Orçamento itens"].Select("[Orçamento] = "+id))cart.Rows.Add(i["Produto"],i["Quantidade"],i["Preço"]);sale=Sell(cart,quote["Cliente"].ToString(),quote["Pagamento"].ToString(),(decimal)quote["Taxa %"],false);var v=Data.Tables["Vendas"].Rows.Find(sale);decimal freight=(decimal)quote["Entrega R$"];foreach(string key in new[]{"CEP entrega","Endereço entrega","Região entrega","Tipo entrega","Entrega R$"})v[key]=quote[key];decimal freightFee=Money(freight*(decimal)quote["Taxa %"]/100);v["Total"]=(decimal)v["Total"]+freight;v["Outras despesas"]=(decimal)v["Outras despesas"]+freight;v["Taxa R$"]=(decimal)v["Taxa R$"]+freightFee;v["Resultado"]=(decimal)v["Resultado"]-freightFee;quote["Situação"]="Vendido";quote["Venda"]=sale;});return sale;}
}
class Pricing {public decimal Price,Base,Overhead,Fee,Variable,Profit,Rate;}
}
