using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Windows.Forms;

namespace Videira {
static class Theme {
 public static readonly Color Surface=Color.FromArgb(243,246,249), Line=Color.FromArgb(179,187,199), Blue=Color.FromArgb(0,120,215);
 public static Font Font=new Font("Tahoma",10f);static Image brand;public static Image Brand {get{if(brand==null){using(var stream=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("Videira.Logo")){if(stream!=null)brand=new Bitmap(Image.FromStream(stream));}}return brand;}}
 public static Image Icon(string kind){var b=new Bitmap(18,18);using(var g=Graphics.FromImage(b)){g.SmoothingMode=SmoothingMode.AntiAlias;if(kind=="search"){using(var p=new Pen(Color.FromArgb(176,138,66),2)){g.DrawEllipse(p,3,2,9,9);g.DrawLine(p,11,10,16,16);}}else if(kind=="ok"){using(var p=new Pen(Color.FromArgb(72,146,72),2.5f)){g.DrawLines(p,new[]{new Point(2,9),new Point(7,14),new Point(16,3)});}}else if(kind=="remove"){using(var p=new Pen(Color.IndianRed,2.5f)){g.DrawLine(p,4,4,14,14);g.DrawLine(p,14,4,4,14);}}else if(kind=="new"){g.FillRectangle(Brushes.AliceBlue,4,2,10,13);g.DrawRectangle(Pens.SteelBlue,4,2,10,13);g.DrawLine(Pens.SteelBlue,7,6,12,6);g.DrawLine(Pens.SteelBlue,7,9,12,9);}else if(kind=="exit"){g.FillRectangle(Brushes.Tan,10,2,5,14);using(var p=new Pen(Color.SeaGreen,2)){g.DrawLine(p,2,9,11,9);g.DrawLine(p,7,5,11,9);g.DrawLine(p,7,13,11,9);}}else {Color[] colors={Color.SteelBlue,Color.MediumSeaGreen,Color.Goldenrod,Color.IndianRed};for(int i=0;i<9;i++)using(var br=new SolidBrush(colors[i%4]))g.FillRectangle(br,2+(i%3)*5,2+(i/3)*5,3,3);}}return b;}
 public static void Button(Button b,string kind=""){b.Font=Font;b.Height=36;b.Width=104;b.Margin=new Padding(3);b.Image=Icon(kind==""?b.Text.Contains("Salvar")||b.Text.Contains("Adicionar")||b.Text.Contains("Confirmar")?"ok":b.Text.Contains("Sair")?"exit":b.Text.Contains("Cancelar")||b.Text.Contains("Remover")||b.Text.Contains("Excluir")?"remove":b.Text.Contains("Filtrar")||b.Text.Contains("Editar")||b.Text.Contains("itens")?"search":b.Text.Contains("Novo")||b.Text.Contains("Nova")?"new":"menu":kind);b.ImageAlign=ContentAlignment.MiddleLeft;b.TextImageRelation=TextImageRelation.ImageBeforeText;b.Padding=new Padding(4,0,4,0);b.BackColor=Color.FromArgb(236,241,246);b.UseVisualStyleBackColor=false;}
 public static DataGridView Grid(){var g=new DataGridView{ReadOnly=true,AllowUserToAddRows=false,AllowUserToDeleteRows=false,MultiSelect=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,BackgroundColor=Color.White,RowHeadersVisible=false,BorderStyle=BorderStyle.FixedSingle,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,EnableHeadersVisualStyles=false,Font=Font,ColumnHeadersHeight=32,ColumnHeadersHeightSizeMode=DataGridViewColumnHeadersHeightSizeMode.AutoSize,AllowUserToResizeRows=false};g.RowTemplate.Height=30;g.ColumnHeadersDefaultCellStyle.BackColor=Color.FromArgb(246,246,246);g.ColumnHeadersDefaultCellStyle.ForeColor=Color.FromArgb(35,35,35);g.ColumnHeadersDefaultCellStyle.Font=Font;g.ColumnHeadersDefaultCellStyle.WrapMode=DataGridViewTriState.True;g.ColumnHeadersDefaultCellStyle.Alignment=DataGridViewContentAlignment.MiddleLeft;g.ColumnHeadersDefaultCellStyle.Padding=new Padding(3,5,3,5);g.DefaultCellStyle.WrapMode=DataGridViewTriState.False;g.DefaultCellStyle.SelectionBackColor=Blue;g.DefaultCellStyle.SelectionForeColor=Color.White;g.AlternatingRowsDefaultCellStyle.BackColor=Color.FromArgb(247,248,249);g.GridColor=Color.FromArgb(213,216,220);return g;}
 public static void LabelField(Control parent,string label,Control field,int x,int y,int width){var l=new Label{Text=label,Location=new Point(x,y),Size=new Size(width,20),Font=new Font(Font,FontStyle.Bold)};parent.Controls.Add(l);field.Location=new Point(x,y+23);field.Size=new Size(width,28);field.Font=Font;parent.Controls.Add(field);}
 public static TextBox Readonly(string value){return new TextBox{Text=value,ReadOnly=true,BackColor=Color.FromArgb(220,223,227)};}
 public static void ProductLayout(Dialog d){Control[] cs=new Control[8];for(int i=0;i<8;i++)cs[i]=d.Fields.GetControlFromPosition(1,i);foreach(Control c in cs)c.Dock=DockStyle.None;d.Fields.Controls.Clear();d.Fields.Visible=false;d.Size=new Size(780,460);var tabs=new TabControl{Dock=DockStyle.Fill,Padding=new Point(14,5)};var tab=new TabPage("Principal"){BackColor=Surface};tabs.TabPages.Add(tab);d.Controls.Add(tabs);tabs.BringToFront();var general=new GroupBox{Text="Identificação do produto",Location=new Point(12,12),Size=new Size(724,143)};tab.Controls.Add(general);LabelField(general,"Código *",cs[0],14,24,120);LabelField(general,"Descrição / nome *",cs[1],145,24,562);LabelField(general,"Fornecedor",cs[2],14,78,545);LabelField(general,"Situação",cs[6],570,78,137);var values=new GroupBox{Text="Preço, custo e estoque",Location=new Point(12,166),Size=new Size(724,146)};tab.Controls.Add(values);LabelField(values,"Custo de compra (R$)",cs[3],14,24,215);LabelField(values,"Preço de venda (R$)",cs[4],245,24,215);LabelField(values,"Estoque inicial (un.)",cs[5],477,24,230);cs[7].Location=new Point(14,92);cs[7].Size=new Size(692,30);cs[7].BackColor=Color.FromArgb(225,232,240);cs[7].Padding=new Padding(8,5,0,0);values.Controls.Add(cs[7]);tab.Controls.Add(new Label{Text="* Campos obrigatórios. Reposições são registradas em Entradas de estoque.",Location=new Point(16,326),Size=new Size(700,22),ForeColor=Color.DimGray});}
}
class TitleBar : Label {
 public TitleBar(string title){Text="   "+title;Height=32;Dock=DockStyle.Top;TextAlign=ContentAlignment.MiddleLeft;Font=Theme.Font;}
 protected override void OnPaint(PaintEventArgs e){using(var b=new LinearGradientBrush(ClientRectangle,Color.FromArgb(172,195,218),Color.FromArgb(224,235,246),90f))e.Graphics.FillRectangle(b,ClientRectangle);e.Graphics.DrawLine(Pens.SlateGray,0,Height-1,Width,Height-1);TextRenderer.DrawText(e.Graphics,Text,Font,ClientRectangle,Color.FromArgb(24,40,57),TextFormatFlags.Left|TextFormatFlags.VerticalCenter);}
}
}

