using System;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Globalization;
using System.Reflection;

namespace Videira {
static class Program {
 [STAThread] static void Main(string[] args) {
  CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("pt-BR");
  Application.EnableVisualStyles(); Application.SetCompatibleTextRenderingDefault(false);if(args.Any(a=>a.StartsWith("--preview")))Application.ThreadException+=(s,e)=>{File.WriteAllText(Path.Combine(Environment.CurrentDirectory,"work","ui-error.txt"),e.Exception.ToString());Application.Exit();};
  try {
   if(args.Contains("--materials")){var arg=args.First(a=>a.StartsWith("--data-root="));var store=new Store(arg.Substring(12));store.Save();return;}
   if(args.Contains("--stone")){var arg=args.First(a=>a.StartsWith("--data-root="));var store=new Store(arg.Substring(12));store.SetupStoneRates();return;}
   if(args.Contains("--upgrade28")){var arg=args.First(a=>a.StartsWith("--data-root="));var store=new Store(arg.Substring(12));store.SetupFourRates();store.Company["Origem Porto Meira confirmada"]="Sim";store.Save();return;}
   if(args.Contains("--test")){Tests.Run();AdvancedTests.Run();StrategyTests.Run();IntegrationTests.Run();MarketTests.Run();MarketEditTests.Run();MarkupTests.Run();DeliveryTests.Run();StoneTests.Run();MaterialsTests.Run();BatchConfirmTests.Run();return;}
   if(Path.GetFileName(Application.ExecutablePath).StartsWith("Instalar")){Install();return;}
   if(args.Contains("--import-market")){string importRoot=args.FirstOrDefault(a=>a.StartsWith("--data-root="));var imp=new Store(importRoot==null?Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"VideiraGestao","Dados"):importRoot.Substring(12));int count=imp.ImportPortfolio();int filled=imp.FillMissingMarketReferences();File.WriteAllText(Path.Combine(Path.GetDirectoryName(Application.ExecutablePath),"market-import-result.txt"),"Referências preenchidas: "+filled+"; Produtos adicionados: "+count+"; rótulos Mercado: "+imp.Data.Tables["Mercado"].Rows.Count);return;}
   bool smoke=args.Any(a=>a.StartsWith("--preview"));
   string root=smoke?Path.Combine(Environment.CurrentDirectory,"work","VideiraPreview"):Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"VideiraGestao","Dados");
   using(var mutex=new System.Threading.Mutex(false,"Local\\VideiraGestao")) {
    if(!mutex.WaitOne(0)){MessageBox.Show("O VIDEIRA GESTÃO já está aberto.");return;}
    try {if(smoke){Application.Run(new MainForm(new Store(root),true,args.FirstOrDefault(a=>a.StartsWith("--preview"))??""));}else{using(var cloud=CloudStore.AskLogin()){if(cloud==null)return;var online=new Store(root);online.ConnectCloud(cloud);Application.Run(new MainForm(online,false,""));}}} finally{mutex.ReleaseMutex();}
   }
  }catch(Exception ex){if(args.Contains("--test")||args.Contains("--upgrade28")||args.Contains("--stone")||args.Contains("--materials")||args.Any(a=>a.StartsWith("--preview"))){System.IO.File.WriteAllText(Path.Combine(Path.GetDirectoryName(Application.ExecutablePath),"diagnostico.txt"),ex.ToString());return;}MessageBox.Show(ex.Message,"VIDEIRA GESTÃO",MessageBoxButtons.OK,MessageBoxIcon.Error);}
 }
 static void Install(){
  if(MessageBox.Show("Instalar VIDEIRA GESTÃO neste computador e criar um atalho na área de trabalho?","VIDEIRA GESTÃO • Instalador",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;
  string dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"VideiraGestao");Directory.CreateDirectory(dir);
  string exe=Path.Combine(dir,"VIDEIRA GESTÃO.exe"); File.Copy(Application.ExecutablePath,exe,true);
  Type t=Type.GetTypeFromProgID("WScript.Shell");object shell=Activator.CreateInstance(t);
  object link=t.InvokeMember("CreateShortcut",BindingFlags.InvokeMethod,null,shell,new object[]{Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),"VIDEIRA GESTÃO.lnk")});
  link.GetType().InvokeMember("TargetPath",BindingFlags.SetProperty,null,link,new object[]{exe});
  link.GetType().InvokeMember("WorkingDirectory",BindingFlags.SetProperty,null,link,new object[]{dir});
  link.GetType().InvokeMember("Save",BindingFlags.InvokeMethod,null,link,null);
  MessageBox.Show("Instalação concluída. Abra pelo atalho VIDEIRA GESTÃO na área de trabalho.\n\nEntre com sua conta para acessar os mesmos dados online neste computador.","VIDEIRA GESTÃO");
 }
}
partial class Store {
 public DataSet Data; public string Root; public string FileName {get{return Path.Combine(Root,"videira.xml");}}
 static DataTable Table(DataSet ds,string name,params string[] fields){var t=ds.Tables.Add(name);t.Columns.Add("Id",typeof(int));foreach(string f in fields){string[] p=f.Split(':');Type type=p.Length<2?typeof(string):p[1]=="n"?typeof(decimal):p[1]=="i"?typeof(int):typeof(DateTime);t.Columns.Add(p[0],type);}t.PrimaryKey=new[]{t.Columns["Id"]};return t;}
 public Store(string root){Root=root;Directory.CreateDirectory(root);Data=new DataSet("Videira");
  Table(Data,"Produtos","Código","Nome","Fornecedor","Custo:n","Preço:n","Estoque:n","Ativo");
  Table(Data,"Fornecedores","Nome","Telefone","Email","Observações");
  Table(Data,"Clientes","Nome","Telefone","Email","Observações");
  Table(Data,"Vendas","Data:d","Cliente","Pagamento","Taxa %:n","Total:n","Custo:n","Embalagem:n","Taxa R$:n","Resultado:n","Situação");
  Table(Data,"Itens","Venda:i","Produto:i","Código","Nome","Quantidade:n","Preço:n","Custo:n","Total:n");
  Table(Data,"Movimentos","Data:d","Produto:i","Código","Nome","Quantidade:n","Tipo","Observações");
  Table(Data,"Despesas","Data:d","Categoria","Descrição","Valor:n");
  Table(Data,"Taxas","Modalidade","Percentual:n");
  Upgrade(Data);if(System.IO.File.Exists(FileName)){Data.ReadXml(FileName,XmlReadMode.IgnoreSchema);Upgrade(Data);}
  else {Data.Tables["Taxas"].Rows.Add(1,"Débito",0m);Data.Tables["Taxas"].Rows.Add(2,"Crédito à vista",0m);Data.Tables["Taxas"].Rows.Add(3,"Crédito parcelado",0m);Save();}if(ImportInfiniteRates())Save();if(SetupDelivery())Save();if(SeedMaterials())Save();
 }
 public int Next(string table){return Data.Tables[table].Rows.Count==0?1:Data.Tables[table].AsEnumerable().Max(r=>(int)r["Id"])+1;}
 public void Save(){if(Cloud!=null){Cloud.Commit(Data);try{SaveLocal();}catch{}return;}SaveLocal();}
 public void SaveLocal(){string temp=FileName+".tmp";Data.WriteXml(temp,XmlWriteMode.WriteSchema);if(System.IO.File.Exists(FileName))System.IO.File.Replace(temp,FileName,FileName+".bak");else System.IO.File.Move(temp,FileName);}
 public void Atomic(Action a){DataSet old=Data.Copy();try{a();Save();}catch{Data=old;throw;}}
 public static decimal Money(decimal n){return Math.Round(n,2,MidpointRounding.AwayFromZero);}
 public int Sell(DataTable cart,string client,string payment,decimal rate,bool persist=true){int id=Next("Vendas");Action transaction=()=>{
  if(cart.Rows.Count==0)throw new Exception("Adicione ao menos um produto.");
  foreach(var g in cart.AsEnumerable().GroupBy(r=>(int)r["Produto"])) {var p=Data.Tables["Produtos"].Rows.Find(g.Key);if(p==null||p["Ativo"].ToString()!="Sim")throw new Exception("Produto indisponível.");if(g.Sum(r=>(decimal)r["Quantidade"])>(decimal)p["Estoque"])throw new Exception("Estoque insuficiente: "+p["Nome"]);}
  decimal total=0,cost=0,pack=0,extra=0;
  foreach(DataRow item in cart.Rows){var p=Data.Tables["Produtos"].Rows.Find(item["Produto"]);decimal q=(decimal)item["Quantidade"],price=(decimal)item["Preço"];if(q<=0||q!=Math.Truncate(q)||price<0)throw new Exception("Quantidade deve ser inteira e positiva; preço não pode ser negativo.");decimal line=Money(q*price);total+=line;cost+=Money(q*(decimal)p["Custo"]);pack+=Money(q*(decimal)p["Embalagem unitária"]);decimal other=Money(q*(decimal)p["Outros custos unitários"]+line*(decimal)p["Despesa variável %"]/100);extra+=other;
   Data.Tables["Itens"].Rows.Add(Next("Itens"),id,p["Id"],p["Código"],p["Nome"],q,price,p["Custo"],line,p["Embalagem unitária"],other,cart.Columns.Contains("Preço original")?item["Preço original"]:(object)price,cart.Columns.Contains("Desconto %")?item["Desconto %"]:(object)0m);
   p["Estoque"]=(decimal)p["Estoque"]-q;Move(p,-q,"Venda","Venda nº "+id);
  }
  decimal fee=Money(total*rate/100);Data.Tables["Vendas"].Rows.Add(id,DateTime.Now,client,payment,rate,total,cost,pack,fee,total-cost-pack-fee-extra,"Concluída",extra);
 };if(persist)Atomic(transaction);else transaction();return id;}
 public void Move(DataRow p,decimal q,string type,string note){Data.Tables["Movimentos"].Rows.Add(Next("Movimentos"),DateTime.Now,p["Id"],p["Código"],p["Nome"],q,type,note);}
 public void Cancel(int id){Atomic(()=>{var v=Data.Tables["Vendas"].Rows.Find(id);if(v==null||v["Situação"].ToString()!="Concluída")throw new Exception("Esta venda já está cancelada.");foreach(DataRow i in Data.Tables["Itens"].Select("Venda = "+id)){var p=Data.Tables["Produtos"].Rows.Find(i["Produto"]);p["Estoque"]=(decimal)p["Estoque"]+(decimal)i["Quantidade"];Move(p,(decimal)i["Quantidade"],"Cancelamento","Venda nº "+id);}v["Situação"]="Cancelada";});}
}
class Dialog : Form {
 public TableLayoutPanel Fields=new TableLayoutPanel();public FlowLayoutPanel Buttons=new FlowLayoutPanel();int row=0;
 public Dialog(string title,int width=560,int height=430){Text=title;Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);Size=new Size(width,Math.Min(height,Screen.PrimaryScreen.WorkingArea.Height-24));StartPosition=FormStartPosition.CenterParent;Font=Theme.Font;BackColor=Theme.Surface;FormBorderStyle=FormBorderStyle.FixedDialog;MinimizeBox=false;MaximizeBox=false;
  Fields.Dock=DockStyle.Fill;Fields.Padding=new Padding(14);Fields.ColumnCount=2;Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,140));Fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));Fields.AutoScroll=true;Controls.Add(Fields);
  Buttons.BackColor=Color.FromArgb(228,231,235);Buttons.Dock=DockStyle.Bottom;Buttons.Height=52;Buttons.Padding=new Padding(8);Buttons.FlowDirection=FlowDirection.RightToLeft;Controls.Add(Buttons);
 }
 public void Add(string label,Control c){Fields.RowStyles.Add(new RowStyle(SizeType.Absolute,32));Fields.Controls.Add(new Label{Text=label,AutoSize=true,Anchor=AnchorStyles.Left},0,row);c.Dock=DockStyle.Fill;Fields.Controls.Add(c,1,row++);}
 public TextBox TextField(string label,string value=""){var c=new TextBox{Text=value};Add(label,c);return c;}
 public NumericUpDown Number(string label,decimal value=0,decimal max=100000000, int decimals=2){var c=new NumericUpDown{Maximum=max,DecimalPlaces=decimals,Value=Math.Min(max,Math.Max(0,value)),ThousandsSeparator=true};Add(label,c);return c;}
 public ComboBox Choice(string label,string[] choices){var c=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList};c.Items.AddRange(choices);if(c.Items.Count>0)c.SelectedIndex=0;Add(label,c);return c;}
 public void Commit(Action action){var cancel=new Button{Text="Sair",Width=95,Height=32};Theme.Button(cancel);cancel.Click+=(s,e)=>Close();Buttons.Controls.Add(cancel);CancelButton=cancel;var save=new Button{Text="✓ Salvar",Width=120,Height=32};Theme.Button(save);save.Width=120;save.Click+=(s,e)=>{try{action();DialogResult=DialogResult.OK;Close();}catch(Exception ex){MessageBox.Show(this,ex.Message,"Verifique os dados",MessageBoxButtons.OK,MessageBoxIcon.Warning);}};Buttons.Controls.Add(save);AcceptButton=save;}
}
partial class MainForm : Form {
 Store db;Panel content=new Panel();DataGridView grid;TextBox search;Label summary;string page="";bool preview;int previewTab;string activePreviewMode="";ComboBox searchBy;ComboBox stateFilter;
 public MainForm(Store store,bool smoke,string previewMode=""){db=store;db.ImportPortfolio();db.FillMissingMarketReferences();preview=smoke;activePreviewMode=previewMode;previewTab=previewMode=="--preview-product-costs"?1:previewMode=="--preview-product-other"?2:0;if(smoke&&db.Data.Tables["Produtos"].Rows.Count==0){db.Data.Tables["Produtos"].Rows.Add(1,"001","VINHO TINTO MALBEC 750ML","Vinícola Exemplo",50m,80m,24m,"Sim");db.Data.Tables["Produtos"].Rows.Add(2,"002","ESPUMANTE BRUT 750ML","Vinícola Exemplo",32m,55m,18m,"Sim");db.Data.Tables["Produtos"].Rows.Add(3,"003","VINHO BRANCO CHARDONNAY 750ML","Vinícola Exemplo",38m,65m,12m,"Sim");}Text="VIDEIRA GESTÃO • Gestão de empresas";Size=new Size(1366,768);MinimumSize=new Size(1080,650);WindowState=FormWindowState.Maximized;StartPosition=FormStartPosition.CenterScreen;Font=Theme.Font;BackColor=Theme.Surface;
  var menus=new MenuStrip{BackColor=Color.White,Font=Theme.Font,Padding=new Padding(3,4,0,4)};Menu(menus,"Geral",new[]{"Início","Minha empresa","Clientes","Fornecedores","Backup","Restaurar backup","Sair"});Menu(menus,"Estoque",new[]{"Produtos","Mercado","Precificação","Entradas de estoque","Movimentações","Inventário"});Menu(menus,"Comercial",new[]{"Novo orçamento","Orçamentos","Nova venda","Vendas"});Menu(menus,"Financeiro",new[]{"Resumo financeiro","Despesas","Taxa de maquininha","Entregas taxas"});Menu(menus,"Relatórios",new[]{"Vendas","Movimentações","Inventário","Resumo financeiro"});MainMenuStrip=menus;
  Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);content.Dock=DockStyle.Fill;Controls.Add(content);Controls.Add(menus);var status=new StatusStrip();status.Items.Add("VIDEIRA GESTÃO 4.1    |    Login e banco online    |    Gestão de produtos e vendas");Controls.Add(status);var onlineMenu=new ToolStripMenuItem("Online");onlineMenu.DropDownItems.Add("Sincronizar dados",null,(s,e)=>Run(()=>{db.ReloadCloud();Home();}));menus.Items.Add(onlineMenu);Home();KeyPreview=true;KeyDown+=(s,e)=>{if(e.KeyCode==Keys.F8&&(page=="Produtos"||page=="Inventário"||page=="Vendas"||page=="Fornecedores"||page=="Clientes")){RefreshGrid();e.Handled=true;}};
  if(preview){Shown+=(s,e)=>{if(previewMode=="--preview-market"||previewMode=="--preview-market-edit")MarketPage();else if(previewMode=="--preview-finance"||previewMode=="--preview-finance-all")FinancePage();else if(previewMode=="--preview-pricing")PricingPage();else if(previewMode=="--preview-expenses"||previewMode=="--preview-materials")ExpenseHub();else if(previewMode=="--preview-quotes")QuotesPage();else if(previewMode!="--preview-home")ShowPage("Produtos");var timer=new Timer{Interval=1000};timer.Tick+=(a,b)=>{timer.Stop();Form target=Application.OpenForms[Application.OpenForms.Count-1];using(var bmp=new Bitmap(target.Width,target.Height)){target.DrawToBitmap(bmp,new Rectangle(0,0,target.Width,target.Height));bmp.Save(Path.Combine(Environment.CurrentDirectory,"work",previewMode.Replace("--"," ").Trim()+".png"));}if(target!=this)target.Close();Close();};timer.Start();if(previewMode=="--preview-markup")MarkupEditor(db.Data.Tables["Produtos"].Rows[0],null,()=>{});if(previewMode=="--preview-market-edit")EditMarket(db.Data.Tables["Mercado"].Rows[0],()=>{});if(previewMode.StartsWith("--preview-sale")||previewMode.StartsWith("--preview-lookup"))Sale();if(previewMode.StartsWith("--preview-company"))CompanyForm();if(previewMode.StartsWith("--preview-quote")&&previewMode!="--preview-quotes")QuoteForm();if(previewMode=="--preview-message"){db.Company["Nome fantasia"]="VIDEIRA VINHOS";var cart=new DataTable();cart.Columns.Add("Produto",typeof(int));cart.Columns.Add("Quantidade",typeof(decimal));cart.Columns.Add("Preço",typeof(decimal));var p=db.Data.Tables["Produtos"].Rows.Find(1);p["País"]="Argentina";p["Uva"]="Malbec";p["Safra"]="2022";p["Volume ml"]=750m;cart.Rows.Add(1,2m,80m);int quote=db.Quote(cart,"Cliente de exemplo","","Pix",DateTime.Today.AddDays(7),"Retirada na loja.");QuoteText(db.Data.Tables["Orçamentos"].Rows.Find(quote));}if(previewMode.StartsWith("--preview-product")&&previewMode!="--preview-product-list")Product(null);if(previewMode=="--preview-expense-flow"){ExpenseEditor("Despesas",null,()=>FinancePage());}if(previewMode=="--preview-navigation"){Home();ShowPage("Produtos");ShowPage("Inventário");Home();ShowPage("Produtos");search.Text="OR";search.Text="";stateFilter.SelectedIndex=1;stateFilter.SelectedIndex=0;System.IO.File.WriteAllText(Path.Combine(Environment.CurrentDirectory,"work","navigation-result.txt"),"PASS: abrir Produtos, Inventário, reabrir Produtos e filtrar sem erro de conversão.");}};}
 }
 new void Menu(MenuStrip m,string name,string[] entries){var item=new ToolStripMenuItem(name){Image=Theme.Icon("menu"),Padding=new Padding(6,2,12,2)};foreach(string entry in entries){string x=entry;item.DropDownItems.Add(x,null,(s,e)=>Run(()=>Navigate(x)));}m.Items.Add(item);}
 void Run(Action a){try{a();}catch(Exception ex){MessageBox.Show(this,ex.Message,"VIDEIRA GESTÃO",MessageBoxButtons.OK,MessageBoxIcon.Warning);}}
 void Navigate(string name){if(name=="Mercado"){MarketPage();return;}if(name=="Sair"){Close();return;}if(name=="Minha empresa"){CompanyForm();return;}if(name=="Despesas"){ExpenseHub();return;}if(name=="Precificação"){PricingPage();return;}if(name=="Orçamentos"){QuotesPage();return;}if(name=="Novo orçamento"){QuoteForm();QuotesPage();return;}if(name=="Início"){Home();return;}if(name=="Nova venda"){Sale();return;}if(name=="Resumo financeiro"){FinancePage();return;}if(name=="Backup"){Backup();return;}if(name=="Restaurar backup"){Restore();return;}ShowPage(name);}
 Button Btn(string text,Action action){var b=new Button{Text=text};Theme.Button(b);if(text=="Ativo / Inativo"||text=="Exportar CSV"||text=="Cancelar venda"||text=="Nova entrada")b.Width=140;b.Click+=(s,e)=>Run(action);return b;}
 void Header(string text){content.Controls.Clear();content.Controls.Add(new TitleBar(text));}
 void ShowPage(string name){if(name=="Entregas taxas"){DeliveryPage();return;}if(name=="Resumo financeiro"){FinancePage();return;}if(name=="Despesas"){ExpenseHub();return;}page=name;Header(name=="Produtos"?"Pesquisa de Produtos":name=="Vendas"?"Gestão de Vendas":name);var body=new Panel{Dock=DockStyle.Fill,Padding=new Padding(10,5,10,5),BackColor=Theme.Surface};content.Controls.Add(body);body.BringToFront();
  var layout=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=4,ColumnCount=1,Margin=Padding.Empty};layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,85));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,30));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,48));body.Controls.Add(layout);
  var filter=new Panel{Dock=DockStyle.Fill};layout.Controls.Add(filter,0,0);searchBy=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Location=new Point(0,28),Width=160};searchBy.Items.AddRange(new[]{"Todos os campos","Código","Nome / descrição"});searchBy.SelectedIndex=0;filter.Controls.Add(new Label{Text="Pesquisar por",Location=new Point(0,7),AutoSize=true});filter.Controls.Add(searchBy);search=new TextBox{Location=new Point(168,28),Width=405};filter.Controls.Add(search);filter.Controls.Add(new Label{Text="Descrição, código ou informação do cadastro",Location=new Point(168,7),AutoSize=true,ForeColor=Color.DimGray});stateFilter=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Location=new Point(588,28),Width=165};stateFilter.Items.AddRange(name=="Produtos"||name=="Inventário"?new[]{"Todos","Ativos","Inativos"}:name=="Vendas"?new[]{"Todas","Concluída","Cancelada"}:new[]{"Todos"});stateFilter.SelectedIndex=0;filter.Controls.Add(new Label{Text="Situação",Location=new Point(588,7),AutoSize=true});filter.Controls.Add(stateFilter);var filterButton=Btn("F8 - Filtrar",RefreshGrid);filterButton.Size=new Size(116,34);filterButton.Location=new Point(769,22);filter.Controls.Add(filterButton);search.TextChanged+=(s,e)=>RefreshGrid();searchBy.SelectedIndexChanged+=(s,e)=>RefreshGrid();stateFilter.SelectedIndexChanged+=(s,e)=>RefreshGrid();
  grid=Theme.Grid();grid.ColumnHeaderMouseClick+=(sender,args)=>{if((page=="Produtos"||page=="Inventário")&&args.ColumnIndex>=0&&grid.Columns[args.ColumnIndex].Name=="Código"){var direction=grid.SortedColumn!=null&&grid.SortedColumn.Name=="Ordem numérica"&&grid.SortOrder==SortOrder.Ascending?System.ComponentModel.ListSortDirection.Descending:System.ComponentModel.ListSortDirection.Ascending;grid.Sort(grid.Columns["Ordem numérica"],direction);grid.Columns["Código"].HeaderCell.SortGlyphDirection=direction==System.ComponentModel.ListSortDirection.Ascending?SortOrder.Ascending:SortOrder.Descending;}};grid.BindingContext=new BindingContext();grid.Dock=DockStyle.Fill;layout.Controls.Add(grid,0,1);summary=new Label{Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft};layout.Controls.Add(summary,0,2);var bottom=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(0,4,0,0),WrapContents=false,BackColor=Color.FromArgb(232,234,237)};layout.Controls.Add(bottom,0,3);
  if(name=="Produtos"){bottom.Controls.Add(Btn("Novo",()=>Product(null)));bottom.Controls.Add(Btn("Editar",()=>Product(Selected("Produtos"))));bottom.Controls.Add(Btn("Ativo / Inativo",()=>{var p=Selected("Produtos");db.Atomic(()=>p["Ativo"]=p["Ativo"].ToString()=="Sim"?"Não":"Sim");RefreshGrid();}));grid.CellDoubleClick+=(s,e)=>Run(()=>Product(Selected("Produtos")));}
  if(name=="Clientes"||name=="Fornecedores"){bottom.Controls.Add(Btn("Novo",()=>Contact(null)));bottom.Controls.Add(Btn("Editar",()=>Contact(Selected(name))));}
  if(name=="Entradas de estoque")bottom.Controls.Add(Btn("Nova entrada",Entry));
  if(name=="Vendas"){bottom.Controls.Add(Btn("Nova venda",Sale));bottom.Controls.Add(Btn("Ver itens",ViewSale));bottom.Controls.Add(Btn("Cancelar venda",()=>{int id=(int)Selected("Vendas")["Id"];if(MessageBox.Show("Cancelar venda nº "+id+" e devolver os itens ao estoque?","Cancelar venda",MessageBoxButtons.YesNo)==DialogResult.Yes){db.Cancel(id);RefreshGrid();}}));}
  if(name=="Taxa de maquininha"){bottom.Controls.Add(Btn("Nova taxa",()=>Rate(null)));bottom.Controls.Add(Btn("Editar taxa",()=>Rate(Selected("Taxas"))));}
  if(name=="Gastos fixos"||name=="Gastos variáveis"){bottom.Controls.Add(Btn("Novo gasto",()=>Expense(null)));bottom.Controls.Add(Btn("Editar",()=>Expense(Selected("Despesas"))));bottom.Controls.Add(Btn("Excluir",()=>{var r=Selected("Despesas");if(MessageBox.Show("Excluir este gasto?","Excluir",MessageBoxButtons.YesNo)==DialogResult.Yes){db.Atomic(()=>db.Data.Tables["Despesas"].Rows.Remove(r));RefreshGrid();}}));}
  if(name=="Produtos"||name=="Inventário"){var mb=Btn("Editar markup",()=>MarkupEditor(Selected("Produtos"),null,RefreshGrid));mb.Width=155;bottom.Controls.Add(mb);}bottom.Controls.Add(Btn("Exportar CSV",Export));bottom.Controls.Add(Btn("Sair",Home));RefreshGrid();
 }
 DataRow Selected(string table){if(grid.CurrentRow==null)throw new Exception("Selecione um registro na tabela.");return db.Data.Tables[table].Rows.Find(Convert.ToInt32(grid.CurrentRow.Cells["Id"].Value));}
 void RefreshGrid(){string previousSort=grid.SortedColumn==null?null:grid.SortedColumn.Name;var previousDirection=grid.SortOrder==SortOrder.Descending?System.ComponentModel.ListSortDirection.Descending:System.ComponentModel.ListSortDirection.Ascending;DataTable t;string q=search==null?"":search.Text.Trim();
  if(page=="Produtos"||page=="Inventário"){t=db.Data.Tables["Produtos"].Copy();foreach(DataRow pending in t.Rows.Cast<DataRow>().ToArray())if(!(bool)pending["Confirmado"])t.Rows.Remove(pending);t.Columns.Add("Markup %",typeof(decimal));t.Columns.Add("Lucro unitário",typeof(decimal));foreach(string key in new[]{"Custo total R$","Gastos rateados R$","Taxa R$"})t.Columns.Add(key,typeof(decimal));t.Columns.Add("Cálculo de custos");foreach(DataRow r in t.Rows){decimal c=(decimal)r["Custo"],p=(decimal)r["Preço"];r["Markup %"]=c==0?0:Store.Money((p-c)/c*100);try{var x=db.CostsAt(r,p);r["Lucro unitário"]=Store.Money(x.Profit);r["Custo total R$"]=Store.Money(x.Base+x.Overhead+x.Fee+x.Variable);r["Gastos rateados R$"]=Store.Money(x.Overhead);r["Taxa R$"]=Store.Money(x.Fee);}catch(Exception ex){r["Cálculo de custos"]=ex.Message;}}}
  else if(page=="Entradas de estoque"||page=="Movimentações")t=db.Data.Tables["Movimentos"].Copy();
  else if(page=="Taxa de maquininha")t=db.Data.Tables["Taxas"].Copy();
  else if(page=="Gastos fixos"||page=="Gastos variáveis"){t=db.Data.Tables["Despesas"].Clone();foreach(DataRow r in db.Data.Tables["Despesas"].Rows)if(r["Categoria"].ToString()==page)t.ImportRow(r);}
  else if(page=="Embalagens"){t=new DataTable();t.Columns.Add("Venda",typeof(int));t.Columns.Add("Data",typeof(DateTime));t.Columns.Add("Unidades",typeof(decimal));t.Columns.Add("Custo embalagem",typeof(decimal));foreach(DataRow v in db.Data.Tables["Vendas"].Rows)if(v["Situação"].ToString()=="Concluída")t.Rows.Add(v["Id"],v["Data"],db.Data.Tables["Itens"].AsEnumerable().Where(r=>(int)r["Venda"]==(int)v["Id"]).Sum(r=>(decimal)r["Quantidade"]),v["Embalagem"]);}
  else if(page=="Resumo financeiro"){t=new DataTable();t.Columns.Add("Indicador");t.Columns.Add("Valor",typeof(decimal));var vs=db.Data.Tables["Vendas"].AsEnumerable().Where(r=>r["Situação"].ToString()=="Concluída");decimal sales=vs.Sum(r=>(decimal)r["Total"]),cost=vs.Sum(r=>(decimal)r["Custo"]),pack=vs.Sum(r=>(decimal)r["Embalagem"]),fee=vs.Sum(r=>(decimal)r["Taxa R$"]),fixedCost=db.Data.Tables["Despesas"].AsEnumerable().Where(r=>r["Categoria"].ToString()=="Gastos fixos").Sum(r=>(decimal)r["Valor"]),variable=db.Data.Tables["Despesas"].AsEnumerable().Where(r=>r["Categoria"].ToString()=="Gastos variáveis").Sum(r=>(decimal)r["Valor"]);t.Rows.Add("Vendas concluídas",sales);t.Rows.Add("Custo dos produtos vendidos",cost);t.Rows.Add("Embalagens • R$ 1 por unidade",pack);t.Rows.Add("Taxas da maquininha",fee);t.Rows.Add("Resultado das vendas",sales-cost-pack-fee);t.Rows.Add("Gastos fixos",fixedCost);t.Rows.Add("Gastos variáveis",variable);t.Rows.Add("Resultado após despesas",sales-cost-pack-fee-fixedCost-variable);}
  else t=db.Data.Tables[page].Copy();
  if(q.Length>0){foreach(DataRow r in t.Rows.Cast<DataRow>().ToArray())if(!(searchBy.SelectedIndex==1&&t.Columns.Contains("Código")?new[]{r["Código"]}:searchBy.SelectedIndex==2&&(t.Columns.Contains("Nome")||t.Columns.Contains("Descrição"))?new[]{r[t.Columns.Contains("Nome")?"Nome":"Descrição"]}:r.ItemArray).Any(x=>Convert.ToString(x).IndexOf(q,StringComparison.CurrentCultureIgnoreCase)>=0))t.Rows.Remove(r);}
  if(stateFilter!=null&&stateFilter.SelectedIndex>0){string col=t.Columns.Contains("Ativo")?"Ativo":t.Columns.Contains("Situação")?"Situação":"";if(col!=""){string val=col=="Ativo"?(stateFilter.SelectedIndex==1?"Sim":"Não"):stateFilter.Text;foreach(DataRow r in t.Rows.Cast<DataRow>().ToArray())if(r[col].ToString()!=val)t.Rows.Remove(r);}}
  if(page=="Produtos"||page=="Inventário")t=t.DefaultView.ToTable(false,new[]{"Id","Código","Nome","Fornecedor","Estoque","Custo","Preço","Embalagem unitária","Ativo","Markup %","Lucro unitário","Custo total R$","Gastos rateados R$","Taxa R$","Cálculo de custos"});if(page=="Produtos"||page=="Inventário"){t.Columns.Add("Ordem numérica",typeof(decimal));foreach(DataRow row in t.Rows){decimal code;row["Ordem numérica"]=decimal.TryParse(row["Código"].ToString(),System.Globalization.NumberStyles.None,System.Globalization.CultureInfo.InvariantCulture,out code)?code:decimal.MaxValue;}}grid.DataSource=null;grid.AutoGenerateColumns=false;grid.Columns.Clear();foreach(DataColumn field in t.Columns)grid.Columns.Add(new DataGridViewTextBoxColumn{Name=field.ColumnName,DataPropertyName=field.ColumnName,HeaderText=field.ColumnName,ValueType=field.DataType,SortMode=DataGridViewColumnSortMode.Automatic});grid.DataSource=t;if(grid.Columns.Contains("Id"))grid.Columns["Id"].Visible=false;if(grid.Columns.Contains("Produto"))grid.Columns["Produto"].Visible=false;
  foreach(DataGridViewColumn col in grid.Columns){if(col.ValueType==typeof(decimal))col.DefaultCellStyle.Format="N2";if(col.ValueType==typeof(DateTime))col.DefaultCellStyle.Format="dd/MM/yyyy HH:mm";}
  if(page=="Produtos"||page=="Inventário"){foreach(DataGridViewRow row in grid.Rows){var bound=row.DataBoundItem as DataRowView;if(bound==null||bound.Row.IsNull("Id"))continue;var p=db.Data.Tables["Produtos"].Rows.Find(bound.Row["Id"]);if(p!=null&&(decimal)p["Estoque mínimo"]>0&&(decimal)p["Estoque"]<=(decimal)p["Estoque mínimo"])row.DefaultCellStyle.ForeColor=Color.Firebrick;}string[] shown={"Código","Nome","EAN","Fornecedor","Custo","Preço","Estoque","Embalagem unitária","Precificação automática","Ativo","Markup %","Lucro unitário","Custo total R$","Gastos rateados R$","Taxa R$","Cálculo de custos"};foreach(DataGridViewColumn col in grid.Columns)col.Visible=shown.Contains(col.Name);grid.Columns["Embalagem unitária"].HeaderText="Embalagem R$";}
  foreach(DataGridViewColumn c in grid.Columns){c.MinimumWidth=c.Name=="Nome"||c.Name=="Descrição"?230:c.Name=="Fornecedor"?145:c.Name=="Cálculo de custos"?150:c.HeaderText.Length>14?125:c.HeaderText.Length>10?110:75;c.FillWeight=c.Name=="Nome"||c.Name=="Descrição"||c.Name=="Indicador"?280:c.Name=="Fornecedor"||c.Name=="Cliente"||c.Name=="Observações"?160:85;if(c.ValueType==typeof(decimal))c.DefaultCellStyle.Alignment=DataGridViewContentAlignment.MiddleRight;}
  if(page=="Produtos"||page=="Inventário"){grid.Columns["Código"].SortMode=DataGridViewColumnSortMode.Programmatic;string sort=previousSort!=null&&grid.Columns.Contains(previousSort)?previousSort:"Ordem numérica";grid.Sort(grid.Columns[sort],previousDirection);if(sort=="Ordem numérica")grid.Columns["Código"].HeaderCell.SortGlyphDirection=previousDirection==System.ComponentModel.ListSortDirection.Ascending?SortOrder.Ascending:SortOrder.Descending;}summary.Text="Registros encontrados: "+t.Rows.Count+(page=="Resumo financeiro"?" • Acumulado de todo o histórico. Gastos fixos são lançados por período.":page=="Produtos"?" • Resultado após fornecedor, embalagem, gastos rateados, taxa de referência e outros custos. Markup % permanece sobre fornecedor.":page=="Taxa de maquininha"?" • Stone: cartão somente 1x. Pix por transferência sem taxa; Pix na maquininha 0,99%. Mesmo preço de venda, sem desconto.":"");
 }
 void Contact(DataRow r){string table=page;using(var d=new Dialog("Cadastro • "+table)){var name=d.TextField("Nome",r==null?"":r["Nome"].ToString());var phone=d.TextField("Telefone",r==null?"":r["Telefone"].ToString());var email=d.TextField("E-mail",r==null?"":r["Email"].ToString());var note=d.TextField("Observações",r==null?"":r["Observações"].ToString());d.Commit(()=>{if(string.IsNullOrWhiteSpace(name.Text))throw new Exception("Informe o nome.");db.Atomic(()=>{if(r==null)db.Data.Tables[table].Rows.Add(db.Next(table),name.Text.Trim(),phone.Text,email.Text,note.Text);else{r["Nome"]=name.Text.Trim();r["Telefone"]=phone.Text;r["Email"]=email.Text;r["Observações"]=note.Text;}});});if(d.ShowDialog(this)==DialogResult.OK)RefreshGrid();}}
 ComboBox Products(){var c=new ComboBox{BindingContext=new BindingContext(),DropDownStyle=ComboBoxStyle.DropDownList};c.DataSource=db.Data.Tables["Produtos"].AsEnumerable().Where(r=>r["Ativo"].ToString()=="Sim"&&(bool)r["Confirmado"]).Select(r=>new ProductChoice{Id=(int)r["Id"],Text=r["Código"]+" • "+r["Nome"]}).ToList();c.DisplayMember="Text";return c;}
 void Entry(){using(var d=new Dialog("Entrada de estoque")){var p=Products();d.Add("Produto",p);var quantity=d.Number("Quantidade",1,100000000,0);var note=d.TextField("Observações");d.Commit(()=>{if(p.SelectedItem==null||quantity.Value<=0)throw new Exception("Selecione produto e quantidade maior que zero.");db.Atomic(()=>{var r=db.Data.Tables["Produtos"].Rows.Find(((ProductChoice)p.SelectedItem).Id);r["Estoque"]=(decimal)r["Estoque"]+quantity.Value;db.Move(r,quantity.Value,"Entrada",note.Text);});});if(d.ShowDialog(this)==DialogResult.OK)RefreshGrid();}}
 void Rate(DataRow r){using(var d=new Dialog("Taxa de maquininha")){var mode=d.TextField("Modalidade",r==null?"":r["Modalidade"].ToString());var rate=d.Number("Taxa %",r==null?0:(decimal)r["Percentual"],100,4);d.Commit(()=>{if(string.IsNullOrWhiteSpace(mode.Text))throw new Exception("Informe a modalidade.");if(mode.Text.Trim().Equals("Pix",StringComparison.OrdinalIgnoreCase)||mode.Text.Trim().Equals("Dinheiro",StringComparison.OrdinalIgnoreCase))throw new Exception("Pix e dinheiro já são formas de pagamento sem taxa neste cadastro. Use uma modalidade de cartão.");if(db.Data.Tables["Taxas"].AsEnumerable().Any(x=>x!=r&&string.Equals(x["Modalidade"].ToString(),mode.Text.Trim(),StringComparison.OrdinalIgnoreCase)))throw new Exception("Modalidade já cadastrada.");db.Atomic(()=>{if(r==null)db.Data.Tables["Taxas"].Rows.Add(db.Next("Taxas"),mode.Text.Trim(),rate.Value);else{r["Modalidade"]=mode.Text.Trim();r["Percentual"]=rate.Value;}});});if(d.ShowDialog(this)==DialogResult.OK)RefreshGrid();}}
 void Expense(DataRow r){string category=page;using(var d=new Dialog(category)){var date=new DateTimePicker{Format=DateTimePickerFormat.Short,Value=r==null?DateTime.Today:(DateTime)r["Data"]};d.Add("Data",date);var desc=d.TextField("Descrição",r==null?"":r["Descrição"].ToString());var val=d.Number("Valor R$",r==null?0:(decimal)r["Valor"]);d.Commit(()=>{if(string.IsNullOrWhiteSpace(desc.Text)||val.Value<=0)throw new Exception("Informe descrição e valor maior que zero.");db.Atomic(()=>{if(r==null)db.Data.Tables["Despesas"].Rows.Add(db.Next("Despesas"),date.Value.Date,category,desc.Text.Trim(),val.Value);else{r["Data"]=date.Value.Date;r["Descrição"]=desc.Text.Trim();r["Valor"]=val.Value;}});});if(d.ShowDialog(this)==DialogResult.OK)RefreshGrid();}}
 void ViewSale(){int id=(int)Selected("Vendas")["Id"];using(var f=new Form{Text="Itens da venda nº "+id,Size=new Size(950,450),StartPosition=FormStartPosition.CenterParent}){var t=db.Data.Tables["Itens"].Clone();foreach(DataRow r in db.Data.Tables["Itens"].Select("Venda = "+id))t.ImportRow(r);var g=new DataGridView{Dock=DockStyle.Fill,DataSource=t,ReadOnly=true,AllowUserToAddRows=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill};f.Controls.Add(g);f.ShowDialog(this);}}
 void Backup(){using(var d=new SaveFileDialog{Filter="Backup Videira (*.xml)|*.xml",FileName="Videira-backup-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".xml"})if(d.ShowDialog(this)==DialogResult.OK){db.Data.WriteXml(d.FileName,XmlWriteMode.WriteSchema);MessageBox.Show("Backup salvo.");}}
 void Restore(){using(var d=new OpenFileDialog{Filter="Backup Videira (*.xml)|*.xml"})if(d.ShowDialog(this)==DialogResult.OK){var incoming=new DataSet();incoming.ReadXml(d.FileName,XmlReadMode.ReadSchema);if(incoming.Tables.Contains("Produtos")&&incoming.Tables.Contains("Vendas")&&incoming.Tables.Contains("Itens"))Store.Upgrade(incoming);foreach(DataTable t in db.Data.Tables){if(!incoming.Tables.Contains(t.TableName))throw new Exception("Backup inválido: tabela ausente.");foreach(DataColumn c in t.Columns)if(!incoming.Tables[t.TableName].Columns.Contains(c.ColumnName)||incoming.Tables[t.TableName].Columns[c.ColumnName].DataType!=c.DataType)throw new Exception("Backup incompatível.");}if(MessageBox.Show("Substituir todos os dados pelo backup selecionado? Uma cópia dos dados atuais será preservada.","Restaurar backup",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;db.Data.WriteXml(Path.Combine(db.Root,"antes-restauracao-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".xml"),XmlWriteMode.WriteSchema);Store.Upgrade(incoming);db.Atomic(()=>db.Data=incoming);Home();MessageBox.Show("Backup restaurado.");}}
 void Export(){using(var d=new SaveFileDialog{Filter="Planilha CSV (*.csv)|*.csv",FileName=page+".csv"})if(d.ShowDialog(this)==DialogResult.OK){var t=(DataTable)grid.DataSource;Func<object,string> quote=x=>"\""+Convert.ToString(x).Replace("\"","\"\"")+"\"";using(var w=new StreamWriter(d.FileName,false,new System.Text.UTF8Encoding(true))){w.WriteLine(string.Join(";",t.Columns.Cast<DataColumn>().Select(c=>quote(c.ColumnName))));foreach(DataRow r in t.Rows)w.WriteLine(string.Join(";",r.ItemArray.Select(x=>quote((x is string&&"=+-@".Contains(((string)x).FirstOrDefault()))?"'"+x:x))));}MessageBox.Show("Relatório exportado.");}}
}
class ProductChoice {public int Id{get;set;}public string Text{get;set;}}
static class Tests {
 static void Assert(bool b,string message){if(!b)throw new Exception(message);}
 public static void Run(){string root=Path.Combine(Environment.CurrentDirectory,"work","VideiraTests-"+Guid.NewGuid());var s=new Store(root);s.Data.Tables["Produtos"].Rows.Add(1,"V001","Vinho","Fornecedor",50m,80m,10m,"Sim");s.Save();var cart=new DataTable();cart.Columns.Add("Produto",typeof(int));cart.Columns.Add("Quantidade",typeof(decimal));cart.Columns.Add("Preço",typeof(decimal));cart.Rows.Add(1,2m,80m);cart.Rows.Add(1,1m,80m);int id=s.Sell(cart,"Teste","Crédito",2.5m);var v=s.Data.Tables["Vendas"].Rows.Find(id);Assert((decimal)v["Embalagem"]==3m,"Embalagem");Assert((decimal)v["Total"]==240m,"Total");Assert((decimal)v["Taxa R$"]==6m,"Taxa");Assert((decimal)v["Resultado"]==81m,"Resultado");Assert((decimal)s.Data.Tables["Produtos"].Rows.Find(1)["Estoque"]==7m,"Baixa de estoque");s=new Store(root);Assert(s.Data.Tables["Vendas"].Rows.Count==1,"Persistência");cart.Rows.Clear();cart.Rows.Add(1,8m,80m);bool failed=false;try{s.Sell(cart,"Teste","Pix",0);}catch{failed=true;}Assert(failed&&s.Data.Tables["Vendas"].Rows.Count==1&&(decimal)s.Data.Tables["Produtos"].Rows.Find(1)["Estoque"]==7m,"Rollback");s.Cancel(id);Assert((decimal)s.Data.Tables["Produtos"].Rows.Find(1)["Estoque"]==10m,"Cancelamento");failed=false;try{s.Cancel(id);}catch{failed=true;}Assert(failed&&(decimal)s.Data.Tables["Produtos"].Rows.Find(1)["Estoque"]==10m,"Cancelamento duplicado");System.IO.File.WriteAllText(Path.Combine(Environment.CurrentDirectory,"work","test-result.txt"),"PASS: embalagem por unidade, total, taxa, resultado, estoque, persistência, venda sem estoque, rollback e cancelamento.");Directory.Delete(root,true);}
}
}











